/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <SpriteKit/SKNode.h>

@class Sprite, SKLabelNode, SKSpriteNode, SKNode;

@interface ActionButton : SKNode {

	float sc;
	Sprite* bg;
	SKLabelNode* txt;
	SKLabelNode* txt2;
	SEL action;
	SKSpriteNode* shadow;
	SKNode* container;
	CGSize offset;
	CGSize margins;

}

@property (retain) SKNode * container; 
@property (assign) float sc; 
@property (retain) SKSpriteNode * shadow; 
@property (retain) Sprite * bg; 
@property (retain) SKLabelNode * txt; 
@property (retain) SKLabelNode * txt2; 
@property (assign) CGSize offset; 
@property (assign) CGSize margins; 
@property (assign) SEL action; 
-(void)setBlue;
-(void)scaleText;
-(void)setText:(id)arg1 text2:(id)arg2 ;
-(void)setYellowButton;
-(void)setGreen;
-(void)setRed;
-(void)setBlue2;
-(void)setBlackButtonInactive;
-(void)setBlackButtonActive;
-(void)setOutlineButtonInactive;
-(void)setOutlineButtonActive;
-(void)setAnagrams;
-(Sprite *)bg;
-(void)setBg:(Sprite *)arg1 ;
-(SKLabelNode *)txt;
-(void)setTxt:(SKLabelNode *)arg1 ;
-(SKLabelNode *)txt2;
-(void)setTxt2:(SKLabelNode *)arg1 ;
-(float)sc;
-(void)setSc:(float)arg1 ;
-(id)init;
-(SKNode *)container;
-(void)setContainer:(SKNode *)arg1 ;
-(SEL)action;
-(void)setOffset:(CGSize)arg1 ;
-(void)setSize:(float)arg1 ;
-(SKSpriteNode *)shadow;
-(void)setText:(id)arg1 ;
-(CGSize)offset;
-(void)setAction:(SEL)arg1 ;
-(CGSize)margins;
-(void)setMargins:(CGSize)arg1 ;
-(void)setShadow:(SKSpriteNode *)arg1 ;
-(void)setButtonText:(id)arg1 ;
-(void)up;
-(void)down;
@end

