/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ADCFilepathContext.h>

@class ADCAdSession, NSNumber, AVAudioPlayer;

@interface ADCAudioPlayerContext : ADCFilepathContext {

	ADCAdSession* _session;
	NSNumber* _playerID;
	AVAudioPlayer* _player;

}

@property (nonatomic,readonly) ADCAdSession * session;              //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) NSNumber * playerID;                 //@synthesize playerID=_playerID - In the implementation block
@property (nonatomic,readonly) AVAudioPlayer * player;              //@synthesize player=_player - In the implementation block
-(ADCAdSession *)session;
-(id)initWithMessage:(id)arg1 ;
-(BOOL)isValid:(BOOL)arg1 ;
-(AVAudioPlayer *)player;
-(NSNumber *)playerID;
@end

