/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ADCViewController.h>
#import <libobjc.A.dylib/WKNavigationDelegate.h>
#import <MessagesExtension/ADCBrowserControlDelegate.h>

@class ADCBrowserControl, UIImage, WKWebView, UIView, UIImageView, UIActivityIndicatorView, NSString;

@interface ADCBrowser : ADCViewController <WKNavigationDelegate, ADCBrowserControlDelegate> {

	BOOL _shouldCloseOnAppear;
	BOOL _lastRequestWasCanceled;
	/*^block*/id _openHandler;
	/*^block*/id _dismissalHandler;
	ADCBrowserControl* _backButton;
	ADCBrowserControl* _forwardButton;
	ADCBrowserControl* _reloadButton;
	ADCBrowserControl* _closeButton;
	ADCBrowserControl* _stopButton;
	UIImage* _logo;
	UIImage* _backgroundBar;
	UIImage* _backgroundTile;
	WKWebView* _wkWebView;
	double _backgroundLogoWidth;
	double _backgroundLogoHeight;
	UIView* _webViewBackground;
	UIView* _browserBar;
	UIImageView* _browserBarBackgroundImage;
	UIImageView* _backgroundLogo;
	UIActivityIndicatorView* _spinner;
	NSString* _lastRequestURL;

}

@property (nonatomic,retain) ADCBrowserControl * backButton;                       //@synthesize backButton=_backButton - In the implementation block
@property (nonatomic,retain) ADCBrowserControl * forwardButton;                    //@synthesize forwardButton=_forwardButton - In the implementation block
@property (nonatomic,retain) ADCBrowserControl * reloadButton;                     //@synthesize reloadButton=_reloadButton - In the implementation block
@property (nonatomic,retain) ADCBrowserControl * closeButton;                      //@synthesize closeButton=_closeButton - In the implementation block
@property (nonatomic,retain) ADCBrowserControl * stopButton;                       //@synthesize stopButton=_stopButton - In the implementation block
@property (nonatomic,retain) UIImage * logo;                                       //@synthesize logo=_logo - In the implementation block
@property (nonatomic,retain) UIImage * backgroundBar;                              //@synthesize backgroundBar=_backgroundBar - In the implementation block
@property (nonatomic,retain) UIImage * backgroundTile;                             //@synthesize backgroundTile=_backgroundTile - In the implementation block
@property (nonatomic,retain) WKWebView * wkWebView;                                //@synthesize wkWebView=_wkWebView - In the implementation block
@property (assign,nonatomic) double backgroundLogoWidth;                           //@synthesize backgroundLogoWidth=_backgroundLogoWidth - In the implementation block
@property (assign,nonatomic) double backgroundLogoHeight;                          //@synthesize backgroundLogoHeight=_backgroundLogoHeight - In the implementation block
@property (assign,nonatomic) BOOL shouldCloseOnAppear;                             //@synthesize shouldCloseOnAppear=_shouldCloseOnAppear - In the implementation block
@property (assign,nonatomic) BOOL lastRequestWasCanceled;                          //@synthesize lastRequestWasCanceled=_lastRequestWasCanceled - In the implementation block
@property (nonatomic,retain) UIView * webViewBackground;                           //@synthesize webViewBackground=_webViewBackground - In the implementation block
@property (nonatomic,retain) UIView * browserBar;                                  //@synthesize browserBar=_browserBar - In the implementation block
@property (nonatomic,retain) UIImageView * browserBarBackgroundImage;              //@synthesize browserBarBackgroundImage=_browserBarBackgroundImage - In the implementation block
@property (nonatomic,retain) UIImageView * backgroundLogo;                         //@synthesize backgroundLogo=_backgroundLogo - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * spinner;                    //@synthesize spinner=_spinner - In the implementation block
@property (nonatomic,retain) NSString * lastRequestURL;                            //@synthesize lastRequestURL=_lastRequestURL - In the implementation block
@property (nonatomic,copy) id openHandler;                                         //@synthesize openHandler=_openHandler - In the implementation block
@property (nonatomic,copy) id dismissalHandler;                                    //@synthesize dismissalHandler=_dismissalHandler - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(WKWebView *)wkWebView;
-(void)setWkWebView:(WKWebView *)arg1 ;
-(void)setBackgroundBar:(UIImage *)arg1 ;
-(void)setBackgroundTile:(UIImage *)arg1 ;
-(void)setForwardButton:(ADCBrowserControl *)arg1 ;
-(void)setBackgroundLogoWidth:(double)arg1 ;
-(void)setBackgroundLogoHeight:(double)arg1 ;
-(void)setShouldCloseOnAppear:(BOOL)arg1 ;
-(void)setLastRequestWasCanceled:(BOOL)arg1 ;
-(void)closeOnAppear;
-(UIImage *)backgroundBar;
-(UIImage *)backgroundTile;
-(ADCBrowserControl *)forwardButton;
-(BOOL)shouldCloseOnAppear;
-(void)setBrowserBar:(UIView *)arg1 ;
-(UIView *)browserBar;
-(void)setWebViewBackground:(UIView *)arg1 ;
-(UIView *)webViewBackground;
-(void)setBrowserBarBackgroundImage:(UIImageView *)arg1 ;
-(UIImageView *)browserBarBackgroundImage;
-(void)setBackgroundLogo:(UIImageView *)arg1 ;
-(UIImageView *)backgroundLogo;
-(double)backgroundLogoWidth;
-(double)backgroundLogoHeight;
-(void)setLoadingState;
-(void)layoutControl:(id)arg1 withPosition:(int)arg2 ;
-(NSString *)lastRequestURL;
-(BOOL)lastRequestWasCanceled;
-(void)setLastRequestURL:(NSString *)arg1 ;
-(void)back;
-(void)showWebView:(id)arg1 ;
-(void)browserControlButtonPushed:(id)arg1 ;
-(void)dealloc;
-(void)close;
-(void)stop;
-(id)initWithDict:(id)arg1 ;
-(void)reload;
-(void)viewWillAppear:(BOOL)arg1 ;
-(ADCBrowserControl *)backButton;
-(void)setBackButton:(ADCBrowserControl *)arg1 ;
-(void)prepareWithCompletionHandler:(/*^block*/id)arg1 ;
-(UIActivityIndicatorView *)spinner;
-(void)setSpinner:(UIActivityIndicatorView *)arg1 ;
-(void)showControls;
-(void)loadRequest:(id)arg1 ;
-(id)dismissalHandler;
-(void)setDismissalHandler:(id)arg1 ;
-(UIImage *)logo;
-(void)setLogo:(UIImage *)arg1 ;
-(void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(/*^block*/id)arg3 ;
-(void)webView:(id)arg1 didFinishNavigation:(id)arg2 ;
-(void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3 ;
-(ADCBrowserControl *)closeButton;
-(void)setCloseButton:(ADCBrowserControl *)arg1 ;
-(void)setStopButton:(ADCBrowserControl *)arg1 ;
-(ADCBrowserControl *)stopButton;
-(void)forward;
-(id)openHandler;
-(void)setOpenHandler:(id)arg1 ;
-(void)setReloadButton:(ADCBrowserControl *)arg1 ;
-(ADCBrowserControl *)reloadButton;
@end

