/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>

@class UIImage, UIImageView;

@interface ADCImageButton : UIView {

	BOOL _sizedImage;
	/*^block*/id _onTap;
	UIImage* _imageObject;
	UIImageView* _imageView;
	CGSize _imageSize;

}

@property (assign,nonatomic,__weak) UIImage * imageObject;                //@synthesize imageObject=_imageObject - In the implementation block
@property (assign,nonatomic,__weak) UIImageView * imageView;              //@synthesize imageView=_imageView - In the implementation block
@property (assign,nonatomic) BOOL sizedImage;                             //@synthesize sizedImage=_sizedImage - In the implementation block
@property (assign,nonatomic) CGSize imageSize;                            //@synthesize imageSize=_imageSize - In the implementation block
@property (nonatomic,copy) id onTap;                                      //@synthesize onTap=_onTap - In the implementation block
@property (nonatomic,retain) UIImage * image; 
+(id)withImageAtPath:(id)arg1 width:(double)arg2 andHeight:(double)arg3 ;
+(id)withImageAtPath:(id)arg1 imageSize:(CGSize)arg2 frame:(CGRect)arg3 cornerRadius:(double)arg4 andBackgroundColor:(id)arg5 ;
-(void)setImageWithPath:(id)arg1 ;
-(id)initWithImageSize:(CGSize)arg1 frame:(CGRect)arg2 cornerRadius:(double)arg3 andBackgroundColor:(id)arg4 ;
-(void)setupTapRecognizer;
-(void)tapRecognized;
-(UIImage *)imageObject;
-(void)setImageObject:(UIImage *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(UIImage *)image;
-(void)setImage:(UIImage *)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(UIImageView *)imageView;
-(CGSize)imageSize;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setImageSize:(CGSize)arg1 ;
-(id)onTap;
-(void)setOnTap:(id)arg1 ;
-(BOOL)sizedImage;
-(void)setSizedImage:(BOOL)arg1 ;
@end

