/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface ADCLog : NSObject {

	NSString* _index;
	long long _level;
	NSString* _message;

}

@property (nonatomic,retain) NSString * index;                //@synthesize index=_index - In the implementation block
@property (assign,nonatomic) long long level;                 //@synthesize level=_level - In the implementation block
@property (nonatomic,retain) NSString * message;              //@synthesize message=_message - In the implementation block
-(id)getDictWithDeviceInfo:(id)arg1 ;
-(id)remappedKeysFromDeviceInfo;
-(id)getLogLevelString;
-(id)initWithLogLevel:(long long)arg1 andMessage:(id)arg2 ;
-(void)getDict:(/*^block*/id)arg1 ;
-(NSString *)index;
-(long long)level;
-(NSString *)message;
-(void)setMessage:(NSString *)arg1 ;
-(void)setIndex:(NSString *)arg1 ;
-(void)setLevel:(long long)arg1 ;
-(id)initFromDict:(id)arg1 ;
@end

