/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSError.h>

@class NSString;

@interface AdColonyAdRequestError : NSError {

	NSString* _zoneId;

}

@property (nonatomic,retain) NSString * zoneId;              //@synthesize zoneId=_zoneId - In the implementation block
+(id)noFillWithZone:(id)arg1 andReason:(id)arg2 ;
+(id)invalidRequestWithZone:(id)arg1 andSuggestion:(id)arg2 ;
+(id)noFillWithZone:(id)arg1 andSuggestion:(id)arg2 ;
+(id)invalidRequestWithZone:(id)arg1 message:(id)arg2 andSuggestion:(id)arg3 ;
+(id)requestErrorWithZone:(id)arg1 code:(unsigned long long)arg2 message:(id)arg3 reason:(id)arg4 andSuggestion:(id)arg5 ;
+(id)invalidRequestWithZone:(id)arg1 message:(id)arg2 reason:(id)arg3 andSuggestion:(id)arg4 ;
+(id)noFillWithZone:(id)arg1 message:(id)arg2 reason:(id)arg3 andSuggestion:(id)arg4 ;
+(id)invalidRequestWithZone:(id)arg1 message:(id)arg2 andReason:(id)arg3 ;
+(id)invalidRequestWithZone:(id)arg1 andReason:(id)arg2 ;
+(id)noFillWithZone:(id)arg1 message:(id)arg2 andReason:(id)arg3 ;
+(id)noFillWithZone:(id)arg1 message:(id)arg2 andSuggestion:(id)arg3 ;
-(id)initWithZone:(id)arg1 code:(long long)arg2 message:(id)arg3 reason:(id)arg4 andSuggestion:(id)arg5 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithDomain:(id)arg1 code:(long long)arg2 userInfo:(id)arg3 ;
-(NSString *)zoneId;
-(void)setZoneId:(NSString *)arg1 ;
@end

