/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALAdLoadDelegate.h>

@class ALSdk, ALLogManager, ALAdLoadState, NSString;

@interface ALAdServiceLoadProxy : NSObject <ALAdLoadDelegate> {

	ALSdk* _sdk;
	ALLogManager* _logger;
	ALAdLoadState* _loadState;

}

@property (nonatomic,retain) ALSdk * sdk;                            //@synthesize sdk=_sdk - In the implementation block
@property (nonatomic,retain) ALLogManager * logger;                  //@synthesize logger=_logger - In the implementation block
@property (nonatomic,retain) ALAdLoadState * loadState;              //@synthesize loadState=_loadState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setSdk:(ALSdk *)arg1 ;
-(ALSdk *)sdk;
-(void)adService:(id)arg1 didLoadAd:(id)arg2 ;
-(void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2 ;
-(id)initWithSdk:(id)arg1 loadState:(id)arg2 ;
-(ALLogManager *)logger;
-(void)setLogger:(ALLogManager *)arg1 ;
-(ALAdLoadState *)loadState;
-(void)setLoadState:(ALAdLoadState *)arg1 ;
@end

