/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALDirectAd.h>

@class NSString, NSURL, NSNumber, UIColor;

@interface ALAdServerAd : ALDirectAd {

	NSString* _rawHTMLSource;

}

@property (nonatomic,copy) NSString * rawHTMLSource;                                         //@synthesize rawHTMLSource=_rawHTMLSource - In the implementation block
@property (nonatomic,retain) NSString * htmlSource; 
@property (nonatomic,retain) NSURL * cachedHTMLURL; 
@property (nonatomic,readonly) NSNumber * mraidCloseDelay; 
@property (nonatomic,readonly) BOOL closeButtonHidden; 
@property (nonatomic,readonly) BOOL expandableAdCloseButtonHidden; 
@property (nonatomic,readonly) unsigned long long expandableAdCloseButtonStyle; 
@property (nonatomic,readonly) UIColor * expandableBackgroundColor; 
-(BOOL)closeButtonHidden;
-(NSNumber *)mraidCloseDelay;
-(id)initWithAdObject:(id)arg1 fullResponse:(id)arg2 source:(unsigned long long)arg3 sdk:(id)arg4 ;
-(NSURL *)cachedHTMLURL;
-(NSString *)htmlSource;
-(NSString *)rawHTMLSource;
-(UIColor *)expandableBackgroundColor;
-(BOOL)expandableAdCloseButtonHidden;
-(unsigned long long)expandableAdCloseButtonStyle;
-(void)setRawHTMLSource:(NSString *)arg1 ;
-(void)setHtmlSource:(NSString *)arg1 ;
-(void)setCachedHTMLURL:(NSURL *)arg1 ;
-(id)videoURL;
-(void)setVideoURL:(id)arg1 ;
@end

