/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ALAd, ALSdk, NSObject, ALAdEventStatsManager, ALGlobalStatsManager;

@interface ALAdEventStatsManagerHelper : NSObject {

	ALAd* _currentAd;
	ALSdk* _sdk;
	long long _createdAtMillis;
	NSObject* _stateLock;
	long long _adShownAtMillis;
	long long _adClickAtMillis;
	long long _adPausedDurationMillis;

}

@property (nonatomic,retain) ALAd * currentAd;                                  //@synthesize currentAd=_currentAd - In the implementation block
@property (nonatomic,retain) ALSdk * sdk;                                       //@synthesize sdk=_sdk - In the implementation block
@property (assign,nonatomic) long long createdAtMillis;                         //@synthesize createdAtMillis=_createdAtMillis - In the implementation block
@property (nonatomic,retain) NSObject * stateLock;                              //@synthesize stateLock=_stateLock - In the implementation block
@property (assign,nonatomic) long long adShownAtMillis;                         //@synthesize adShownAtMillis=_adShownAtMillis - In the implementation block
@property (assign,nonatomic) long long adClickAtMillis;                         //@synthesize adClickAtMillis=_adClickAtMillis - In the implementation block
@property (assign,nonatomic) long long adPausedDurationMillis;                  //@synthesize adPausedDurationMillis=_adPausedDurationMillis - In the implementation block
@property (nonatomic,readonly) ALAdEventStatsManager * adStats; 
@property (nonatomic,readonly) ALGlobalStatsManager * globalStats; 
+(void)trackFetchStatsForAd:(id)arg1 sdk:(id)arg2 ;
+(void)trackRenderTime:(long long)arg1 forAd:(id)arg2 sdk:(id)arg3 ;
+(void)trackCacheStats:(id)arg1 forAd:(id)arg2 sdk:(id)arg3 ;
-(void)setSdk:(ALSdk *)arg1 ;
-(ALSdk *)sdk;
-(ALAd *)currentAd;
-(void)setCurrentAd:(ALAd *)arg1 ;
-(id)initWithAd:(id)arg1 sdk:(id)arg2 ;
-(void)trackInterstitialUsedVideoStream:(BOOL)arg1 ;
-(void)trackAdShown;
-(void)trackAdHidden;
-(void)trackInterstitialPausedDuration:(long long)arg1 ;
-(void)trackInterstitialVideoSkipped;
-(void)trackAdClicked;
-(void)trackInterstitialVideoPercentViewed:(id)arg1 ;
-(void)trackInterstitialPoststitialCodeExecuted;
-(void)setCreatedAtMillis:(long long)arg1 ;
-(long long)createdAtMillis;
-(void)trackAdShownWithWebKit;
-(void)trackUnableToPersistWebKitHTMLPlacementReplacedString;
-(void)trackUnableToRetrieveWebKitHTMLString;
-(void)trackIsStreamingWebKit;
-(void)trackAdViewExpanded;
-(void)trackAdViewContracted;
-(void)trackInterstitialOptOutButtonClickThrough;
-(ALAdEventStatsManager *)adStats;
-(ALGlobalStatsManager *)globalStats;
-(void)setAdShownAtMillis:(long long)arg1 ;
-(long long)adShownAtMillis;
-(long long)adClickAtMillis;
-(void)setAdClickAtMillis:(long long)arg1 ;
-(void)trackTimeSinceShowForStatKey:(id)arg1 ;
-(long long)adPausedDurationMillis;
-(void)setAdPausedDurationMillis:(long long)arg1 ;
-(NSObject *)stateLock;
-(void)setStateLock:(NSObject *)arg1 ;
@end

