/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALPostbackDelegate.h>

@class ALAdService, ALDirectAd, ALAdView, NSURL, NSString;

@interface ALAdServicePostbackProxy : NSObject <ALPostbackDelegate> {

	ALAdService* _adService;
	ALDirectAd* _ad;
	ALAdView* _adView;
	NSURL* _destinationURL;

}

@property (assign,nonatomic,__weak) ALAdService * adService;              //@synthesize adService=_adService - In the implementation block
@property (nonatomic,retain) ALDirectAd * ad;                             //@synthesize ad=_ad - In the implementation block
@property (nonatomic,retain) ALAdView * adView;                           //@synthesize adView=_adView - In the implementation block
@property (nonatomic,retain) NSURL * destinationURL;                      //@synthesize destinationURL=_destinationURL - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)postbackProxyWithAdService:(id)arg1 adView:(id)arg2 ad:(id)arg3 destinationURL:(id)arg4 ;
-(void)postbackService:(id)arg1 didFailToExecutePostback:(id)arg2 errorCode:(long long)arg3 ;
-(ALAdService *)adService;
-(void)setAdService:(ALAdService *)arg1 ;
-(void)clickThrough;
-(void)postbackService:(id)arg1 didExecutePostback:(id)arg2 ;
-(void)setDestinationURL:(NSURL *)arg1 ;
-(NSURL *)destinationURL;
-(ALDirectAd *)ad;
-(void)setAd:(ALDirectAd *)arg1 ;
-(void)setAdView:(ALAdView *)arg1 ;
-(ALAdView *)adView;
@end

