/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALNativeAdPrecacheDelegate.h>

@class NSString, ALCarouselView;

@interface ALCarouselPrecacheRouter : NSObject <ALNativeAdPrecacheDelegate> {

	NSString* _tag;
	ALCarouselView* _carouselView;

}

@property (nonatomic,copy) NSString * tag;                                      //@synthesize tag=_tag - In the implementation block
@property (assign,nonatomic,__weak) ALCarouselView * carouselView;              //@synthesize carouselView=_carouselView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)nativeAdService:(id)arg1 didPrecacheImagesForAd:(id)arg2 ;
-(void)nativeAdService:(id)arg1 didPrecacheVideoForAd:(id)arg2 ;
-(void)nativeAdService:(id)arg1 didFailToPrecacheImagesForAd:(id)arg2 withError:(long long)arg3 ;
-(void)nativeAdService:(id)arg1 didFailToPrecacheVideoForAd:(id)arg2 withError:(long long)arg3 ;
-(id)initWithCarouselView:(id)arg1 ;
-(void)setCarouselView:(ALCarouselView *)arg1 ;
-(ALCarouselView *)carouselView;
-(unsigned long long)cardIndexForAdIndex:(unsigned long long)arg1 ;
-(NSString *)tag;
-(void)setTag:(NSString *)arg1 ;
@end

