/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ALCacheStatsTracker : NSObject {

	BOOL _successfullyPersistedWebKitHTMLString;
	long long _totalDownloadedBytes;
	long long _totalCachedBytes;
	long long _HTMLResourceCacheSuccessCount;
	long long _HTMLResourceCacheFailureCount;

}

@property (assign,nonatomic) long long totalDownloadedBytes;                          //@synthesize totalDownloadedBytes=_totalDownloadedBytes - In the implementation block
@property (assign,nonatomic) long long totalCachedBytes;                              //@synthesize totalCachedBytes=_totalCachedBytes - In the implementation block
@property (assign,nonatomic) long long HTMLResourceCacheSuccessCount;                 //@synthesize HTMLResourceCacheSuccessCount=_HTMLResourceCacheSuccessCount - In the implementation block
@property (assign,nonatomic) long long HTMLResourceCacheFailureCount;                 //@synthesize HTMLResourceCacheFailureCount=_HTMLResourceCacheFailureCount - In the implementation block
@property (assign,nonatomic) BOOL successfullyPersistedWebKitHTMLString;              //@synthesize successfullyPersistedWebKitHTMLString=_successfullyPersistedWebKitHTMLString - In the implementation block
-(BOOL)successfullyPersistedWebKitHTMLString;
-(long long)HTMLResourceCacheSuccessCount;
-(long long)HTMLResourceCacheFailureCount;
-(long long)totalDownloadedBytes;
-(void)setTotalDownloadedBytes:(long long)arg1 ;
-(long long)totalCachedBytes;
-(void)setTotalCachedBytes:(long long)arg1 ;
-(void)setHTMLResourceCacheSuccessCount:(long long)arg1 ;
-(void)setHTMLResourceCacheFailureCount:(long long)arg1 ;
-(void)setSuccessfullyPersistedWebKitHTMLString:(BOOL)arg1 ;
-(void)trackDownloadedBytes:(long long)arg1 ;
-(void)trackCachedBytes:(long long)arg1 ;
-(void)incrementHTMLResourceCacheSuccessCount;
-(void)incrementHTMLResourceCacheFailureCount;
-(void)trackWebKitSuccessfullyCachedHTMLResources:(BOOL)arg1 ;
-(id)description;
@end

