/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALAdLoadDelegate.h>

@class ALInterstitialAd, UIWindow, NSString;

@interface ALInterstitialAdLoadDelegateProxy : NSObject <ALAdLoadDelegate> {

	ALInterstitialAd* _parentAdObject;
	UIWindow* _window;
	NSString* _placement;

}

@property (nonatomic,retain) ALInterstitialAd * parentAdObject;              //@synthesize parentAdObject=_parentAdObject - In the implementation block
@property (nonatomic,retain) UIWindow * window;                              //@synthesize window=_window - In the implementation block
@property (nonatomic,retain) NSString * placement;                           //@synthesize placement=_placement - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)adService:(id)arg1 didLoadAd:(id)arg2 ;
-(void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2 ;
-(void)setParentAdObject:(ALInterstitialAd *)arg1 ;
-(ALInterstitialAd *)parentAdObject;
-(UIWindow *)window;
-(void)setWindow:(UIWindow *)arg1 ;
-(NSString *)placement;
-(void)setPlacement:(NSString *)arg1 ;
@end

