/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ALMediationAdapter;
@class NSString, ALMediationAdapterConfigurationWrapper, ALSdk, ALLogManager;

@interface ALMediationAdapterWrapper : NSObject {

	BOOL _enabled;
	NSString* _adapterName;
	id<ALMediationAdapter> _adapter;
	ALMediationAdapterConfigurationWrapper* _configuration;
	ALSdk* _sdk;
	ALLogManager* _logger;

}

@property (nonatomic,retain) ALSdk * sdk;                                                         //@synthesize sdk=_sdk - In the implementation block
@property (assign,nonatomic,__weak) ALLogManager * logger;                                        //@synthesize logger=_logger - In the implementation block
@property (nonatomic,copy) NSString * adapterName;                                                //@synthesize adapterName=_adapterName - In the implementation block
@property (nonatomic,retain) id<ALMediationAdapter> adapter;                                      //@synthesize adapter=_adapter - In the implementation block
@property (nonatomic,retain) ALMediationAdapterConfigurationWrapper * configuration;              //@synthesize configuration=_configuration - In the implementation block
@property (assign) BOOL enabled;                                                                  //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,copy,readonly) NSString * implementationClassName; 
@property (nonatomic,copy,readonly) NSString * version; 
@property (getter=isReady,nonatomic,readonly) BOOL ready; 
-(void)setSdk:(ALSdk *)arg1 ;
-(ALSdk *)sdk;
-(void)loadNextAd:(id)arg1 andNotify:(id)arg2 ;
-(NSString *)implementationClassName;
-(void)runOperation:(id)arg1 withBlock:(/*^block*/id)arg2 ;
-(void)notifyAdLoadFailed:(long long)arg1 loadState:(id)arg2 ;
-(void)updateLastKnownConfigurationIfNeeded:(id)arg1 ;
-(void)markDisabled:(id)arg1 ;
-(id)initWithAdapterName:(id)arg1 adapter:(id)arg2 sdk:(id)arg3 ;
-(void)prepareNextAd:(id)arg1 ;
-(void)showAd:(id)arg1 overWindow:(id)arg2 andNotify:(id)arg3 ;
-(void)notifyAdLoadSucceeded:(id)arg1 loadState:(id)arg2 ;
-(id)description;
-(BOOL)enabled;
-(void)setEnabled:(BOOL)arg1 ;
-(NSString *)version;
-(BOOL)isReady;
-(ALLogManager *)logger;
-(void)setConfiguration:(ALMediationAdapterConfigurationWrapper *)arg1 ;
-(ALMediationAdapterConfigurationWrapper *)configuration;
-(id<ALMediationAdapter>)adapter;
-(NSString *)adapterName;
-(void)setAdapterName:(NSString *)arg1 ;
-(void)setLogger:(ALLogManager *)arg1 ;
-(void)setAdapter:(id<ALMediationAdapter>)arg1 ;
-(void)initialize:(id)arg1 ;
@end

