/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/ALAd.h>

@class ALMediatedAdInfo, NSString, NSDictionary;

@interface ALMediatedAd : ALAd {

	BOOL _ready;
	ALMediatedAdInfo* _mediatedAdInfo;

}

@property (assign,getter=isReady,nonatomic) BOOL ready;                      //@synthesize ready=_ready - In the implementation block
@property (nonatomic,retain) ALMediatedAdInfo * mediatedAdInfo;              //@synthesize mediatedAdInfo=_mediatedAdInfo - In the implementation block
@property (nonatomic,copy,readonly) NSString * adapterClass; 
@property (nonatomic,copy,readonly) NSString * adapterName; 
@property (nonatomic,readonly) NSDictionary * configuration; 
@property (nonatomic,readonly) long long timeoutSeconds; 
-(BOOL)isEqualToAd:(id)arg1 ;
-(void)setMediatedAdInfo:(ALMediatedAdInfo *)arg1 ;
-(ALMediatedAdInfo *)mediatedAdInfo;
-(NSString *)adapterClass;
-(id)initWithAdObject:(id)arg1 fullAdResponse:(id)arg2 source:(unsigned long long)arg3 sdk:(id)arg4 ;
-(id)initWithOriginalAd:(id)arg1 isReady:(BOOL)arg2 adInfo:(id)arg3 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isReady;
-(NSDictionary *)configuration;
-(long long)timeoutSeconds;
-(NSString *)adapterName;
-(void)setReady:(BOOL)arg1 ;
@end

