/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALMediationAdLoadDelegate.h>

@class ALMediationAdapterWrapper, ALAdapterLoadState, NSString;

@interface ALMediationAdLoadDelegateProxy : NSObject <ALMediationAdLoadDelegate> {

	ALMediationAdapterWrapper* _parentWrapper;
	ALAdapterLoadState* _loadState;

}

@property (assign,nonatomic,__weak) ALMediationAdapterWrapper * parentWrapper;              //@synthesize parentWrapper=_parentWrapper - In the implementation block
@property (nonatomic,retain) ALAdapterLoadState * loadState;                                //@synthesize loadState=_loadState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithParentMediationAdapterWrapper:(id)arg1 loadState:(id)arg2 ;
-(void)mediationService:(id)arg1 didLoadAd:(id)arg2 ;
-(void)mediationService:(id)arg1 didFailToLoadAdWithError:(long long)arg2 ;
-(ALAdapterLoadState *)loadState;
-(void)setLoadState:(ALAdapterLoadState *)arg1 ;
-(ALMediationAdapterWrapper *)parentWrapper;
-(void)setParentWrapper:(ALMediationAdapterWrapper *)arg1 ;
@end

