/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALPostbackDelegate.h>

@class ALPostbackRequest, ALPersistentPostbackManager, NSString;

@interface ALPersistentPostbackManagerDelegateProxy : NSObject <ALPostbackDelegate> {

	ALPostbackRequest* _postback;
	ALPersistentPostbackManager* _postbackManager;

}

@property (nonatomic,retain) ALPostbackRequest * postback;                                      //@synthesize postback=_postback - In the implementation block
@property (assign,nonatomic,__weak) ALPersistentPostbackManager * postbackManager;              //@synthesize postbackManager=_postbackManager - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)delegateProxyWithPostbackRequest:(id)arg1 postbackManager:(id)arg2 ;
-(void)postbackService:(id)arg1 didFailToExecutePostback:(id)arg2 errorCode:(long long)arg3 ;
-(void)postbackService:(id)arg1 didExecutePostback:(id)arg2 ;
-(void)setPostback:(ALPostbackRequest *)arg1 ;
-(void)setPostbackManager:(ALPersistentPostbackManager *)arg1 ;
-(ALPersistentPostbackManager *)postbackManager;
-(ALPostbackRequest *)postback;
@end

