/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALTask.h>
#import <MessagesExtension/ALAdLoadDelegate.h>

@class NSArray, ALTaskProcessAdWaterfall, NSString;

@interface ALTaskProcessNextWaterfallAd : ALTask <ALAdLoadDelegate> {

	NSArray* _adObjects;
	long long _currentAdIndex;
	ALTaskProcessAdWaterfall* _parentTask;

}

@property (nonatomic,retain) NSArray * adObjects;                                //@synthesize adObjects=_adObjects - In the implementation block
@property (assign,nonatomic) long long currentAdIndex;                           //@synthesize currentAdIndex=_currentAdIndex - In the implementation block
@property (nonatomic,retain) ALTaskProcessAdWaterfall * parentTask;              //@synthesize parentTask=_parentTask - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)adService:(id)arg1 didLoadAd:(id)arg2 ;
-(void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2 ;
-(id)initWithAdIndex:(long long)arg1 allAds:(id)arg2 parentTask:(id)arg3 sdk:(id)arg4 ;
-(void)setAdObjects:(NSArray *)arg1 ;
-(void)setCurrentAdIndex:(long long)arg1 ;
-(long long)currentAdIndex;
-(NSArray *)adObjects;
-(void)preloadAdIfNeeded:(long long)arg1 ;
-(void)processCurrentAd;
-(id)parseAdTypeAdIndex:(long long)arg1 ;
-(void)run;
-(ALTaskProcessAdWaterfall *)parentTask;
-(void)setParentTask:(ALTaskProcessAdWaterfall *)arg1 ;
@end

