/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ALTask.h>
#import <MessagesExtension/ALConnectionManagerDelegate.h>

@class ALDirectAd, NSString;

@interface ALTaskReportReward : ALTask <ALConnectionManagerDelegate> {

	ALDirectAd* _sourceAd;

}

@property (nonatomic,retain) ALDirectAd * sourceAd;                 //@synthesize sourceAd=_sourceAd - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithAd:(id)arg1 sdk:(id)arg2 ;
-(void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3 ;
-(void)connectionVia:(id)arg1 didFailWith:(long long)arg2 ;
-(void)sendApiRequestWith:(id)arg1 ;
-(void)setSourceAd:(ALDirectAd *)arg1 ;
-(ALDirectAd *)sourceAd;
-(void)run;
@end

