/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessagesExtension/MessagesExtension-Structs.h>
@class NSURL, NSString;

@interface ALVASTVideoFile : NSObject {

	NSURL* _sourceVideoURL;
	NSURL* _videoURL;
	unsigned long long _deliveryType;
	NSString* _fileType;
	double _width;
	double _height;
	unsigned long long _bitrate;

}

@property (nonatomic,retain) NSURL * sourceVideoURL;                               //@synthesize sourceVideoURL=_sourceVideoURL - In the implementation block
@property (assign,nonatomic) unsigned long long deliveryType;                      //@synthesize deliveryType=_deliveryType - In the implementation block
@property (nonatomic,copy) NSString * fileType;                                    //@synthesize fileType=_fileType - In the implementation block
@property (assign,nonatomic) double width;                                         //@synthesize width=_width - In the implementation block
@property (assign,nonatomic) double height;                                        //@synthesize height=_height - In the implementation block
@property (assign,nonatomic) unsigned long long bitrate;                           //@synthesize bitrate=_bitrate - In the implementation block
@property (nonatomic,retain) NSURL * videoURL;                                     //@synthesize videoURL=_videoURL - In the implementation block
@property (getter=isVideoStream,nonatomic,readonly) BOOL videoStream; 
+(id)videoFileFromXMLNode:(id)arg1 usingSDK:(id)arg2 ;
+(unsigned long long)deliveryTypeFromString:(id)arg1 ;
+(id)stringFromDeliveryType:(unsigned long long)arg1 ;
-(BOOL)isVideoStream;
-(NSURL *)sourceVideoURL;
-(void)setSourceVideoURL:(NSURL *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)fileType;
-(double)width;
-(double)height;
-(void)setWidth:(double)arg1 ;
-(void)setHeight:(double)arg1 ;
-(void)setFileType:(NSString *)arg1 ;
-(NSURL *)videoURL;
-(void)setVideoURL:(NSURL *)arg1 ;
-(unsigned long long)bitrate;
-(void)setDeliveryType:(unsigned long long)arg1 ;
-(unsigned long long)deliveryType;
-(void)setBitrate:(unsigned long long)arg1 ;
@end

