/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSXMLParserDelegate.h>

@class ALSdk, ALStack, NSMutableString, ALMutableXMLNode, NSError, NSDate, ALLogManager, NSString;

@interface ALXMLParser : NSObject <NSXMLParserDelegate> {

	ALSdk* _sdk;
	ALStack* _nodeStack;
	NSMutableString* _currentText;
	ALMutableXMLNode* _lastParsedNode;
	NSError* _error;
	NSDate* _startTime;

}

@property (nonatomic,retain) ALSdk * sdk;                                    //@synthesize sdk=_sdk - In the implementation block
@property (nonatomic,readonly) ALLogManager * logger; 
@property (nonatomic,retain) ALStack * nodeStack;                            //@synthesize nodeStack=_nodeStack - In the implementation block
@property (nonatomic,retain) NSMutableString * currentText;                  //@synthesize currentText=_currentText - In the implementation block
@property (nonatomic,retain) ALMutableXMLNode * lastParsedNode;              //@synthesize lastParsedNode=_lastParsedNode - In the implementation block
@property (nonatomic,retain) NSError * error;                                //@synthesize error=_error - In the implementation block
@property (nonatomic,retain) NSDate * startTime;                             //@synthesize startTime=_startTime - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)parseData:(id)arg1 error:(id*)arg2 withSDK:(id)arg3 ;
-(void)setSdk:(ALSdk *)arg1 ;
-(ALSdk *)sdk;
-(id)initWithSdk:(id)arg1 ;
-(void)setNodeStack:(ALStack *)arg1 ;
-(void)setLastParsedNode:(ALMutableXMLNode *)arg1 ;
-(ALMutableXMLNode *)lastParsedNode;
-(ALStack *)nodeStack;
-(NSError *)error;
-(void)setError:(NSError *)arg1 ;
-(void)parser:(id)arg1 foundCharacters:(id)arg2 ;
-(void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(void)parser:(id)arg1 parseErrorOccurred:(id)arg2 ;
-(void)parserDidStartDocument:(id)arg1 ;
-(void)parserDidEndDocument:(id)arg1 ;
-(void)parser:(id)arg1 foundCDATA:(id)arg2 ;
-(ALLogManager *)logger;
-(NSDate *)startTime;
-(void)setStartTime:(NSDate *)arg1 ;
-(NSMutableString *)currentText;
-(void)setCurrentText:(NSMutableString *)arg1 ;
-(id)parseData:(id)arg1 error:(id*)arg2 ;
-(void)setupParser;
@end

