/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpriteKit/SKNode.h>

@class SKLabelNode, SKNode, NSString, SKSpriteNode, NSDictionary;

@interface AnagramsScore : SKNode {

	SKLabelNode* score_node;
	SKLabelNode* word_node;
	SKLabelNode* more;
	SKNode* word_list;
	SKNode* score_container;
	SKLabelNode* q;
	BOOL right;
	BOOL gray;
	BOOL _active;
	int words;
	int _score;
	NSString* words_string;
	SKSpriteNode* bg;
	SKSpriteNode* score_bg;
	NSDictionary* _dict_c;
	NSString* _game;
	SKLabelNode* _score_node;
	NSString* _words_string_compact;

}

@property (retain) NSDictionary * dict_c;                        //@synthesize dict_c=_dict_c - In the implementation block
@property (retain) NSString * game;                              //@synthesize game=_game - In the implementation block
@property (assign) BOOL active;                                  //@synthesize active=_active - In the implementation block
@property (assign) BOOL gray; 
@property (retain) SKSpriteNode * score_bg; 
@property (retain) SKSpriteNode * bg; 
@property (assign) int score;                                    //@synthesize score=_score - In the implementation block
@property (retain) SKLabelNode * score_node;                     //@synthesize score_node=_score_node - In the implementation block
@property (assign) int words; 
@property (retain) NSString * words_string; 
@property (retain) NSString * words_string_compact;              //@synthesize words_string_compact=_words_string_compact - In the implementation block
-(SKSpriteNode *)bg;
-(void)setBg:(SKSpriteNode *)arg1 ;
-(void)setWords_string_compact:(NSString *)arg1 ;
-(NSString *)words_string_compact;
-(void)setEnemy;
-(void)Gray;
-(void)setScore:(int)arg1 words:(id)arg2 words_count:(int)arg3 ;
-(NSString *)words_string;
-(void)setWords_string:(NSString *)arg1 ;
-(void)setGray:(BOOL)arg1 ;
-(SKSpriteNode *)score_bg;
-(void)setScore_bg:(SKSpriteNode *)arg1 ;
-(NSDictionary *)dict_c;
-(void)setDict_c:(NSDictionary *)arg1 ;
-(SKLabelNode *)score_node;
-(void)setScore_node:(SKLabelNode *)arg1 ;
-(id)init;
-(void)setActive:(BOOL)arg1 ;
-(int)score;
-(void)setScore:(int)arg1 ;
-(BOOL)active;
-(void)setWords:(int)arg1 ;
-(int)words;
-(NSString *)game;
-(void)setGame:(NSString *)arg1 ;
-(BOOL)gray;
@end

