/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <SceneKit/SCNView.h>
#import <MessagesExtension/SCNPhysicsContactDelegate.h>
#import <libobjc.A.dylib/SCNSceneRendererDelegate.h>

@class SCNNode, FeedbackGenerator, SCNPhysicsBody, SCNScene, NSMutableArray, BasketballBall, SCNGeometry, NSDate, NSTimer, NSMutableString, NSString;

@interface BasketballView : SCNView <SCNPhysicsContactDelegate, SCNSceneRendererDelegate> {

	SCNNode* pole1;
	SCNNode* pole2;
	FeedbackGenerator* feedback1;
	SCNNode* ball;
	SCNNode* basket;
	SCNNode* basket_main;
	SCNNode* net;
	SCNNode* net2;
	SCNNode* net_col;
	SCNNode* ball_shadow;
	SCNNode* selected;
	SCNPhysicsBody* selected_body;
	SCNScene* scene;
	float speed;
	float speed_x;
	CGPoint touch_start;
	CGPoint prev_pos;
	CGPoint touch_pos;
	CGPoint prev_pos2;
	CGVector vec;
	int last_shot;
	int last_shot2;
	int net_frame;
	NSMutableArray* balls;
	BasketballBall* game_ball;
	BasketballBall* game_ball2;
	SCNNode* count1_one;
	SCNNode* count2_one;
	SCNNode* count11;
	SCNNode* count12;
	SCNNode* count21;
	SCNNode* count22;
	SCNNode* time1;
	SCNNode* time2;
	int times1;
	int times2;
	SCNGeometry* mat2;
	NSDate* last_bounce;
	NSDate* last_rim;
	NSTimer* timer2;
	NSMutableArray* net4_textures;
	NSMutableArray* net3_textures;
	NSMutableArray* num_textures;
	NSDate* last;
	int state;
	int seed;
	int score1;
	int score2;
	int player;
	int timer;
	int times;
	float ratio;
	int time;
	NSMutableString* replay_send;
	NSDate* start_time;
	NSMutableArray* replay1;
	NSMutableArray* replay2;
	NSString* mode;

}

@property (assign) int time; 
@property (assign) float ratio; 
@property (assign) int times; 
@property (assign) int player; 
@property (retain) NSMutableArray * replay1; 
@property (retain) NSMutableArray * replay2; 
@property (assign) int score1; 
@property (assign) int score2; 
@property (assign) int seed; 
@property (assign) int state; 
@property (assign) int timer; 
@property (retain) NSDate * start_time; 
@property (retain) NSMutableString * replay_send; 
@property (retain) NSString * mode; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)Skip;
-(void)playReplay;
-(void)touchDownAtPoint:(CGPoint)arg1 ;
-(void)touchMovedToPoint:(CGPoint)arg1 ;
-(void)touchUpAtPoint:(CGPoint)arg1 ;
-(int)score1;
-(int)score2;
-(NSMutableString *)replay_send;
-(void)changeMode:(id)arg1 ;
-(void)setScore1:(int)arg1 ;
-(void)setScore2:(int)arg1 ;
-(void)startRound;
-(NSMutableArray *)replay2;
-(void)bounce:(float)arg1 ;
-(void)rim:(float)arg1 ;
-(void)rem:(id)arg1 ;
-(void)spawn:(int)arg1 ;
-(void)spawn:(int)arg1 player:(int)arg2 ;
-(void)spawn;
-(void)continueRound;
-(void)setReplay_send:(NSMutableString *)arg1 ;
-(void)setStart_time:(NSDate *)arg1 ;
-(NSMutableArray *)replay1;
-(void)setReplay1:(NSMutableArray *)arg1 ;
-(void)setReplay2:(NSMutableArray *)arg1 ;
-(void)setMode:(NSString *)arg1 ;
-(void)unload;
-(int)state;
-(void)reset;
-(int)time;
-(NSString *)mode;
-(int)timer;
-(void)setTimer:(int)arg1 ;
-(void)setState:(int)arg1 ;
-(void)setTime:(int)arg1 ;
-(void)update;
-(int)seed;
-(NSDate *)start_time;
-(id)initWithFrame:(CGRect)arg1 ;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)didReceiveMemoryWarning;
-(BOOL)prefersStatusBarHidden;
-(void)setSeed:(int)arg1 ;
-(int)player;
-(void)setPlayer:(int)arg1 ;
-(float)ratio;
-(void)setRatio:(float)arg1 ;
-(void)setTimes:(int)arg1 ;
-(int)times;
-(void)physicsWorld:(id)arg1 didBeginContact:(id)arg2 ;
-(void)physicsWorld:(id)arg1 didUpdateContact:(id)arg2 ;
-(void)renderer:(id)arg1 willRenderScene:(id)arg2 atTime:(double)arg3 ;
-(void)renderer:(id)arg1 updateAtTime:(double)arg2 ;
-(void)createScene;
@end

