/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <SpriteKit/SKNode.h>

@class SKSpriteNode;

@interface CheckersPiece : SKNode {

	BOOL instant;
	BOOL king;
	BOOL origin_king;
	BOOL last;
	BOOL _force;
	int player;
	float vy;
	float z;
	SKSpriteNode* sprite;
	SKSpriteNode* shadow;
	SKSpriteNode* shade;
	CGPoint pos;
	CGPoint origin;

}

@property (retain) SKSpriteNode * shadow; 
@property (retain) SKSpriteNode * sprite; 
@property (retain) SKSpriteNode * shade; 
@property (assign) int player; 
@property (assign) CGPoint pos; 
@property (assign) CGPoint origin; 
@property (assign) float vy; 
@property (assign) float z; 
@property (assign) BOOL instant; 
@property (assign) BOOL force;                         //@synthesize force=_force - In the implementation block
@property (assign) BOOL king; 
@property (assign) BOOL origin_king; 
@property (assign) BOOL last; 
-(SKSpriteNode *)sprite;
-(void)setVy:(float)arg1 ;
-(void)unblink;
-(void)setPuck:(int)arg1 ;
-(void)blinkWin;
-(void)setSprite:(SKSpriteNode *)arg1 ;
-(float)vy;
-(BOOL)instant;
-(void)setInstant:(BOOL)arg1 ;
-(void)flipImg;
-(void)setPuck:(int)arg1 king:(BOOL)arg2 ;
-(BOOL)king;
-(void)setKing:(BOOL)arg1 ;
-(BOOL)origin_king;
-(void)setOrigin_king:(BOOL)arg1 ;
-(id)init;
-(CGPoint)origin;
-(SKSpriteNode *)shadow;
-(float)z;
-(void)setOrigin:(CGPoint)arg1 ;
-(BOOL)force;
-(void)setForce:(BOOL)arg1 ;
-(void)setShadow:(SKSpriteNode *)arg1 ;
-(void)setZ:(float)arg1 ;
-(void)setLast:(BOOL)arg1 ;
-(void)flip;
-(BOOL)last;
-(int)player;
-(void)setPlayer:(int)arg1 ;
-(void)blink;
-(CGPoint)pos;
-(void)setPos:(CGPoint)arg1 ;
-(SKSpriteNode *)shade;
-(void)setShade:(SKSpriteNode *)arg1 ;
@end

