/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableData, NSInputStream;

@interface CodedInputStream : NSObject {

	NSMutableData* buffer;
	int bufferSize;
	int bufferSizeAfterLimit;
	int bufferPos;
	NSInputStream* input;
	int lastTag;
	int totalBytesRetired;
	int currentLimit;
	int recursionLimit;
	int sizeLimit;

}

@property (retain) NSMutableData * buffer; 
@property (retain) NSInputStream * input; 
+(id)streamWithInputStream:(id)arg1 ;
+(id)streamWithData:(id)arg1 ;
-(long long)readRawLittleEndian64;
-(void)skipRawData:(int)arg1 ;
-(int)readRawLittleEndian32;
-(long long)readRawVarint64;
-(id)readRawData:(int)arg1 ;
-(char)readRawByte;
-(void)recomputeBufferSizeAfterLimit;
-(BOOL)refillBuffer:(BOOL)arg1 ;
-(int)setRecursionLimit:(int)arg1 ;
-(int)setSizeLimit:(int)arg1 ;
-(void)resetSizeCounter;
-(int)bytesUntilLimit;
-(int)readRawVarint32;
-(void)dealloc;
-(id)initWithData:(id)arg1 ;
-(BOOL)isAtEnd;
-(NSInputStream *)input;
-(void)setBuffer:(NSMutableData *)arg1 ;
-(NSMutableData *)buffer;
-(void)commonInit;
-(double)readDouble;
-(float)readFloat;
-(int)readInt32;
-(long long)readInt64;
-(int)readFixed32;
-(long long)readFixed64;
-(id)readString;
-(id)readData;
-(void)setInput:(NSInputStream *)arg1 ;
-(id)initWithInputStream:(id)arg1 ;
-(BOOL)skipField:(int)arg1 ;
-(void)skipMessage;
-(int)readTag;
-(void)checkLastTagWas:(int)arg1 ;
-(int)pushLimit:(int)arg1 ;
-(void)popLimit:(int)arg1 ;
-(long long)readUInt64;
-(BOOL)readBool;
-(int)readUInt32;
-(int)readEnum;
-(int)readSFixed32;
-(long long)readSFixed64;
-(int)readSInt32;
-(long long)readSInt64;
@end

