/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableData, NSOutputStream;

@interface CodedOutputStream : NSObject {

	NSMutableData* buffer;
	int position;
	NSOutputStream* output;

}

@property (retain) NSMutableData * buffer; 
@property (assign) int position; 
@property (retain) NSOutputStream * output; 
+(id)streamWithOutputStream:(id)arg1 bufferSize:(int)arg2 ;
+(id)streamWithOutputStream:(id)arg1 ;
+(id)streamWithData:(id)arg1 ;
-(void)writeData:(int)arg1 value:(id)arg2 ;
-(void)refreshBuffer;
-(int)spaceLeft;
-(void)writeRawData:(id)arg1 offset:(int)arg2 length:(int)arg3 ;
-(void)checkNoSpaceLeft;
-(void)writeDataNoTag:(id)arg1 ;
-(void)dealloc;
-(int)position;
-(void)setBuffer:(NSMutableData *)arg1 ;
-(NSMutableData *)buffer;
-(void)flush;
-(void)setPosition:(int)arg1 ;
-(NSOutputStream *)output;
-(void)setOutput:(NSOutputStream *)arg1 ;
-(void)writeInt32NoTag:(int)arg1 ;
-(void)writeString:(int)arg1 value:(id)arg2 ;
-(void)writeUInt32:(int)arg1 value:(int)arg2 ;
-(void)writeFixed32:(int)arg1 value:(int)arg2 ;
-(void)writeInt32:(int)arg1 value:(int)arg2 ;
-(void)writeSInt32:(int)arg1 value:(int)arg2 ;
-(void)writeSFixed32:(int)arg1 value:(int)arg2 ;
-(void)writeUInt64:(int)arg1 value:(long long)arg2 ;
-(void)writeFixed64:(int)arg1 value:(long long)arg2 ;
-(void)writeInt64:(int)arg1 value:(long long)arg2 ;
-(void)writeSInt64:(int)arg1 value:(long long)arg2 ;
-(void)writeSFixed64:(int)arg1 value:(long long)arg2 ;
-(void)writeBool:(int)arg1 value:(BOOL)arg2 ;
-(void)writeFloat:(int)arg1 value:(float)arg2 ;
-(void)writeDouble:(int)arg1 value:(double)arg2 ;
-(void)writeEnum:(int)arg1 value:(int)arg2 ;
-(id)initWithOutputStream:(id)arg1 data:(id)arg2 ;
-(void)writeRawData:(id)arg1 ;
-(void)writeStringNoTag:(id)arg1 ;
-(void)writeDoubleNoTag:(double)arg1 ;
-(void)writeFloatNoTag:(float)arg1 ;
-(void)writeUInt64NoTag:(long long)arg1 ;
-(void)writeInt64NoTag:(long long)arg1 ;
-(void)writeUInt32NoTag:(int)arg1 ;
-(void)writeFixed64NoTag:(long long)arg1 ;
-(void)writeFixed32NoTag:(int)arg1 ;
-(void)writeSInt32NoTag:(int)arg1 ;
-(void)writeSInt64NoTag:(long long)arg1 ;
-(void)writeSFixed64NoTag:(long long)arg1 ;
-(void)writeSFixed32NoTag:(int)arg1 ;
-(void)writeBoolNoTag:(BOOL)arg1 ;
-(void)writeEnumNoTag:(int)arg1 ;
-(void)writeRawMessageSetExtension:(int)arg1 value:(id)arg2 ;
-(void)writeRawByte:(unsigned char)arg1 ;
-(void)writeTag:(int)arg1 format:(int)arg2 ;
-(void)writeRawVarint32:(int)arg1 ;
-(void)writeRawVarint64:(long long)arg1 ;
-(void)writeRawLittleEndian32:(int)arg1 ;
-(void)writeRawLittleEndian64:(long long)arg1 ;
@end

