/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessagesExtension/MessagesExtension-Structs.h>
@class NSMutableArray;

@interface CurveToSegments : NSObject {

	int m_count;
	float m_distance_tolerance;
	float m_approximation_scale;
	float curve_recursion_limit;
	float curve_distance_epsilon;
	float curve_collinearity_epsilon;
	float curve_angle_tolerance_epsilon;
	float m_angle_tolerance;
	NSMutableArray* m_points;

}

@property (retain) NSMutableArray * m_points; 
-(id)init:(CGPoint)arg1 p2:(CGPoint)arg2 p3:(CGPoint)arg3 ;
-(void)bezier:(CGPoint)arg1 p2:(CGPoint)arg2 p3:(CGPoint)arg3 ;
-(void)recursive_bezier:(CGPoint)arg1 p2:(CGPoint)arg2 p3:(CGPoint)arg3 level:(int)arg4 ;
-(void)setM_points:(NSMutableArray *)arg1 ;
-(NSMutableArray *)m_points;
@end

