/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <SpriteKit/SKNode.h>

@class SKSpriteNode;

@interface DotsLine : SKNode {

	SKSpriteNode* sprite;
	int type;
	int player;
	CGPoint pos;
	CGPoint start;
	CGPoint finish;

}

@property (assign) CGPoint pos; 
@property (assign) CGPoint start; 
@property (assign) CGPoint finish; 
@property (assign) int type; 
@property (assign) int player; 
-(void)setFinish:(CGPoint)arg1 ;
-(void)SetPlayer:(int)arg1 ;
-(void)PrePlay;
-(void)Play;
-(id)init;
-(int)type;
-(void)setType:(int)arg1 ;
-(CGPoint)start;
-(CGPoint)finish;
-(void)setStart:(CGPoint)arg1 ;
-(int)player;
-(void)setPlayer:(int)arg1 ;
-(void)blink;
-(CGPoint)pos;
-(void)setPos:(CGPoint)arg1 ;
@end

