/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURL, NSOperationQueue, NSBlockOperation, FBAdPersistentCacheImpl, NSString, NSData;

@interface FBAdAssetPlaceholder : NSObject {

	BOOL _fetchCompleted;
	unsigned long long _retriesRemaining;
	NSURL* _remoteURL;
	long long _type;
	NSOperationQueue* _queue;
	NSBlockOperation* _fetchOperation;
	FBAdPersistentCacheImpl* _cache;
	FBAdAssetPlaceholder* _retainedSelf;
	NSString* _key;
	NSData* _assetData;
	NSString* _context;

}

@property (assign,nonatomic) unsigned long long retriesRemaining;              //@synthesize retriesRemaining=_retriesRemaining - In the implementation block
@property (assign,nonatomic) BOOL fetchCompleted;                              //@synthesize fetchCompleted=_fetchCompleted - In the implementation block
@property (nonatomic,retain) NSURL * remoteURL;                                //@synthesize remoteURL=_remoteURL - In the implementation block
@property (assign,nonatomic) long long type;                                   //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSOperationQueue * queue;                         //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSBlockOperation * fetchOperation;                //@synthesize fetchOperation=_fetchOperation - In the implementation block
@property (nonatomic,retain) FBAdPersistentCacheImpl * cache;                  //@synthesize cache=_cache - In the implementation block
@property (nonatomic,retain) FBAdAssetPlaceholder * retainedSelf;              //@synthesize retainedSelf=_retainedSelf - In the implementation block
@property (nonatomic,copy) NSString * key;                                     //@synthesize key=_key - In the implementation block
@property (nonatomic,retain) NSData * assetData;                               //@synthesize assetData=_assetData - In the implementation block
@property (nonatomic,copy) NSString * context;                                 //@synthesize context=_context - In the implementation block
-(id)initWithRemoteURL:(id)arg1 key:(id)arg2 ofType:(long long)arg3 cache:(id)arg4 context:(id)arg5 ;
-(void)fetchAsset;
-(void)setFetchCompleted:(BOOL)arg1 ;
-(void)setQueue:(NSOperationQueue *)arg1 ;
-(NSString *)key;
-(NSOperationQueue *)queue;
-(long long)type;
-(void)setType:(long long)arg1 ;
-(NSString *)context;
-(void)setKey:(NSString *)arg1 ;
-(void)setContext:(NSString *)arg1 ;
-(void)setCache:(FBAdPersistentCacheImpl *)arg1 ;
-(FBAdPersistentCacheImpl *)cache;
-(FBAdAssetPlaceholder *)retainedSelf;
-(void)setRetainedSelf:(FBAdAssetPlaceholder *)arg1 ;
-(void)addResultHandler:(/*^block*/id)arg1 ;
-(void)setAssetData:(NSData *)arg1 ;
-(NSData *)assetData;
-(NSURL *)remoteURL;
-(void)setRemoteURL:(NSURL *)arg1 ;
-(NSBlockOperation *)fetchOperation;
-(void)setFetchOperation:(NSBlockOperation *)arg1 ;
-(void)setRetriesRemaining:(unsigned long long)arg1 ;
-(unsigned long long)retriesRemaining;
-(BOOL)fetchCompleted;
@end

