/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessagesExtension/MessagesExtension-Structs.h>
@interface FBAdDSLTouchRecord : NSObject {

	double _touchForce;
	double _touchRadius;
	CGPoint _startLocation;
	CGPoint _endLocation;

}

@property (nonatomic,readonly) CGPoint startLocation;              //@synthesize startLocation=_startLocation - In the implementation block
@property (nonatomic,readonly) CGPoint endLocation;                //@synthesize endLocation=_endLocation - In the implementation block
@property (nonatomic,readonly) double touchForce;                  //@synthesize touchForce=_touchForce - In the implementation block
@property (nonatomic,readonly) double touchRadius;                 //@synthesize touchRadius=_touchRadius - In the implementation block
-(id)initWithTouches:(id)arg1 ;
-(CGPoint)startLocation;
-(CGPoint)endLocation;
-(double)touchForce;
-(double)touchRadius;
@end

