/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UICollectionViewCell.h>

@class NSString, UILabel, UIView;

@interface FBAdChoiceCollectionViewCell : UICollectionViewCell {

	long long _style;
	NSString* _optionTitle;
	NSString* _optionSubtitle;
	UILabel* _optionTitleLabel;
	UILabel* _optionSubtitleLabel;
	UIView* _optionIconView;
	long long _flowType;

}

@property (nonatomic,copy) NSString * optionTitle;                       //@synthesize optionTitle=_optionTitle - In the implementation block
@property (nonatomic,copy) NSString * optionSubtitle;                    //@synthesize optionSubtitle=_optionSubtitle - In the implementation block
@property (nonatomic,retain) UILabel * optionTitleLabel;                 //@synthesize optionTitleLabel=_optionTitleLabel - In the implementation block
@property (nonatomic,retain) UILabel * optionSubtitleLabel;              //@synthesize optionSubtitleLabel=_optionSubtitleLabel - In the implementation block
@property (nonatomic,retain) UIView * optionIconView;                    //@synthesize optionIconView=_optionIconView - In the implementation block
@property (assign,nonatomic) long long flowType;                         //@synthesize flowType=_flowType - In the implementation block
@property (assign,nonatomic) long long style;                            //@synthesize style=_style - In the implementation block
@property (nonatomic,readonly) CGSize preferredSize; 
+(id)reuseId;
-(void)configureForFlowType:(long long)arg1 layoutType:(long long)arg2 ;
-(UIView *)optionIconView;
-(UILabel *)optionTitleLabel;
-(UILabel *)optionSubtitleLabel;
-(NSString *)optionTitle;
-(void)setOptionTitle:(NSString *)arg1 ;
-(NSString *)optionSubtitle;
-(void)setOptionSubtitle:(NSString *)arg1 ;
-(void)setOptionTitleLabel:(UILabel *)arg1 ;
-(void)setOptionSubtitleLabel:(UILabel *)arg1 ;
-(void)setOptionIconView:(UIView *)arg1 ;
-(long long)style;
-(void)setStyle:(long long)arg1 ;
-(void)prepareForReuse;
-(CGSize)preferredSize;
-(void)layoutSubviews;
-(void)setFlowType:(long long)arg1 ;
-(long long)flowType;
@end

