/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <libobjc.A.dylib/WKNavigationDelegate.h>
#import <libobjc.A.dylib/WKUIDelegate.h>
#import <MessagesExtension/FBAdTouchGestureRecognizerDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <libobjc.A.dylib/WKScriptMessageHandler.h>

@protocol FBAdContentContainerDelegate, FBAdViewNavigationPolicy, FBAdPlayableLoggerService;
@class NSObject, FBAdDataModel, WKWebView, NSString, NSURL, WKNavigation;

@interface FBAdWebKitContentContainer : NSObject <WKNavigationDelegate, WKUIDelegate, FBAdTouchGestureRecognizerDelegate, UIGestureRecognizerDelegate, WKScriptMessageHandler> {

	BOOL _loggedImpression;
	BOOL _markupImpressionEventReceived;
	BOOL _overrideMarkupImpressionCheck;
	BOOL _terminated;
	BOOL _isJavascriptAdControlInitialized;
	NSObject*<FBAdContentContainerDelegate> _delegate;
	NSObject*<FBAdViewNavigationPolicy> _parent;
	FBAdDataModel* _offsiteAd;
	double _lastTouchStartTimestamp;
	double _lastTouchCurrentTimestamp;
	double _lastTouchRadius;
	double _lastTouchPressure;
	double _firstImpressionTime;
	long long _placementType;
	WKWebView* _webView;
	NSString* _activationCommand;
	NSURL* _requestURL;
	WKNavigation* _warmupNavigation;
	id<FBAdPlayableLoggerService> _playableLoggerService;
	CGSize _actualAdSize;
	FBAdSize _adSizeType;
	CGSize _minimumSize;
	CGSize _maximumSize;
	CGPoint _lastTouchStartLocation;
	CGPoint _lastTouchCurrentLocation;

}

@property (nonatomic,copy) NSString * activationCommand;                                                             //@synthesize activationCommand=_activationCommand - In the implementation block
@property (assign,nonatomic) BOOL isJavascriptAdControlInitialized;                                                  //@synthesize isJavascriptAdControlInitialized=_isJavascriptAdControlInitialized - In the implementation block
@property (assign,getter=isMarkupImpressionEventReceived,nonatomic) BOOL markupImpressionEventReceived;              //@synthesize markupImpressionEventReceived=_markupImpressionEventReceived - In the implementation block
@property (nonatomic,copy) NSURL * requestURL;                                                                       //@synthesize requestURL=_requestURL - In the implementation block
@property (assign,getter=isTerminated,nonatomic) BOOL terminated;                                                    //@synthesize terminated=_terminated - In the implementation block
@property (nonatomic,retain) WKNavigation * warmupNavigation;                                                        //@synthesize warmupNavigation=_warmupNavigation - In the implementation block
@property (nonatomic,retain) id<FBAdPlayableLoggerService> playableLoggerService;                                    //@synthesize playableLoggerService=_playableLoggerService - In the implementation block
@property (assign,nonatomic,__weak) NSObject*<FBAdContentContainerDelegate> delegate;                                //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) NSObject*<FBAdViewNavigationPolicy> parent;                                      //@synthesize parent=_parent - In the implementation block
@property (assign,nonatomic) CGSize actualAdSize;                                                                    //@synthesize actualAdSize=_actualAdSize - In the implementation block
@property (assign,nonatomic) FBAdSize adSizeType;                                                                    //@synthesize adSizeType=_adSizeType - In the implementation block
@property (nonatomic,retain) FBAdDataModel * offsiteAd;                                                              //@synthesize offsiteAd=_offsiteAd - In the implementation block
@property (assign,nonatomic) CGSize minimumSize;                                                                     //@synthesize minimumSize=_minimumSize - In the implementation block
@property (assign,nonatomic) CGSize maximumSize;                                                                     //@synthesize maximumSize=_maximumSize - In the implementation block
@property (assign,nonatomic) CGPoint lastTouchStartLocation;                                                         //@synthesize lastTouchStartLocation=_lastTouchStartLocation - In the implementation block
@property (assign,nonatomic) CGPoint lastTouchCurrentLocation;                                                       //@synthesize lastTouchCurrentLocation=_lastTouchCurrentLocation - In the implementation block
@property (assign,nonatomic) double lastTouchStartTimestamp;                                                         //@synthesize lastTouchStartTimestamp=_lastTouchStartTimestamp - In the implementation block
@property (assign,nonatomic) double lastTouchCurrentTimestamp;                                                       //@synthesize lastTouchCurrentTimestamp=_lastTouchCurrentTimestamp - In the implementation block
@property (assign,nonatomic) double lastTouchRadius;                                                                 //@synthesize lastTouchRadius=_lastTouchRadius - In the implementation block
@property (assign,nonatomic) double lastTouchPressure;                                                               //@synthesize lastTouchPressure=_lastTouchPressure - In the implementation block
@property (assign,getter=hasLoggedImpression,nonatomic) BOOL loggedImpression;                                       //@synthesize loggedImpression=_loggedImpression - In the implementation block
@property (assign,nonatomic) double firstImpressionTime;                                                             //@synthesize firstImpressionTime=_firstImpressionTime - In the implementation block
@property (nonatomic,readonly) BOOL overrideMarkupImpressionCheck;                                                   //@synthesize overrideMarkupImpressionCheck=_overrideMarkupImpressionCheck - In the implementation block
@property (nonatomic,readonly) WKWebView * webView;                                                                  //@synthesize webView=_webView - In the implementation block
@property (nonatomic,readonly) BOOL logImpression; 
@property (assign,nonatomic) long long placementType;                                                                //@synthesize placementType=_placementType - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)setPlacementType:(long long)arg1 ;
-(double)firstImpressionTime;
-(void)setFirstImpressionTime:(double)arg1 ;
-(BOOL)hasLoggedImpression;
-(BOOL)logImpression;
-(BOOL)isMarkupImpressionEventReceived;
-(void)setMarkupImpressionEventReceived:(BOOL)arg1 ;
-(void)gestureRecognizer:(id)arg1 beganWithTouches:(id)arg2 event:(id)arg3 ;
-(void)gestureRecognizer:(id)arg1 movedWithTouches:(id)arg2 event:(id)arg3 ;
-(void)gestureRecognizer:(id)arg1 endedWithTouches:(id)arg2 event:(id)arg3 ;
-(void)gestureRecognizer:(id)arg1 cancelledWithTouches:(id)arg2 event:(id)arg3 ;
-(CGPoint)lastTouchStartLocation;
-(void)setLastTouchStartLocation:(CGPoint)arg1 ;
-(CGPoint)lastTouchCurrentLocation;
-(void)setLastTouchCurrentLocation:(CGPoint)arg1 ;
-(double)lastTouchStartTimestamp;
-(void)setLastTouchStartTimestamp:(double)arg1 ;
-(double)lastTouchCurrentTimestamp;
-(void)setLastTouchCurrentTimestamp:(double)arg1 ;
-(double)lastTouchRadius;
-(void)setLastTouchRadius:(double)arg1 ;
-(double)lastTouchPressure;
-(void)setLastTouchPressure:(double)arg1 ;
-(CGSize)actualAdSize;
-(void)setActualAdSize:(CGSize)arg1 ;
-(FBAdDataModel *)offsiteAd;
-(FBAdSize)adSizeType;
-(void)setAdSizeType:(FBAdSize)arg1 ;
-(id)initWithAdView:(id)arg1 actualAdSize:(CGSize)arg2 adSizeType:(FBAdSize)arg3 overrideMarkupImpressionCheck:(BOOL)arg4 ;
-(void)setTransparentWebView;
-(id)getView;
-(BOOL)loadAdData:(id)arg1 minViewability:(int)arg2 ;
-(void)prepareToLoadContent;
-(BOOL)loadAdMarkup:(id)arg1 activationCommand:(id)arg2 baseURL:(id)arg3 ;
-(BOOL)loadAdMarkupFromURL:(id)arg1 baseURL:(id)arg2 ;
-(void)initializeJavascriptAdControl;
-(void)initializeJavascriptAdControlWithRetries:(long long)arg1 ;
-(BOOL)logClickWithExtraData:(id)arg1 ;
-(void)updateTouchDataWithTouches:(id)arg1 andEvent:(id)arg2 ;
-(void)handlePlayableWebViewEvent:(id)arg1 params:(id)arg2 ;
-(id)touchInformation;
-(void)initializeLogging:(id)arg1 playableName:(id)arg2 ;
-(void)logButtonClick:(id)arg1 x:(long long)arg2 y:(long long)arg3 ;
-(void)logEndCardShownUp;
-(void)logGameLoaded;
-(void)logLevelCompleted:(id)arg1 ;
-(id)jsMethodToInject;
-(void)setOffsiteAd:(FBAdDataModel *)arg1 ;
-(void)setLoggedImpression:(BOOL)arg1 ;
-(BOOL)overrideMarkupImpressionCheck;
-(NSString *)activationCommand;
-(void)setActivationCommand:(NSString *)arg1 ;
-(BOOL)isJavascriptAdControlInitialized;
-(void)setIsJavascriptAdControlInitialized:(BOOL)arg1 ;
-(WKNavigation *)warmupNavigation;
-(void)setWarmupNavigation:(WKNavigation *)arg1 ;
-(id<FBAdPlayableLoggerService>)playableLoggerService;
-(void)setPlayableLoggerService:(id<FBAdPlayableLoggerService>)arg1 ;
-(NSObject*<FBAdViewNavigationPolicy>)parent;
-(void)setParent:(NSObject*<FBAdViewNavigationPolicy>)arg1 ;
-(NSObject*<FBAdContentContainerDelegate>)delegate;
-(void)setDelegate:(NSObject*<FBAdContentContainerDelegate>)arg1 ;
-(CGSize)minimumSize;
-(CGSize)maximumSize;
-(void)setFrame:(CGRect)arg1 ;
-(WKWebView *)webView;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(void)setMaximumSize:(CGSize)arg1 ;
-(void)setMinimumSize:(CGSize)arg1 ;
-(void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(/*^block*/id)arg3 ;
-(void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3 ;
-(void)webView:(id)arg1 didFinishNavigation:(id)arg2 ;
-(void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3 ;
-(void)webViewWebContentProcessDidTerminate:(id)arg1 ;
-(void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2 ;
-(void)setRequestURL:(NSURL *)arg1 ;
-(NSURL *)requestURL;
-(long long)placementType;
-(BOOL)isTerminated;
-(void)setTerminated:(BOOL)arg1 ;
@end

