/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBAdDSLDataLoaderDelegate
@required
-(void)assetForURL:(id)arg1 withType:(unsigned long long)arg2 completion:(/*^block*/id)arg3;
-(void)didLoadModel:(id)arg1 withAssets:(id)arg2;
-(void)didFailToLoadModel:(id)arg1 withError:(id)arg2;

@end

