/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>
#import <MessagesExtension/FBAdUpdatableView.h>

@class FBNativeAdBase, FBNativeAdViewAttributes, FBAdLabel, UIButton, NSString;

@interface FBAdTemplateFooterView : UIView <FBAdUpdatableView> {

	BOOL _renderCTAOnly;
	BOOL _loaded;
	FBNativeAdBase* _nativeAdBase;
	FBNativeAdViewAttributes* _attributes;
	FBAdLabel* _footerTitleLabel;
	FBAdLabel* _footerBodyLabel;
	UIButton* _ctaButton;

}

@property (assign,nonatomic,__weak) FBNativeAdBase * nativeAdBase;                      //@synthesize nativeAdBase=_nativeAdBase - In the implementation block
@property (assign,nonatomic,__weak) FBNativeAdViewAttributes * attributes;              //@synthesize attributes=_attributes - In the implementation block
@property (assign,nonatomic,__weak) FBAdLabel * footerTitleLabel;                       //@synthesize footerTitleLabel=_footerTitleLabel - In the implementation block
@property (assign,nonatomic,__weak) FBAdLabel * footerBodyLabel;                        //@synthesize footerBodyLabel=_footerBodyLabel - In the implementation block
@property (assign,nonatomic,__weak) UIButton * ctaButton;                               //@synthesize ctaButton=_ctaButton - In the implementation block
@property (assign,nonatomic) BOOL renderCTAOnly;                                        //@synthesize renderCTAOnly=_renderCTAOnly - In the implementation block
@property (assign,getter=isLoaded,nonatomic) BOOL loaded;                               //@synthesize loaded=_loaded - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCtaButton:(UIButton *)arg1 ;
-(UIButton *)ctaButton;
-(void)updateView:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 nativeAdBase:(id)arg2 attributes:(id)arg3 ;
-(void)setNativeAdBase:(FBNativeAdBase *)arg1 ;
-(FBNativeAdBase *)nativeAdBase;
-(double)intrinsicHeightForNativeAd:(id)arg1 width:(double)arg2 ;
-(BOOL)bodyTextExistsInNativeAd:(id)arg1 ;
-(FBAdLabel *)footerTitleLabel;
-(void)setFooterTitleLabel:(FBAdLabel *)arg1 ;
-(FBAdLabel *)footerBodyLabel;
-(void)setFooterBodyLabel:(FBAdLabel *)arg1 ;
-(BOOL)renderCTAOnly;
-(void)setRenderCTAOnly:(BOOL)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(FBNativeAdViewAttributes *)attributes;
-(BOOL)isLoaded;
-(void)setAttributes:(FBNativeAdViewAttributes *)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setLoaded:(BOOL)arg1 ;
-(void)createView;
@end

