/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBAdPersistentCache;
@interface FBAdAssetCache : NSObject {

	id<FBAdPersistentCache> _assetCache;

}

@property (nonatomic,retain) id<FBAdPersistentCache> assetCache;              //@synthesize assetCache=_assetCache - In the implementation block
-(id)assetInMemoryForKey:(id)arg1 ;
-(void)storeAssetInMemory:(id)arg1 forKey:(id)arg2 expiration:(id)arg3 ;
-(BOOL)assetExistsOnDiskForKey:(id)arg1 remoteURL:(id)arg2 ofType:(long long)arg3 ;
-(void)assetForRemoteURL:(id)arg1 ofType:(long long)arg2 resultHandler:(/*^block*/id)arg3 ;
-(void)imageForRemoteURL:(id)arg1 resultHandler:(/*^block*/id)arg2 ;
-(void)videoForRemoteURL:(id)arg1 resultHandler:(/*^block*/id)arg2 ;
-(void)markupForRemoteURL:(id)arg1 resultHandler:(/*^block*/id)arg2 ;
-(void)dataForRemoteURL:(id)arg1 resultHandler:(/*^block*/id)arg2 ;
-(void)zipForRemoteURL:(id)arg1 resultHandler:(/*^block*/id)arg2 ;
-(void)wipeCache;
-(id)storageURLForCache;
-(id<FBAdPersistentCache>)assetCache;
-(void)setAssetCache:(id<FBAdPersistentCache>)arg1 ;
-(id)initWithAssetCache:(id)arg1 ;
@end

