/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/FBAdEventAdHocDataProvider.h>
#import <MessagesExtension/FBAdEventLogger.h>

@class NSUUID, FBAdEventDispatcher, FBAdFunnelLogging, FBAdEventErrorSignalHandler, NSString;

@interface FBAdEventAdapter : NSObject <FBAdEventAdHocDataProvider, FBAdEventLogger> {

	FBAdEventDispatcher* _eventDispatcher;
	FBAdFunnelLogging* _funnelLogger;
	FBAdEventErrorSignalHandler* _signalHandler;

}

@property (nonatomic,retain) FBAdEventDispatcher * eventDispatcher;                    //@synthesize eventDispatcher=_eventDispatcher - In the implementation block
@property (nonatomic,retain) FBAdFunnelLogging * funnelLogger;                         //@synthesize funnelLogger=_funnelLogger - In the implementation block
@property (nonatomic,retain) FBAdEventErrorSignalHandler * signalHandler;              //@synthesize signalHandler=_signalHandler - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSUUID * sessionId; 
@property (nonatomic,readonly) double sessionTime; 
-(FBAdFunnelLogging *)funnelLogger;
-(void)setFunnelLogger:(FBAdFunnelLogging *)arg1 ;
-(id)botDetector;
-(void)logEventOfType:(id)arg1 withPriority:(unsigned long long)arg2 withToken:(id)arg3 withExtraData:(id)arg4 ;
-(void)logImpressionForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logImpressionMissForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logSnapshotForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logVideoEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logCloseEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logBrowserSessionEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logAdCompleteEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logDeviceRotateEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logOffTargetClickEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logUserReturnEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logDebugEventWithSubtype:(id)arg1 code:(long long)arg2 extraData:(id)arg3 ;
-(void)logAdReportingEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logShowAdCalledEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logUXFunnelEventForToken:(id)arg1 extraData:(id)arg2 ;
-(void)logDSLEventForToken:(id)arg1 extraData:(id)arg2 ;
-(void)logClickGuardEventForToken:(id)arg1 withExtraData:(id)arg2 ;
-(void)logPlayableMetricsForToken:(id)arg1 extraData:(id)arg2 ;
-(double)sessionTime;
-(id)initWithFunnelLogger:(id)arg1 networkingService:(id)arg2 ;
-(id)eventConfiguration;
-(void)setupEventDispatcherWithNetworkingService:(id)arg1 ;
-(FBAdEventErrorSignalHandler *)signalHandler;
-(void)setSignalHandler:(FBAdEventErrorSignalHandler *)arg1 ;
-(NSUUID *)sessionId;
-(id)sessionInfo;
-(id)eventStorage;
-(FBAdEventDispatcher *)eventDispatcher;
-(void)setEventDispatcher:(FBAdEventDispatcher *)arg1 ;
@end

