/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>
#import <MessagesExtension/FBAdStoriesPageViewDelegate.h>
#import <MessagesExtension/FBAdViewabilityValidatorDelegate.h>
#import <MessagesExtension/FBAdDisplayable.h>

@protocol FBAdDisplayableViewDelegate;
@class FBAdStoriesPageView, FBNativeAdDataModel, FBAdPlacementDefinition, FBAdViewabilityValidator, NSDate, FBAdTimer, FBAdBlurredOverlayView, FBAdStoriesPageIndicator, UIView, UIScrollView, UIStackView, NSMutableArray, FBAdDetailsAndCTAButtonContainerView, FBGradientView, FBAdAudioMuteButton, NSString;

@interface FBAdStoriesView : UIView <FBAdStoriesPageViewDelegate, FBAdViewabilityValidatorDelegate, FBAdDisplayable> {

	FBAdStoriesPageView* _currentPageView;
	BOOL _impressionSent;
	BOOL _canPlayVideo;
	BOOL _firstPageIsReady;
	id<FBAdDisplayableViewDelegate> _delegate;
	FBNativeAdDataModel* _dataModel;
	FBAdPlacementDefinition* _placementDefinition;
	FBAdViewabilityValidator* _viewabilityValidator;
	long long _currentPage;
	long long _numberOfPages;
	double _volume;
	NSDate* _gestureStartTime;
	FBAdTimer* _forceViewTimer;
	FBAdBlurredOverlayView* _backgroundView;
	FBAdStoriesPageIndicator* _pageIndicator;
	UIView* _headerView;
	UIScrollView* _scrollView;
	UIStackView* _scrollViewPagesContainer;
	NSMutableArray* _cachedPageViews;
	FBAdDetailsAndCTAButtonContainerView* _adDetailsAndCTAButtonContainerView;
	FBGradientView* _topGradientView;
	FBGradientView* _bottomGradientView;
	FBAdAudioMuteButton* _muteButton;
	SCD_Struct_IM9 _overallTime;

}

@property (nonatomic,retain) FBNativeAdDataModel * dataModel;                                                        //@synthesize dataModel=_dataModel - In the implementation block
@property (nonatomic,retain) FBAdPlacementDefinition * placementDefinition;                                          //@synthesize placementDefinition=_placementDefinition - In the implementation block
@property (nonatomic,retain) FBAdViewabilityValidator * viewabilityValidator;                                        //@synthesize viewabilityValidator=_viewabilityValidator - In the implementation block
@property (assign,nonatomic) long long currentPage;                                                                  //@synthesize currentPage=_currentPage - In the implementation block
@property (assign,nonatomic) long long numberOfPages;                                                                //@synthesize numberOfPages=_numberOfPages - In the implementation block
@property (assign,nonatomic) double volume;                                                                          //@synthesize volume=_volume - In the implementation block
@property (nonatomic,retain) NSDate * gestureStartTime;                                                              //@synthesize gestureStartTime=_gestureStartTime - In the implementation block
@property (assign,nonatomic) BOOL firstPageIsReady;                                                                  //@synthesize firstPageIsReady=_firstPageIsReady - In the implementation block
@property (nonatomic,retain) FBAdTimer * forceViewTimer;                                                             //@synthesize forceViewTimer=_forceViewTimer - In the implementation block
@property (assign,nonatomic) SCD_Struct_IM9 overallTime;                                                             //@synthesize overallTime=_overallTime - In the implementation block
@property (nonatomic,retain) FBAdBlurredOverlayView * backgroundView;                                                //@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic,retain) FBAdStoriesPageIndicator * pageIndicator;                                               //@synthesize pageIndicator=_pageIndicator - In the implementation block
@property (nonatomic,retain) UIView * headerView;                                                                    //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,retain) UIScrollView * scrollView;                                                              //@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,retain) UIStackView * scrollViewPagesContainer;                                                 //@synthesize scrollViewPagesContainer=_scrollViewPagesContainer - In the implementation block
@property (nonatomic,retain) NSMutableArray * cachedPageViews;                                                       //@synthesize cachedPageViews=_cachedPageViews - In the implementation block
@property (nonatomic,retain) FBAdDetailsAndCTAButtonContainerView * adDetailsAndCTAButtonContainerView;              //@synthesize adDetailsAndCTAButtonContainerView=_adDetailsAndCTAButtonContainerView - In the implementation block
@property (nonatomic,retain) FBGradientView * topGradientView;                                                       //@synthesize topGradientView=_topGradientView - In the implementation block
@property (nonatomic,retain) FBGradientView * bottomGradientView;                                                    //@synthesize bottomGradientView=_bottomGradientView - In the implementation block
@property (nonatomic,retain) FBAdAudioMuteButton * muteButton;                                                       //@synthesize muteButton=_muteButton - In the implementation block
@property (assign,nonatomic) BOOL canPlayVideo;                                                                      //@synthesize canPlayVideo=_canPlayVideo - In the implementation block
@property (assign,nonatomic,__weak) id<FBAdDisplayableViewDelegate> delegate;                                        //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) SCD_Struct_IM9 currentTime; 
-(void)showAd;
-(void)setDataModel:(FBNativeAdDataModel *)arg1 ;
-(FBAdPlacementDefinition *)placementDefinition;
-(void)setPlacementDefinition:(FBAdPlacementDefinition *)arg1 ;
-(void)didTouchCTA:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)viewabilityValidator:(id)arg1 checkedWithStatus:(long long)arg2 ;
-(FBAdViewabilityValidator *)viewabilityValidator;
-(void)setViewabilityValidator:(FBAdViewabilityValidator *)arg1 ;
-(FBAdDetailsAndCTAButtonContainerView *)adDetailsAndCTAButtonContainerView;
-(void)setAdDetailsAndCTAButtonContainerView:(FBAdDetailsAndCTAButtonContainerView *)arg1 ;
-(void)loadAdFromDataModel:(id)arg1 placementDefinition:(id)arg2 ;
-(void)loadAdFromDataModel:(id)arg1 placementDefinition:(id)arg2 carouselPageNumber:(id)arg3 totalPages:(id)arg4 ;
-(void)destroyAd;
-(void)setPlaying:(BOOL)arg1 forced:(BOOL)arg2 ;
-(void)configureVolume:(double)arg1 ;
-(void)pageViewDidPrepareContent:(id)arg1 ;
-(void)pageView:(id)arg1 didFailToPrepareContentWithError:(id)arg2 ;
-(void)pageViewDidEndDisplayingPage:(id)arg1 ;
-(void)pageView:(id)arg1 didChangeCurrentTime:(SCD_Struct_IM9)arg2 ;
-(void)handlePreviousPageIsRequested;
-(void)handleNextPageIsRequestedByTapping:(BOOL)arg1 ;
-(FBAdStoriesPageIndicator *)pageIndicator;
-(UIStackView *)scrollViewPagesContainer;
-(void)handleAudioMuteButtonTouch;
-(void)loadPage:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)prefetchNextPageIfNeeded;
-(void)timerTicked:(id)arg1 ;
-(BOOL)firstPageIsReady;
-(void)setFirstPageIsReady:(BOOL)arg1 ;
-(FBAdTimer *)forceViewTimer;
-(void)setForceViewTimer:(FBAdTimer *)arg1 ;
-(void)setPageIndicator:(FBAdStoriesPageIndicator *)arg1 ;
-(void)setScrollViewPagesContainer:(UIStackView *)arg1 ;
-(NSMutableArray *)cachedPageViews;
-(void)setCachedPageViews:(NSMutableArray *)arg1 ;
-(id)init;
-(id<FBAdDisplayableViewDelegate>)delegate;
-(void)setDelegate:(id<FBAdDisplayableViewDelegate>)arg1 ;
-(FBAdBlurredOverlayView *)backgroundView;
-(void)layoutSubviews;
-(UIView *)headerView;
-(void)setHeaderView:(UIView *)arg1 ;
-(void)setBackgroundView:(FBAdBlurredOverlayView *)arg1 ;
-(UIScrollView *)scrollView;
-(void)setCurrentPage:(long long)arg1 ;
-(long long)currentPage;
-(void)setNumberOfPages:(long long)arg1 ;
-(long long)numberOfPages;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(SCD_Struct_IM9)currentTime;
-(double)volume;
-(void)setVolume:(double)arg1 ;
-(BOOL)isPlaying;
-(void)longPress:(id)arg1 ;
-(void)setup;
-(void)didTap:(id)arg1 ;
-(FBAdAudioMuteButton *)muteButton;
-(void)setMuteButton:(FBAdAudioMuteButton *)arg1 ;
-(FBNativeAdDataModel *)dataModel;
-(void)setCanPlayVideo:(BOOL)arg1 ;
-(BOOL)canPlayVideo;
-(void)setOverallTime:(SCD_Struct_IM9)arg1 ;
-(SCD_Struct_IM9)overallTime;
-(void)setTopGradientView:(FBGradientView *)arg1 ;
-(FBGradientView *)topGradientView;
-(void)setBottomGradientView:(FBGradientView *)arg1 ;
-(FBGradientView *)bottomGradientView;
-(NSDate *)gestureStartTime;
-(void)setGestureStartTime:(NSDate *)arg1 ;
@end

