/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>
#import <MessagesExtension/FBAdUpdatableView.h>

@class UIImage, UIImageView, UIVisualEffectView, NSString;

@interface FBAdBlurredImageView : UIView <FBAdUpdatableView> {

	BOOL _showBlurImageOnly;
	UIImage* _image;
	UIImageView* _imageView;
	UIImageView* _blurredImageView;
	UIVisualEffectView* _blurEffectView;

}

@property (nonatomic,retain) UIImageView * blurredImageView;                   //@synthesize blurredImageView=_blurredImageView - In the implementation block
@property (nonatomic,retain) UIVisualEffectView * blurEffectView;              //@synthesize blurEffectView=_blurEffectView - In the implementation block
@property (nonatomic,retain) UIImage * image;                                  //@synthesize image=_image - In the implementation block
@property (assign,nonatomic,__weak) UIImageView * imageView;                   //@synthesize imageView=_imageView - In the implementation block
@property (assign,nonatomic) BOOL showBlurImageOnly;                           //@synthesize showBlurImageOnly=_showBlurImageOnly - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)updateView:(BOOL)arg1 ;
-(void)setupViewsWithImage:(id)arg1 ;
-(UIImageView *)blurredImageView;
-(BOOL)showBlurImageOnly;
-(void)setShowBlurImageOnly:(BOOL)arg1 ;
-(void)setBlurredImageView:(UIImageView *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(UIImage *)image;
-(void)setImage:(UIImage *)arg1 ;
-(id)initWithImage:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setBlurEffectView:(UIVisualEffectView *)arg1 ;
-(UIVisualEffectView *)blurEffectView;
@end

