/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>

@class UIColor;

@interface FBAdSmallIcon : UIView {

	unsigned long long _style;
	UIColor* _color;

}

@property (assign,nonatomic) unsigned long long style;              //@synthesize style=_style - In the implementation block
@property (nonatomic,retain) UIColor * color;                       //@synthesize color=_color - In the implementation block
+(double)iconWidthAndHeight;
-(void)drawANLogoRect:(CGRect)arg1 ;
-(void)drawInfoRect:(CGRect)arg1 ;
-(void)drawStarRect:(CGRect)arg1 ;
-(void)drawAdChoicesRect:(CGRect)arg1 ;
-(void)drawAppleRect:(CGRect)arg1 ;
-(void)drawGlobeRect:(CGRect)arg1 ;
-(void)drawBigStarRect:(CGRect)arg1 ;
-(unsigned long long)style;
-(void)setStyle:(unsigned long long)arg1 ;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(id)initWithStyle:(unsigned long long)arg1 color:(id)arg2 ;
@end

