/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>

@protocol FNFAVPlayer, FNFAVPlayerLayer;
@class FBAdKVOController;

@interface FBAdVideoPlayerView : UIView {

	BOOL _initialized;
	id<FNFAVPlayer> _player;
	id<FNFAVPlayerLayer> _playerLayer;
	FBAdKVOController* _readyForDisplayKVOController;
	/*^block*/id _videoReadyToDisplay;

}

@property (assign,nonatomic,__weak) id<FNFAVPlayerLayer> playerLayer;                       //@synthesize playerLayer=_playerLayer - In the implementation block
@property (assign,nonatomic) BOOL initialized;                                              //@synthesize initialized=_initialized - In the implementation block
@property (nonatomic,retain) FBAdKVOController * readyForDisplayKVOController;              //@synthesize readyForDisplayKVOController=_readyForDisplayKVOController - In the implementation block
@property (nonatomic,copy) id videoReadyToDisplay;                                          //@synthesize videoReadyToDisplay=_videoReadyToDisplay - In the implementation block
@property (nonatomic,retain) id<FNFAVPlayer> player;                                        //@synthesize player=_player - In the implementation block
+(void)initialize;
-(void)updateView:(BOOL)arg1 ;
-(id)videoReadyToDisplay;
-(void)setVideoReadyToDisplay:(id)arg1 ;
-(id)initWithVideoReadyToDisplay:(/*^block*/id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 videoReadyToDisplay:(/*^block*/id)arg2 ;
-(void)initVideoLayer;
-(FBAdKVOController *)readyForDisplayKVOController;
-(void)setReadyForDisplayKVOController:(FBAdKVOController *)arg1 ;
-(id)init;
-(void)dealloc;
-(BOOL)initialized;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id<FNFAVPlayer>)player;
-(void)setPlayer:(id<FNFAVPlayer>)arg1 ;
-(id<FNFAVPlayerLayer>)playerLayer;
-(void)setPlayerLayer:(id<FNFAVPlayerLayer>)arg1 ;
-(void)setInitialized:(BOOL)arg1 ;
@end

