/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/FBAdSyncNetworkingService.h>

@protocol FBAdNetworkingService;
@class NSString;

@interface FBAdSyncNetworkingServiceImpl : NSObject <FBAdSyncNetworkingService> {

	id<FBAdNetworkingService> _networkingService;
	/*^block*/id _hostProvider;
	/*^block*/id _contextParameterProvider;

}

@property (nonatomic,readonly) id<FBAdNetworkingService> networkingService;              //@synthesize networkingService=_networkingService - In the implementation block
@property (nonatomic,readonly) id hostProvider;                                          //@synthesize hostProvider=_hostProvider - In the implementation block
@property (nonatomic,readonly) id contextParameterProvider;                              //@synthesize contextParameterProvider=_contextParameterProvider - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)parseResponse:(id)arg1 ;
-(id<FBAdNetworkingService>)networkingService;
-(void)performSynchronizationRequest:(id)arg1 completion:(/*^block*/id)arg2 failed:(/*^block*/id)arg3 ;
-(id)initWithNetworkingService:(id)arg1 hostProvider:(/*^block*/id)arg2 contextParameterProvider:(/*^block*/id)arg3 ;
-(long long)responseTypeForResponseTypeCommand:(id)arg1 ;
-(id)requestTypeCommandForRequestType:(long long)arg1 ;
-(id)hostProvider;
-(id)contextParameterProvider;
@end

