/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessagesExtension/MessagesExtension-Structs.h>
@class NSMapTable;

@interface FBAdKVOController : NSObject {

	NSMapTable* _objectInfosMap;
	opaque_pthread_mutex_t _lock;
	id _observer;

}

@property (nonatomic,__weak,readonly) id observer;              //@synthesize observer=_observer - In the implementation block
+(id)controllerWithObserver:(id)arg1 ;
-(void)dealloc;
-(id)debugDescription;
-(id)observer;
-(id)initWithObserver:(id)arg1 ;
-(id)initWithObserver:(id)arg1 retainObserved:(BOOL)arg2 ;
-(void)_observe:(id)arg1 info:(id)arg2 ;
-(void)_unobserve:(id)arg1 info:(id)arg2 ;
-(void)_unobserve:(id)arg1 ;
-(void)_unobserveAll;
-(void)observe:(id)arg1 keyPath:(id)arg2 options:(unsigned long long)arg3 block:(/*^block*/id)arg4 ;
-(void)observe:(id)arg1 keyPaths:(id)arg2 options:(unsigned long long)arg3 block:(/*^block*/id)arg4 ;
-(void)observe:(id)arg1 keyPath:(id)arg2 options:(unsigned long long)arg3 action:(SEL)arg4 ;
-(void)observe:(id)arg1 keyPaths:(id)arg2 options:(unsigned long long)arg3 action:(SEL)arg4 ;
-(void)observe:(id)arg1 keyPath:(id)arg2 options:(unsigned long long)arg3 context:(void*)arg4 ;
-(void)observe:(id)arg1 keyPaths:(id)arg2 options:(unsigned long long)arg3 context:(void*)arg4 ;
-(void)unobserve:(id)arg1 keyPath:(id)arg2 ;
-(void)unobserve:(id)arg1 ;
-(void)unobserveAll;
@end

