/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/FBDisplayAdAdapter.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>
#import <MessagesExtension/FBAdViewDelegate.h>
#import <MessagesExtension/FBAdDisplayableViewControllerDelegate.h>
#import <MessagesExtension/FBAdViewInternalDelegate.h>

@protocol FBAdDisplayableViewController;
@class UIViewController, FBAdIntroCardTransition, FBAdExitTransition, FBAdViewInternal, NSString;

@interface FBANBannerAdAdapter : FBDisplayAdAdapter <UIViewControllerTransitioningDelegate, FBAdViewDelegate, FBAdDisplayableViewControllerDelegate, FBAdViewInternalDelegate> {

	BOOL _fullScreenAdValid;
	UIViewController*<FBAdDisplayableViewController> _displayableViewController;
	FBAdIntroCardTransition* _introCardTransition;
	FBAdExitTransition* _exitTransition;

}

@property (assign,nonatomic) BOOL fullScreenAdValid;                                                                  //@synthesize fullScreenAdValid=_fullScreenAdValid - In the implementation block
@property (assign,nonatomic,__weak) FBAdIntroCardTransition * introCardTransition;                                    //@synthesize introCardTransition=_introCardTransition - In the implementation block
@property (assign,nonatomic,__weak) FBAdExitTransition * exitTransition;                                              //@synthesize exitTransition=_exitTransition - In the implementation block
@property (nonatomic,retain) UIViewController*<FBAdDisplayableViewController> displayableViewController;              //@synthesize displayableViewController=_displayableViewController - In the implementation block
@property (nonatomic,retain) FBAdViewInternal * adView; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIViewController * viewControllerForPresentingModalView; 
+(void)initialize;
-(void)adViewWillLogImpression:(id)arg1 ;
-(void)adViewDidClick:(id)arg1 ;
-(void)adViewDidFinishHandlingClick:(id)arg1 ;
-(void)adViewDidLoad:(id)arg1 ;
-(void)adView:(id)arg1 didFailWithError:(id)arg2 ;
-(void)displayableAdDidClick:(id)arg1 ;
-(void)displayableAdDidClose:(id)arg1 ;
-(void)displayableAdWillClose:(id)arg1 ;
-(void)displayableAdDidLoad:(id)arg1 ;
-(void)displayableAd:(id)arg1 didFailWithError:(id)arg2 ;
-(void)displayableAdWantsToLogImpression:(id)arg1 withExtraData:(id)arg2 ;
-(void)adPreviewDidClick;
-(void)loadAdData:(id)arg1 forSize:(FBAdSize)arg2 forOrientation:(long long)arg3 forPlacement:(id)arg4 placementDefinition:(id)arg5 dataModelType:(id)arg6 rewardData:(id)arg7 extraHint:(id)arg8 ;
-(id)adDataModel;
-(BOOL)startAdFromRootViewController:(id)arg1 ;
-(BOOL)startAdFromRootViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)loadFullScreenAdWithAdData:(id)arg1 placementDefinition:(id)arg2 extraHint:(id)arg3 ;
-(BOOL)isIntroCardEnabled;
-(FBAdIntroCardTransition *)introCardTransition;
-(FBAdExitTransition *)exitTransition;
-(UIViewController*<FBAdDisplayableViewController>)displayableViewController;
-(void)setDisplayableViewController:(UIViewController*<FBAdDisplayableViewController>)arg1 ;
-(BOOL)fullScreenAdValid;
-(void)setFullScreenAdValid:(BOOL)arg1 ;
-(void)setIntroCardTransition:(FBAdIntroCardTransition *)arg1 ;
-(void)setExitTransition:(FBAdExitTransition *)arg1 ;
-(id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3 ;
-(id)animationControllerForDismissedController:(id)arg1 ;
@end

