/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface FBBDSignalError : NSObject {

	long long _errorCode;
	NSString* _errorName;
	NSString* _errorMessage;
	NSString* _errorStack;

}

@property (nonatomic,readonly) NSDictionary * errorDict; 
@property (nonatomic,readonly) unsigned long long dataSize; 
-(id)initWithErrorCode:(long long)arg1 withErrorName:(id)arg2 withErrorMessage:(id)arg3 withErrorStack:(id)arg4 ;
-(BOOL)isEqualToSignalError:(id)arg1 ;
-(unsigned long long)dataSize;
-(NSDictionary *)errorDict;
@end

