/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/FBBDTapGestureRecognizerDelegate.h>

@protocol BotDetectionConfigProviderDelegate;
@class FBBDTapGestureRecognizer, FBBotDetectionCircularBuffer, NSString;

@interface FBBDTouchSignalManager : NSObject <FBBDTapGestureRecognizerDelegate> {

	FBBDTapGestureRecognizer* _bdTapGestureRecognizer;
	FBBotDetectionCircularBuffer* _circularBuffer;
	int _touchSignalFlags;
	id<BotDetectionConfigProviderDelegate> _configDelegate;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)touchOccuredWithTouches:(id)arg1 withEvent:(id)arg2 ;
-(id)initWithConfigDelegate:(id)arg1 withTouchSignalFlags:(int)arg2 ;
-(id)touchSignalsArray;
@end

