/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBDisplayAdAdapterDelegate;
#import <MessagesExtension/MessagesExtension-Structs.h>
@class UIView, FBNativeAdDataModel, FBAdDataModel;

@interface FBDisplayAdAdapter : NSObject {

	BOOL _needsImpressionClickHandler;
	UIView* _adView;
	FBNativeAdDataModel* _nativeAdData;
	id<FBDisplayAdAdapterDelegate> _delegate;

}

@property (nonatomic,retain) UIView * adView;                                             //@synthesize adView=_adView - In the implementation block
@property (nonatomic,readonly) FBAdDataModel * adDataModel; 
@property (nonatomic,retain) FBNativeAdDataModel * nativeAdData;                          //@synthesize nativeAdData=_nativeAdData - In the implementation block
@property (nonatomic,readonly) SCD_Struct_IM9 duration; 
@property (assign,nonatomic) BOOL needsImpressionClickHandler;                            //@synthesize needsImpressionClickHandler=_needsImpressionClickHandler - In the implementation block
@property (assign,nonatomic,__weak) id<FBDisplayAdAdapterDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)loadAdData:(id)arg1 forSize:(FBAdSize)arg2 forOrientation:(long long)arg3 forPlacement:(id)arg4 placementDefinition:(id)arg5 dataModelType:(id)arg6 rewardData:(id)arg7 extraHint:(id)arg8 ;
-(FBAdDataModel *)adDataModel;
-(BOOL)startAdFromRootViewController:(id)arg1 ;
-(BOOL)startAdFromRootViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)onImpressionWithExtraData:(id)arg1 withPostData:(id)arg2 ;
-(void)onImpressionMissWithExtraData:(id)arg1 withPostData:(id)arg2 ;
-(void)onClickForViewController:(id)arg1 withExtraData:(id)arg2 ;
-(void)registerViewForInteraction:(id)arg1 withViewController:(id)arg2 ;
-(BOOL)setRewardData:(id)arg1 ;
-(void)unregisterView;
-(FBNativeAdDataModel *)nativeAdData;
-(void)setNativeAdData:(FBNativeAdDataModel *)arg1 ;
-(BOOL)needsImpressionClickHandler;
-(void)setNeedsImpressionClickHandler:(BOOL)arg1 ;
-(id<FBDisplayAdAdapterDelegate>)delegate;
-(void)setDelegate:(id<FBDisplayAdAdapterDelegate>)arg1 ;
-(SCD_Struct_IM9)duration;
-(id)initWithDelegate:(id)arg1 ;
-(void)setAdView:(UIView *)arg1 ;
-(UIView *)adView;
@end

