/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <UIKitCore/UIView.h>

@interface FBGradientView : UIView
+(id)newWithColors:(id)arg1 ;
+(id)newWithColors:(id)arg1 opacity:(double)arg2 ;
+(id)newWithColors:(id)arg1 locations:(id)arg2 opacity:(double)arg3 ;
+(id)newWithColors:(id)arg1 locations:(id)arg2 startPoint:(CGPoint)arg3 endPoint:(CGPoint)arg4 opacity:(double)arg5 ;
+(id)newWithColors:(id)arg1 locations:(id)arg2 startPoint:(CGPoint)arg3 endPoint:(CGPoint)arg4 backgroundColor:(id)arg5 opacity:(double)arg6 ;
+(Class)layerClass;
-(void)setOpacity:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setColors:(id)arg1 ;
-(void)setStartPoint:(CGPoint)arg1 ;
-(void)setEndPoint:(CGPoint)arg1 ;
-(void)setLocations:(id)arg1 ;
@end

