/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/FBAdDataModel.h>

@class NSString;

@interface FBHTMLAdDataModel : FBAdDataModel {

	NSString* _markup;
	NSString* _activationCommand;
	long long _orientation;

}

@property (nonatomic,copy,readonly) NSString * markup;                         //@synthesize markup=_markup - In the implementation block
@property (nonatomic,copy,readonly) NSString * activationCommand;              //@synthesize activationCommand=_activationCommand - In the implementation block
@property (nonatomic,readonly) long long orientation;                          //@synthesize orientation=_orientation - In the implementation block
@property (getter=isValid,nonatomic,readonly) BOOL valid; 
+(void)initialize;
-(NSString *)activationCommand;
-(BOOL)isValid;
-(long long)orientation;
-(id)initWithMetadata:(id)arg1 ;
-(NSString *)markup;
@end

