/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/FBAdDataModel.h>

@class UIColor, FBAdImage, NSURL, NSString, NSNumber;

@interface FBInstreamAdDataModel : FBAdDataModel {

	BOOL _adChoicesDisabled;
	BOOL _autoplay;
	BOOL _countdownEnabled;
	BOOL _persistentAdDetails;
	UIColor* _accentColor;
	FBAdImage* _adChoicesIcon;
	NSURL* _adChoicesLinkURL;
	NSString* _adChoicesText;
	UIColor* _backgroundColor;
	NSString* _callToActionText;
	NSURL* _callToActionURL;
	NSString* _countdownFormat;
	FBAdImage* _icon;
	FBAdImage* _image;
	NSURL* _impressionLoggingURL;
	NSURL* _nativeImpressionLoggingURL;
	long long _orientation;
	NSNumber* _skippableSeconds;
	NSString* _subtitle;
	UIColor* _textColor;
	NSString* _title;
	NSURL* _videoHDURL;
	NSURL* _videoURL;
	NSURL* _videoLoggingURL;

}

@property (nonatomic,copy,readonly) UIColor * accentColor;                           //@synthesize accentColor=_accentColor - In the implementation block
@property (nonatomic,readonly) BOOL adChoicesDisabled;                               //@synthesize adChoicesDisabled=_adChoicesDisabled - In the implementation block
@property (nonatomic,readonly) FBAdImage * adChoicesIcon;                            //@synthesize adChoicesIcon=_adChoicesIcon - In the implementation block
@property (nonatomic,copy,readonly) NSURL * adChoicesLinkURL;                        //@synthesize adChoicesLinkURL=_adChoicesLinkURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * adChoicesText;                        //@synthesize adChoicesText=_adChoicesText - In the implementation block
@property (nonatomic,readonly) BOOL autoplay;                                        //@synthesize autoplay=_autoplay - In the implementation block
@property (nonatomic,copy,readonly) UIColor * backgroundColor;                       //@synthesize backgroundColor=_backgroundColor - In the implementation block
@property (nonatomic,copy,readonly) NSString * callToActionText;                     //@synthesize callToActionText=_callToActionText - In the implementation block
@property (nonatomic,copy,readonly) NSURL * callToActionURL;                         //@synthesize callToActionURL=_callToActionURL - In the implementation block
@property (nonatomic,readonly) BOOL countdownEnabled;                                //@synthesize countdownEnabled=_countdownEnabled - In the implementation block
@property (nonatomic,copy,readonly) NSString * countdownFormat;                      //@synthesize countdownFormat=_countdownFormat - In the implementation block
@property (nonatomic,readonly) FBAdImage * icon;                                     //@synthesize icon=_icon - In the implementation block
@property (nonatomic,readonly) FBAdImage * image;                                    //@synthesize image=_image - In the implementation block
@property (nonatomic,copy,readonly) NSURL * impressionLoggingURL;                    //@synthesize impressionLoggingURL=_impressionLoggingURL - In the implementation block
@property (nonatomic,copy,readonly) NSURL * nativeImpressionLoggingURL;              //@synthesize nativeImpressionLoggingURL=_nativeImpressionLoggingURL - In the implementation block
@property (nonatomic,readonly) long long orientation;                                //@synthesize orientation=_orientation - In the implementation block
@property (nonatomic,readonly) BOOL persistentAdDetails;                             //@synthesize persistentAdDetails=_persistentAdDetails - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * skippableSeconds;                     //@synthesize skippableSeconds=_skippableSeconds - In the implementation block
@property (nonatomic,copy,readonly) NSString * subtitle;                             //@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,copy,readonly) UIColor * textColor;                             //@synthesize textColor=_textColor - In the implementation block
@property (nonatomic,copy,readonly) NSString * title;                                //@synthesize title=_title - In the implementation block
@property (nonatomic,copy,readonly) NSURL * videoHDURL;                              //@synthesize videoHDURL=_videoHDURL - In the implementation block
@property (nonatomic,copy,readonly) NSURL * videoURL;                                //@synthesize videoURL=_videoURL - In the implementation block
@property (nonatomic,copy,readonly) NSURL * videoLoggingURL;                         //@synthesize videoLoggingURL=_videoLoggingURL - In the implementation block
@property (getter=isValid,nonatomic,readonly) BOOL valid; 
-(NSString *)adChoicesText;
-(NSURL *)adChoicesLinkURL;
-(FBAdImage *)adChoicesIcon;
-(BOOL)adChoicesDisabled;
-(BOOL)countdownEnabled;
-(NSString *)countdownFormat;
-(NSURL *)impressionLoggingURL;
-(NSURL *)nativeImpressionLoggingURL;
-(BOOL)persistentAdDetails;
-(NSNumber *)skippableSeconds;
-(NSURL *)videoHDURL;
-(NSURL *)videoLoggingURL;
-(id)init;
-(BOOL)isValid;
-(NSString *)title;
-(long long)orientation;
-(FBAdImage *)image;
-(NSString *)subtitle;
-(UIColor *)backgroundColor;
-(FBAdImage *)icon;
-(UIColor *)textColor;
-(NSURL *)videoURL;
-(id)initWithMetadata:(id)arg1 ;
-(BOOL)autoplay;
-(NSString *)callToActionText;
-(NSURL *)callToActionURL;
-(UIColor *)accentColor;
@end

