/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>
#import <MessagesExtension/FBAdCommandProcessorDelegate.h>
#import <MessagesExtension/FBAdDisplayableViewDelegate.h>
#import <MessagesExtension/FBAdDisplayableViewController.h>

@protocol FBAdDisplayableViewControllerDelegate, FBAdFunnelLoggingDelegate;
@class FBAdDataModel, FBNativeAdDataModel, FBAdPlacementDefinition, UIViewController, FBAdCommandProcessor, FBInterstitialAdNativeView, FBAdExtraHint, NSNumber, NSString;

@interface FBInterstitialNativeAdInternal : UIViewController <FBAdCommandProcessorDelegate, FBAdDisplayableViewDelegate, FBAdDisplayableViewController> {

	BOOL _nativeViewHasAppearedBefore;
	id<FBAdDisplayableViewControllerDelegate> _delegate;
	FBNativeAdDataModel* _dataModel;
	FBAdPlacementDefinition* _placementDefinition;
	UIViewController* _rootViewController;
	FBAdCommandProcessor* _commandProcessor;
	double _firstImpressionTime;
	FBInterstitialAdNativeView* _nativeView;
	id<FBAdFunnelLoggingDelegate> _funnelLoggerDelegate;
	FBAdExtraHint* _extraHint;

}

@property (nonatomic,retain) FBNativeAdDataModel * dataModel;                                        //@synthesize dataModel=_dataModel - In the implementation block
@property (nonatomic,retain) FBAdPlacementDefinition * placementDefinition;                          //@synthesize placementDefinition=_placementDefinition - In the implementation block
@property (nonatomic,retain) UIViewController * rootViewController;                                  //@synthesize rootViewController=_rootViewController - In the implementation block
@property (nonatomic,retain) FBAdCommandProcessor * commandProcessor;                                //@synthesize commandProcessor=_commandProcessor - In the implementation block
@property (assign,nonatomic) double firstImpressionTime;                                             //@synthesize firstImpressionTime=_firstImpressionTime - In the implementation block
@property (assign,nonatomic,__weak) FBInterstitialAdNativeView * nativeView;                         //@synthesize nativeView=_nativeView - In the implementation block
@property (assign,nonatomic) BOOL nativeViewHasAppearedBefore;                                       //@synthesize nativeViewHasAppearedBefore=_nativeViewHasAppearedBefore - In the implementation block
@property (assign,nonatomic,__weak) id<FBAdFunnelLoggingDelegate> funnelLoggerDelegate;              //@synthesize funnelLoggerDelegate=_funnelLoggerDelegate - In the implementation block
@property (nonatomic,retain) FBAdExtraHint * extraHint;                                              //@synthesize extraHint=_extraHint - In the implementation block
@property (nonatomic,readonly) NSNumber * cickDelayTime; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIViewController * viewControllerForPresentingModalView; 
@property (getter=isAdValid,nonatomic,readonly) BOOL adValid; 
@property (nonatomic,readonly) FBAdDataModel * adDataModel; 
@property (assign,nonatomic,__weak) id<FBAdDisplayableViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)loadAd;
-(UIViewController *)viewControllerForPresentingModalView;
-(BOOL)isAdValid;
-(BOOL)showAdFromRootViewController:(id)arg1 ;
-(FBAdDataModel *)adDataModel;
-(void)setDataModel:(FBNativeAdDataModel *)arg1 ;
-(FBAdExtraHint *)extraHint;
-(void)setExtraHint:(FBAdExtraHint *)arg1 ;
-(double)firstImpressionTime;
-(void)setFirstImpressionTime:(double)arg1 ;
-(FBAdPlacementDefinition *)placementDefinition;
-(void)setPlacementDefinition:(FBAdPlacementDefinition *)arg1 ;
-(void)viewControllerDismissed:(id)arg1 ;
-(id)commandProcessorTouchInformation:(id)arg1 ;
-(id<FBAdFunnelLoggingDelegate>)funnelLoggerDelegate;
-(void)setFunnelLoggerDelegate:(id<FBAdFunnelLoggingDelegate>)arg1 ;
-(void)adDisplayableViewDidClick:(id)arg1 withEvent:(id)arg2 withCommand:(id)arg3 skipAppStore:(BOOL)arg4 withPageNumber:(id)arg5 withPageTotal:(id)arg6 completionHandler:(/*^block*/id)arg7 ;
-(void)adDisplayableViewDidInteract:(id)arg1 withTouchData:(id)arg2 touchType:(id)arg3 withCommand:(id)arg4 skipAppStore:(BOOL)arg5 withPageNumber:(id)arg6 withPageTotal:(id)arg7 completionHandler:(/*^block*/id)arg8 ;
-(void)adDisplayableViewDidLoad:(id)arg1 ;
-(void)adDisplayableViewWantsToLogImpression:(id)arg1 withViewabilityValidator:(id)arg2 withPageNumber:(id)arg3 withPageTotal:(id)arg4 ;
-(void)adDisplayableViewDidClick:(id)arg1 withEvent:(id)arg2 withCommand:(id)arg3 skipAppStore:(BOOL)arg4 withPageNumber:(id)arg5 withPageTotal:(id)arg6 ;
-(void)adDisplayableViewDidInteract:(id)arg1 withGesture:(id)arg2 withCommand:(id)arg3 skipAppStore:(BOOL)arg4 withPageNumber:(id)arg5 withPageTotal:(id)arg6 ;
-(void)adDisplayableViewDidProgress:(id)arg1 ;
-(void)adDisplayableViewDidEnd:(id)arg1 ;
-(void)adDisplayableView:(id)arg1 didFailWithError:(id)arg2 ;
-(void)adDisplayableViewDidClose:(id)arg1 ;
-(id)adDisplayableViewRootViewController:(id)arg1 ;
-(id)initWithAdData:(id)arg1 placementDefinition:(id)arg2 extraHint:(id)arg3 ;
-(BOOL)showAdFromRootViewController:(id)arg1 animated:(BOOL)arg2 ;
-(NSNumber *)cickDelayTime;
-(void)setupCommandProcessorIfNeeded;
-(void)processCommand:(id)arg1 withExtraData:(id)arg2 skipAppStore:(BOOL)arg3 completionHandler:(/*^block*/id)arg4 ;
-(FBInterstitialAdNativeView *)nativeView;
-(void)setNativeView:(FBInterstitialAdNativeView *)arg1 ;
-(BOOL)nativeViewHasAppearedBefore;
-(void)setNativeViewHasAppearedBefore:(BOOL)arg1 ;
-(id<FBAdDisplayableViewControllerDelegate>)delegate;
-(void)setDelegate:(id<FBAdDisplayableViewControllerDelegate>)arg1 ;
-(id)logger;
-(void)setRootViewController:(UIViewController *)arg1 ;
-(UIViewController *)rootViewController;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(unsigned long long)supportedInterfaceOrientations;
-(void)viewDidAppear:(BOOL)arg1 ;
-(long long)preferredInterfaceOrientationForPresentation;
-(BOOL)prefersStatusBarHidden;
-(FBNativeAdDataModel *)dataModel;
-(void)willPresentViewController:(id)arg1 ;
-(FBAdCommandProcessor *)commandProcessor;
-(void)setCommandProcessor:(FBAdCommandProcessor *)arg1 ;
@end

