/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBInterstitialAdMediaViewDelegate <NSObject>
@optional
-(void)interstitialAdMediaViewDidHidePlayButton:(id)arg1;
-(void)interstitialAdMediaViewDidShowPlayButton:(id)arg1;
-(void)interstitialAdMediaViewDidStartVideo:(id)arg1;
-(void)interstitialAdMediaViewDidPauseVideo:(id)arg1;

@required
-(void)interstitialAdMediaViewDidLoad:(id)arg1;
-(void)interstitialAdMediaViewDidProgress:(id)arg1;
-(void)interstitialAdMediaViewDidEnd:(id)arg1;
-(void)interstitialAdMediaView:(id)arg1 didFailWithError:(id)arg2;

@end

