/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/FBAdDataModel.h>
#import <MessagesExtension/FBAdReportingData.h>
#import <MessagesExtension/FBAdCreativeURLContaining.h>

@class NSURL, FBAdImage, NSString, NSNumber, NSDictionary, NSArray, FBNativeAdViewAttributes, FBPlayableAdDataModel, FBAdToolbarConfiguration, FBAdColorInfo, FBAdAssetSetData;

@interface FBNativeAdDataModel : FBAdDataModel <FBAdReportingData, FBAdCreativeURLContaining> {

	long long _cachedType;
	BOOL _showEndCard;
	BOOL _viewJSONLoggingEnabled;
	BOOL _viewSnapshotLoggingEnabled;
	BOOL _fullyClickable;
	BOOL _audioMuted;
	BOOL _videoHasAudio;
	BOOL _isWatchAndBrowseEligible;
	BOOL _allowVideoReplay;
	BOOL _isDSL;
	BOOL _showIntroCardTransition;
	BOOL _showExitTransition;
	NSDictionary* _metadata;
	long long _placementType;
	NSURL* _destinationURL;
	NSString* _headline;
	NSString* _linkDescription;
	NSString* _advertiserName;
	NSString* _sponsoredTranslation;
	NSString* _adTranslation;
	NSString* _promotedTranslation;
	NSString* _localizedDelayClickText;
	NSString* _localizedCancelText;
	NSString* _localizedSponsoredText;
	NSString* _localizedSkipText;
	NSString* _localizedRewardInText;
	NSString* _localizedGenericRewardText;
	NSString* _localizedKeepWatchingAdText;
	NSString* _localizedBackToGameText;
	NSArray* _screenshots;
	NSNumber* _starRatingValue;
	NSNumber* _starRatingCount;
	NSString* _category;
	NSString* _title;
	NSString* _subtitle;
	NSString* _socialContext;
	NSString* _callToAction;
	FBAdImage* _icon;
	NSURL* _iconURL;
	FBAdImage* _image;
	NSURL* _imageURL;
	NSString* _body;
	NSURL* _commandURL;
	long long _snapshotDelayPostInSecond;
	double _snapshotCompressionQuality;
	FBAdImage* _adChoicesIcon;
	FBAdImage* _ctaButtonIcon;
	NSURL* _adChoicesLinkURL;
	NSString* _adChoicesText;
	NSURL* _videoURL;
	NSNumber* _videoAutoplayEnabled;
	long long _orientation;
	FBNativeAdViewAttributes* _adViewAttributes;
	NSArray* _multiProductAdContent;
	FBPlayableAdDataModel* _playableAdDataModel;
	NSString* _adCreativeType;
	NSURL* _replayIconURL;
	FBAdToolbarConfiguration* _toolbarConfiguration;
	NSNumber* _mediaAspectRatio;
	NSString* _encryptedAdID;
	NSNumber* _cappingPeriod;
	NSNumber* _xoutPeriod;
	NSNumber* _cappingCount;
	FBAdColorInfo* _colorInfo;
	FBAdAssetSetData* _assets;
	SCD_Struct_IM9 _forcedViewTime;
	SCD_Struct_IM9 _watchTimeRequiredForReward;

}

@property (assign,nonatomic) long long placementType;                                                      //@synthesize placementType=_placementType - In the implementation block
@property (assign,nonatomic) BOOL isDSL;                                                                   //@synthesize isDSL=_isDSL - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * metadata;                                               //@synthesize metadata=_metadata - In the implementation block
@property (nonatomic,copy,readonly) NSURL * destinationURL;                                                //@synthesize destinationURL=_destinationURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * headline;                                                   //@synthesize headline=_headline - In the implementation block
@property (nonatomic,copy,readonly) NSString * linkDescription;                                            //@synthesize linkDescription=_linkDescription - In the implementation block
@property (nonatomic,copy,readonly) NSString * advertiserName;                                             //@synthesize advertiserName=_advertiserName - In the implementation block
@property (nonatomic,copy,readonly) NSString * sponsoredTranslation;                                       //@synthesize sponsoredTranslation=_sponsoredTranslation - In the implementation block
@property (nonatomic,copy,readonly) NSString * adTranslation;                                              //@synthesize adTranslation=_adTranslation - In the implementation block
@property (nonatomic,copy,readonly) NSString * promotedTranslation;                                        //@synthesize promotedTranslation=_promotedTranslation - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedDelayClickText;                                    //@synthesize localizedDelayClickText=_localizedDelayClickText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedCancelText;                                        //@synthesize localizedCancelText=_localizedCancelText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedSponsoredText;                                     //@synthesize localizedSponsoredText=_localizedSponsoredText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedSkipText;                                          //@synthesize localizedSkipText=_localizedSkipText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedRewardInText;                                      //@synthesize localizedRewardInText=_localizedRewardInText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedGenericRewardText;                                 //@synthesize localizedGenericRewardText=_localizedGenericRewardText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedKeepWatchingAdText;                                //@synthesize localizedKeepWatchingAdText=_localizedKeepWatchingAdText - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedBackToGameText;                                    //@synthesize localizedBackToGameText=_localizedBackToGameText - In the implementation block
@property (nonatomic,copy,readonly) NSArray * screenshots;                                                 //@synthesize screenshots=_screenshots - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * starRatingValue;                                            //@synthesize starRatingValue=_starRatingValue - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * starRatingCount;                                            //@synthesize starRatingCount=_starRatingCount - In the implementation block
@property (nonatomic,copy,readonly) NSString * category;                                                   //@synthesize category=_category - In the implementation block
@property (nonatomic,readonly) BOOL showEndCard;                                                           //@synthesize showEndCard=_showEndCard - In the implementation block
@property (nonatomic,copy,readonly) NSString * title;                                                      //@synthesize title=_title - In the implementation block
@property (nonatomic,copy,readonly) NSString * subtitle;                                                   //@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,copy,readonly) NSString * socialContext;                                              //@synthesize socialContext=_socialContext - In the implementation block
@property (nonatomic,copy,readonly) NSString * callToAction;                                               //@synthesize callToAction=_callToAction - In the implementation block
@property (nonatomic,readonly) FBAdImage * icon;                                                           //@synthesize icon=_icon - In the implementation block
@property (nonatomic,copy,readonly) NSURL * iconURL;                                                       //@synthesize iconURL=_iconURL - In the implementation block
@property (nonatomic,readonly) FBAdImage * image;                                                          //@synthesize image=_image - In the implementation block
@property (nonatomic,copy,readonly) NSURL * imageURL;                                                      //@synthesize imageURL=_imageURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * body;                                                       //@synthesize body=_body - In the implementation block
@property (nonatomic,copy,readonly) NSURL * commandURL;                                                    //@synthesize commandURL=_commandURL - In the implementation block
@property (nonatomic,readonly) BOOL viewJSONLoggingEnabled;                                                //@synthesize viewJSONLoggingEnabled=_viewJSONLoggingEnabled - In the implementation block
@property (nonatomic,readonly) BOOL viewSnapshotLoggingEnabled;                                            //@synthesize viewSnapshotLoggingEnabled=_viewSnapshotLoggingEnabled - In the implementation block
@property (nonatomic,readonly) long long snapshotDelayPostInSecond;                                        //@synthesize snapshotDelayPostInSecond=_snapshotDelayPostInSecond - In the implementation block
@property (nonatomic,readonly) double snapshotCompressionQuality;                                          //@synthesize snapshotCompressionQuality=_snapshotCompressionQuality - In the implementation block
@property (nonatomic,readonly) FBAdImage * adChoicesIcon;                                                  //@synthesize adChoicesIcon=_adChoicesIcon - In the implementation block
@property (nonatomic,readonly) FBAdImage * ctaButtonIcon;                                                  //@synthesize ctaButtonIcon=_ctaButtonIcon - In the implementation block
@property (nonatomic,copy,readonly) NSURL * adChoicesLinkURL;                                              //@synthesize adChoicesLinkURL=_adChoicesLinkURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * adChoicesText;                                              //@synthesize adChoicesText=_adChoicesText - In the implementation block
@property (nonatomic,readonly) BOOL fullyClickable;                                                        //@synthesize fullyClickable=_fullyClickable - In the implementation block
@property (nonatomic,copy,readonly) NSURL * videoURL;                                                      //@synthesize videoURL=_videoURL - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * videoAutoplayEnabled;                                       //@synthesize videoAutoplayEnabled=_videoAutoplayEnabled - In the implementation block
@property (nonatomic,readonly) BOOL audioMuted;                                                            //@synthesize audioMuted=_audioMuted - In the implementation block
@property (nonatomic,readonly) SCD_Struct_IM9 forcedViewTime;                                              //@synthesize forcedViewTime=_forcedViewTime - In the implementation block
@property (nonatomic,readonly) long long orientation;                                                      //@synthesize orientation=_orientation - In the implementation block
@property (nonatomic,readonly) FBNativeAdViewAttributes * adViewAttributes;                                //@synthesize adViewAttributes=_adViewAttributes - In the implementation block
@property (nonatomic,copy,readonly) NSArray * multiProductAdContent;                                       //@synthesize multiProductAdContent=_multiProductAdContent - In the implementation block
@property (getter=isValid,nonatomic,readonly) BOOL valid; 
@property (nonatomic,readonly) long long type; 
@property (nonatomic,readonly) BOOL videoHasAudio;                                                         //@synthesize videoHasAudio=_videoHasAudio - In the implementation block
@property (nonatomic,readonly) FBPlayableAdDataModel * playableAdDataModel;                                //@synthesize playableAdDataModel=_playableAdDataModel - In the implementation block
@property (getter=isWatchAndBrowseEligible,nonatomic,readonly) BOOL isWatchAndBrowseEligible;              //@synthesize isWatchAndBrowseEligible=_isWatchAndBrowseEligible - In the implementation block
@property (nonatomic,copy,readonly) NSString * adCreativeType;                                             //@synthesize adCreativeType=_adCreativeType - In the implementation block
@property (nonatomic,copy,readonly) NSURL * replayIconURL;                                                 //@synthesize replayIconURL=_replayIconURL - In the implementation block
@property (nonatomic,retain) FBAdToolbarConfiguration * toolbarConfiguration;                              //@synthesize toolbarConfiguration=_toolbarConfiguration - In the implementation block
@property (getter=shouldAllowVideoReplay,nonatomic,readonly) BOOL allowVideoReplay;                        //@synthesize allowVideoReplay=_allowVideoReplay - In the implementation block
@property (nonatomic,readonly) NSNumber * mediaAspectRatio;                                                //@synthesize mediaAspectRatio=_mediaAspectRatio - In the implementation block
@property (nonatomic,copy,readonly) NSString * adViewType; 
@property (nonatomic,readonly) BOOL showIntroCardTransition;                                               //@synthesize showIntroCardTransition=_showIntroCardTransition - In the implementation block
@property (nonatomic,readonly) BOOL showExitTransition;                                                    //@synthesize showExitTransition=_showExitTransition - In the implementation block
@property (nonatomic,copy,readonly) NSString * encryptedAdID;                                              //@synthesize encryptedAdID=_encryptedAdID - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * cappingPeriod;                                              //@synthesize cappingPeriod=_cappingPeriod - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * xoutPeriod;                                                 //@synthesize xoutPeriod=_xoutPeriod - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * cappingCount;                                               //@synthesize cappingCount=_cappingCount - In the implementation block
@property (nonatomic,readonly) SCD_Struct_IM9 watchTimeRequiredForReward;                                  //@synthesize watchTimeRequiredForReward=_watchTimeRequiredForReward - In the implementation block
@property (nonatomic,readonly) FBAdColorInfo * colorInfo;                                                  //@synthesize colorInfo=_colorInfo - In the implementation block
@property (nonatomic,readonly) FBAdAssetSetData * assets;                                                  //@synthesize assets=_assets - In the implementation block
@property (nonatomic,copy,readonly) NSString * inlineClientToken; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)setPlacementType:(long long)arg1 ;
-(NSString *)socialContext;
-(NSString *)sponsoredTranslation;
-(BOOL)showEndCard;
-(SCD_Struct_IM9)forcedViewTime;
-(NSString *)adViewType;
-(NSNumber *)cappingCount;
-(NSString *)adChoicesText;
-(NSURL *)adChoicesLinkURL;
-(FBAdImage *)adChoicesIcon;
-(BOOL)showIntroCardTransition;
-(NSString *)encryptedAdID;
-(NSNumber *)xoutPeriod;
-(NSURL *)commandURL;
-(NSString *)linkDescription;
-(NSString *)adTranslation;
-(NSString *)promotedTranslation;
-(FBNativeAdViewAttributes *)adViewAttributes;
-(id)initWithMetadata:(id)arg1 placementType:(long long)arg2 ;
-(id)cacheKeysForCreatives;
-(id)processMultiProductAdMetadata:(id)arg1 ;
-(BOOL)isAppStoreIDPresent;
-(NSString *)localizedDelayClickText;
-(NSString *)localizedCancelText;
-(NSString *)localizedSponsoredText;
-(NSString *)localizedSkipText;
-(NSString *)localizedRewardInText;
-(NSString *)localizedGenericRewardText;
-(NSString *)localizedKeepWatchingAdText;
-(NSString *)localizedBackToGameText;
-(NSNumber *)starRatingValue;
-(NSNumber *)starRatingCount;
-(BOOL)viewJSONLoggingEnabled;
-(BOOL)viewSnapshotLoggingEnabled;
-(long long)snapshotDelayPostInSecond;
-(double)snapshotCompressionQuality;
-(FBAdImage *)ctaButtonIcon;
-(BOOL)fullyClickable;
-(NSNumber *)videoAutoplayEnabled;
-(NSArray *)multiProductAdContent;
-(BOOL)videoHasAudio;
-(FBPlayableAdDataModel *)playableAdDataModel;
-(BOOL)isWatchAndBrowseEligible;
-(NSURL *)replayIconURL;
-(FBAdToolbarConfiguration *)toolbarConfiguration;
-(void)setToolbarConfiguration:(FBAdToolbarConfiguration *)arg1 ;
-(BOOL)shouldAllowVideoReplay;
-(BOOL)isDSL;
-(void)setIsDSL:(BOOL)arg1 ;
-(BOOL)showExitTransition;
-(NSNumber *)cappingPeriod;
-(SCD_Struct_IM9)watchTimeRequiredForReward;
-(long long)type;
-(BOOL)isValid;
-(NSString *)category;
-(NSString *)title;
-(long long)orientation;
-(FBAdImage *)image;
-(NSDictionary *)metadata;
-(NSString *)subtitle;
-(NSURL *)destinationURL;
-(FBAdImage *)icon;
-(NSString *)body;
-(NSURL *)imageURL;
-(FBAdAssetSetData *)assets;
-(NSURL *)iconURL;
-(NSURL *)videoURL;
-(id)initWithMetadata:(id)arg1 ;
-(FBAdColorInfo *)colorInfo;
-(NSString *)headline;
-(NSArray *)screenshots;
-(NSString *)callToAction;
-(NSString *)adCreativeType;
-(long long)placementType;
-(BOOL)audioMuted;
-(NSString *)advertiserName;
-(NSNumber *)mediaAspectRatio;
@end

