/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/FBNativeAdView.h>

@class NSNumber, UILabel, FBAdTemplateHeaderView, FBAdTemplateFooterView;

@interface FBNativeAdTemplateView : FBNativeAdView {

	NSNumber* _headerSize;
	NSNumber* _mediaViewSize;
	NSNumber* _detailsSize;
	UILabel* _headerTitleLabel;
	UILabel* _headerBodyLabel;
	FBAdTemplateHeaderView* _templateHeaderView;
	FBAdTemplateFooterView* _templateFooterView;

}

@property (assign,nonatomic,__weak) UILabel * headerTitleLabel;                               //@synthesize headerTitleLabel=_headerTitleLabel - In the implementation block
@property (assign,nonatomic,__weak) UILabel * headerBodyLabel;                                //@synthesize headerBodyLabel=_headerBodyLabel - In the implementation block
@property (assign,nonatomic,__weak) FBAdTemplateHeaderView * templateHeaderView;              //@synthesize templateHeaderView=_templateHeaderView - In the implementation block
@property (assign,nonatomic,__weak) FBAdTemplateFooterView * templateFooterView;              //@synthesize templateFooterView=_templateFooterView - In the implementation block
@property (nonatomic,retain) NSNumber * headerSize;                                           //@synthesize headerSize=_headerSize - In the implementation block
@property (nonatomic,retain) NSNumber * mediaViewSize;                                        //@synthesize mediaViewSize=_mediaViewSize - In the implementation block
@property (nonatomic,retain) NSNumber * detailsSize;                                          //@synthesize detailsSize=_detailsSize - In the implementation block
+(id)defaultAttributes;
-(void)updateView:(BOOL)arg1 ;
-(UILabel *)headerBodyLabel;
-(void)setHeaderBodyLabel:(UILabel *)arg1 ;
-(void)constructCallToActionButton;
-(void)constructIconView;
-(void)constructBodyView;
-(NSNumber *)mediaViewSize;
-(NSNumber *)detailsSize;
-(void)setMediaViewSize:(NSNumber *)arg1 ;
-(void)setDetailsSize:(NSNumber *)arg1 ;
-(FBAdTemplateHeaderView *)templateHeaderView;
-(void)setTemplateHeaderView:(FBAdTemplateHeaderView *)arg1 ;
-(FBAdTemplateFooterView *)templateFooterView;
-(void)setTemplateFooterView:(FBAdTemplateFooterView *)arg1 ;
-(void)setHeaderSize:(NSNumber *)arg1 ;
-(NSNumber *)headerSize;
-(void)setHeaderTitleLabel:(UILabel *)arg1 ;
-(UILabel *)headerTitleLabel;
@end

