/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FBRewardedVideoRewardData : NSObject {

	NSString* _userID;
	NSString* _currency;

}

@property (nonatomic,copy,readonly) NSString * userID;                //@synthesize userID=_userID - In the implementation block
@property (nonatomic,copy,readonly) NSString * currency;              //@synthesize currency=_currency - In the implementation block
-(id)initWithUserID:(id)arg1 withCurrency:(id)arg2 ;
-(id)init;
-(NSString *)userID;
-(NSString *)currency;
@end

