/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKCrashHandler : NSObject
+(id)filterCrashLogs:(id)arg1 ;
+(BOOL)callstack:(id)arg1 containsPrefix:(id)arg2 ;
+(void)uninstallExceptionsHandler;
+(BOOL)isSafeToGenerateMapping;
+(void)installExceptionsHandler;
+(id)getProcessedCrashLogs;
+(void)generateMethodMapping:(id)arg1 ;
+(void)sendCrashLogs;
+(void)saveCrashLog:(id)arg1 ;
+(id)loadCrashLogs;
+(void)clearCrashReportFiles;
+(id)loadLibData:(id)arg1 ;
+(id)getCrashLogFileNames:(id)arg1 ;
+(id)loadCrashLog:(id)arg1 ;
+(id)getPathToCrashFile:(id)arg1 ;
+(id)getPathToLibDataFile:(id)arg1 ;
+(void)saveException:(id)arg1 ;
+(void)saveSignal:(int)arg1 withCallStack:(id)arg2 ;
+(id)getFBSDKVersion;
+(void)initialize;
+(void)addObserver:(id)arg1 ;
+(void)removeObserver:(id)arg1 ;
+(void)disable;
@end

