/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray, AVAudioMix;


@protocol FNFAVPlayerItem <NSObject>
@property (nonatomic,readonly) long long status; 
@property (nonatomic,copy,readonly) NSArray * loadedTimeRanges; 
@property (nonatomic,readonly) BOOL shouldApplyRotationTransform; 
@property (nonatomic,copy) AVAudioMix * audioMix; 
@required
-(void)asyncLoadAvailableQualitiesWithHandler:(/*^block*/id)arg1 onQueue:(id)arg2;
-(void)asyncLoadCurrentQualityWithHandler:(/*^block*/id)arg1 onQueue:(id)arg2;
-(void)requestTimeLoadedUpdate;
-(void)requestErrorNotificationIfNeeded;
-(BOOL)shouldApplyRotationTransform;
-(long long)status;
-(SCD_Struct_IM9*)duration;
-(id)asset;
-(NSArray *)loadedTimeRanges;
-(SCD_Struct_IM9*)currentTime;
-(void)setAudioMix:(id)arg1;
-(void)addOutput:(id)arg1;
-(id)accessLog;
-(AVAudioMix *)audioMix;
-(BOOL)isPlaybackLikelyToKeepUp;
-(BOOL)isPlaybackBufferFull;

@end

