/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSError;


@protocol FNFAVPlayer <NSObject>
@property (assign,nonatomic) float rate; 
@property (assign,getter=isMuted,nonatomic) BOOL muted; 
@property (assign,nonatomic) float volume; 
@property (assign,nonatomic) BOOL allowsExternalPlayback; 
@property (nonatomic,readonly) long long status; 
@property (nonatomic,readonly) NSError * error; 
@required
-(id)addPeriodicTimeObserverForInterval:(SCD_Struct_IM9)arg1 queue:(id)arg2 followMasterClock:(BOOL)arg3 usingBlock:(/*^block*/id)arg4;
-(NSError *)error;
-(void)pause;
-(long long)status;
-(id)currentItem;
-(void)play;
-(SCD_Struct_IM9*)currentTime;
-(float)volume;
-(void)setVolume:(float)arg1;
-(void)setRate:(float)arg1;
-(float)rate;
-(void)setMuted:(BOOL)arg1;
-(BOOL)isMuted;
-(void)removeTimeObserver:(id)arg1;
-(void)replaceCurrentItemWithPlayerItem:(id)arg1;
-(void)setAllowsExternalPlayback:(BOOL)arg1;
-(void)seekToTime:(SCD_Struct_IM9)arg1 toleranceBefore:(SCD_Struct_IM9)arg2 toleranceAfter:(SCD_Struct_IM9)arg3 completionHandler:(/*^block*/id)arg4;
-(BOOL)allowsExternalPlayback;
-(id)addPeriodicTimeObserverForInterval:(SCD_Struct_IM9)arg1 queue:(id)arg2 usingBlock:(/*^block*/id)arg3;
-(void)seekToTime:(SCD_Struct_IM9)arg1 toleranceBefore:(SCD_Struct_IM9)arg2 toleranceAfter:(SCD_Struct_IM9)arg3;
-(void)seekToTime:(SCD_Struct_IM9)arg1;
-(void)seekToTime:(SCD_Struct_IM9)arg1 completionHandler:(/*^block*/id)arg2;

@end

