/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FNFAssetForPlayer
@property (nonatomic,readonly) long long status; 
@property (nonatomic,readonly) SCD_Struct_IM9 maxBufferTime; 
@property (nonatomic,readonly) SCD_Struct_IM9 minBufferTime; 
@property (nonatomic,readonly) int pauseReason; 
@required
-(BOOL)seekToPosition:(SCD_Struct_IM9)arg1;
-(opaqueCMFormatDescriptionRef)formatDesc;
-(id)audioStreamExtraParameters;
-(id)audioChannelConfiguration;
-(BOOL)containsTrack:(long long)arg1;
-(unsigned long long)codecFormatForTrack:(long long)arg1;
-(void)addErrorToLog:(id)arg1 shouldStopPlayback:(BOOL)arg2;
-(id)representationId;
-(id)audioRepresentationId;
-(id)mpdAccessibilityDescription;
-(BOOL)mpdContainsAttributeUsingASRCaptions;
-(BOOL)trackHasMoreFrames:(long long)arg1;
-(FNFFrameMetadata*)currentFrameMetadataForTrack:(long long)arg1;
-(const char*)currentFrameDataForTrack:(long long)arg1;
-(void)advanceFrameForTrack:(long long)arg1;
-(void)updatePlaybackTime:(SCD_Struct_IM9)arg1;
-(BOOL)shouldPauseForStallingWithNextCheckCallback:(/*^block*/id)arg1 stallReason:(int)arg2;
-(BOOL)shouldRestartAfterStalling;
-(BOOL)stallingForTrack:(long long)arg1;
-(BOOL)shouldBufferVideoAsSoonAsPossible;
-(BOOL)resetAssetToBeginningIfNeeded;
-(void)playbackPauseRequested:(int)arg1;
-(SCD_Struct_IM9*)timeAfterSeek;
-(id)qualityLabel;
-(BOOL)decompressedFramebuffer;
-(BOOL)isDurationFinal;
-(double)prepareToSeekWithPosition:(SCD_Struct_IM9)arg1;
-(void)setAssetEventListener:(id)arg1;
-(void)setIsSoundMuted:(BOOL)arg1;
-(void)setUserSelectedQuality:(id)arg1;
-(void)asyncLoadAssetWithHandler:(/*^block*/id)arg1 onQueue:(id)arg2;
-(SCD_Struct_IM9)maxBufferTime;
-(SCD_Struct_IM9)minBufferTime;
-(long long)status;
-(SCD_Struct_IM9*)duration;
-(id)projection;
-(CGAffineTransform*)preferredTransform;
-(BOOL)isAudioOnly;
-(void)playbackStarted;
-(BOOL)isProtectedContent;
-(int)pauseReason;
-(AudioStreamBasicDescription*)asbd;
-(id)debugDetails;

@end

