/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FNFTimeLoadedDelegate, FNFBandwidthProvider;
#import <MessagesExtension/MessagesExtension-Structs.h>
@class NSArray;

@interface FNFBufferSizeDecider : NSObject {

	double _fetchBufferSizeInSeconds;
	double _defaultFetchBufferSizeInSeconds;
	double _fetchMultiplier;
	double _unstallMultiplier;
	double _unstallBufferSizeInSeconds;
	double _stallBufferSizeInSeconds;
	double _firstUnstallBufferSizeInSeconds;
	double _currentUnStallBufferSize;
	BOOL _dynamicUnstallBufferEnabled;
	double _unstallBufferSizeForExcellentNetwork;
	double _unstallBufferSizeForGoodNetwork;
	double _unstallBufferSizeForModerateNetwork;
	double _unstallBufferSizeForPoorNetwork;
	double _unstallBufferSizeForUnknownNetwork;
	BOOL _enableWhatsAppStreaming;
	double _furthestTimeLoadedInSeconds[2];
	id<FNFTimeLoadedDelegate> _delegate;
	NSArray* _loadedTimeRanges;
	double _firstFetchSizeInSeconds;
	id<FNFBandwidthProvider> _bandwidthProvider;
	SCD_Struct_IM9 _playbackTime;
	SCD_Struct_IM9 _timeAfterSeek;

}

@property (assign,nonatomic,__weak) id<FNFTimeLoadedDelegate> delegate;               //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy,readonly) NSArray * loadedTimeRanges;                       //@synthesize loadedTimeRanges=_loadedTimeRanges - In the implementation block
@property (assign,nonatomic) SCD_Struct_IM9 playbackTime;                             //@synthesize playbackTime=_playbackTime - In the implementation block
@property (assign,nonatomic) SCD_Struct_IM9 timeAfterSeek;                            //@synthesize timeAfterSeek=_timeAfterSeek - In the implementation block
@property (nonatomic,readonly) double firstFetchSizeInSeconds;                        //@synthesize firstFetchSizeInSeconds=_firstFetchSizeInSeconds - In the implementation block
@property (nonatomic,retain) id<FNFBandwidthProvider> bandwidthProvider;              //@synthesize bandwidthProvider=_bandwidthProvider - In the implementation block
-(SCD_Struct_IM9)timeAfterSeek;
-(void)requestTimeLoadedUpdate;
-(SCD_Struct_IM9)timeLoaded;
-(float)timeLoadedInSeconds;
-(float)timeLoadedInSecondsForTrack:(long long)arg1 ;
-(BOOL)updateTimeLoadedWithLoadedVideoTime:(SCD_Struct_IM9)arg1 videoFullyDownloaded:(BOOL)arg2 ;
-(BOOL)updateTimeLoadedWithLoadedAudioTime:(SCD_Struct_IM9)arg1 audioFullyDownloaded:(BOOL)arg2 ;
-(BOOL)updateTimeLoadedWithLoadedVideoTime:(SCD_Struct_IM9)arg1 videoFullyDownloaded:(BOOL)arg2 loadedAudioTime:(SCD_Struct_IM9)arg3 audioFullyDownloaded:(BOOL)arg4 ;
-(double)calUnstallBufferBasedOnConnection;
-(BOOL)shouldStall;
-(BOOL)shouldUnstallWithPauseReason:(int)arg1 ;
-(BOOL)shouldFetch;
-(BOOL)shouldFetchForTrack:(long long)arg1 ;
-(float)timeToLoadInSeconds;
-(void)resetPlaybackTimeAndTimeLoaded;
-(SCD_Struct_IM9)addFetchBufferToTime:(SCD_Struct_IM9)arg1 ;
-(BOOL)hasLoadedTime:(SCD_Struct_IM9)arg1 ;
-(BOOL)_updateTimeLoaded:(SCD_Struct_IM9)arg1 fullyLoaded:(BOOL)arg2 ;
-(double)currentUnstallBuffer;
-(double)currentFetchBuffer;
-(void)setTimeAfterSeek:(SCD_Struct_IM9)arg1 ;
-(double)firstFetchSizeInSeconds;
-(id<FNFBandwidthProvider>)bandwidthProvider;
-(void)setBandwidthProvider:(id<FNFBandwidthProvider>)arg1 ;
-(id)description;
-(id<FNFTimeLoadedDelegate>)delegate;
-(void)setDelegate:(id<FNFTimeLoadedDelegate>)arg1 ;
-(NSArray *)loadedTimeRanges;
-(id)initWithConfig:(SCD_Struct_FN66)arg1 ;
-(SCD_Struct_IM9)playbackTime;
-(void)setPlaybackTime:(SCD_Struct_IM9)arg1 ;
@end

