/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FNFVideoPlaybackLoggingContext, OS_dispatch_queue, FNFCoreAudioDelegate;
#import <MessagesExtension/MessagesExtension-Structs.h>
@class NSObject;

@interface FNFCoreAudioWrapper : NSObject {

	OpaqueAudioQueueRef _audioQueue;
	OpaqueAudioQueueTimelineRef _timeline;
	AudioStreamBasicDescription _asbd;
	AudioQueueLevelMeterState* _levels;
	unsigned _levelSize;
	id<FNFVideoPlaybackLoggingContext> _loggingContext;
	NSObject*<OS_dispatch_queue> _internalQueue;
	id<FNFCoreAudioDelegate> _delegate;

}
-(void)setLoggingContext:(id)arg1 ;
-(id)initWithStreamDescription:(AudioStreamBasicDescription)arg1 andDelegate:(id)arg2 andQueue:(id)arg3 ;
-(void)_handleErrorForCode:(int)arg1 andStatus:(int)arg2 ;
-(OpaqueAudioQueueRef)queueRef;
-(BOOL)setTimePitchEnabled:(BOOL)arg1 ;
-(void)stopImmediately:(unsigned char)arg1 ;
-(BOOL)startWithTimestamp:(AudioTimeStamp*)arg1 ;
-(void)setVolume:(float)arg1 withRampTime:(float)arg2 ;
-(void)_cleanupLevelMetering;
-(AudioQueueLevelMeterState*)currentLevelMeterState;
-(unsigned)levelMeterStateLength;
-(AudioQueueBuffer*)bufferWithParams:(AQBufferParameters)arg1 ;
-(BOOL)enqueueBuffer:(AudioQueueBuffer*)arg1 withStartTime:(AudioTimeStamp*)arg2 andFramesToTrim:(unsigned)arg3 outStartTime:(AudioTimeStamp*)arg4 ;
-(BOOL)primeAudioQueue;
-(void)_audioQueueIsRunningCallback:(OpaqueAudioQueueRef)arg1 ;
-(void)_audioQueueConverterErrorCallback:(OpaqueAudioQueueRef)arg1 ;
-(void)audioQueueConverterOutputCallback:(OpaqueAudioQueueRef)arg1 forBuffer:(AudioQueueBuffer*)arg2 ;
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(id)delegate;
-(void)pause;
-(void)reset;
-(id)dispatchQueue;
-(void)flush;
-(void)releaseBuffer:(AudioQueueBuffer*)arg1 ;
-(void)_setDelegate:(id)arg1 ;
-(SCD_Struct_IM9)currentTime;
-(void)setVolume:(float)arg1 ;
-(void)setRate:(float)arg1 ;
-(void)setLevelMeteringEnabled:(BOOL)arg1 ;
@end

