/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:20 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FNFDataLoader
@required
-(void)fetchFirstRequestForSeconds:(unsigned)arg1 initializationAtomSize:(unsigned long long)arg2 track:(long long)arg3;
-(void)seekForwardToOffset:(unsigned long long)arg1 forTrack:(long long)arg2;
-(void)fetchToOffset:(unsigned long long)arg1 forTrack:(long long)arg2;
-(BOOL)isFullyDownloaded:(long long)arg1;
-(void)resetWithNewDataBlockDistributor:(id)arg1;
-(unsigned long long)currentReceiveOffsetForTrack:(long long)arg1;
-(unsigned long long)currentRequestOffsetForTrack:(long long)arg1;
-(BOOL)fetchInProgressForTrack:(long long)arg1;
-(void)setDelegate:(id)arg1;
-(id)resourceLoader;
-(void)cancelRequests;

@end

