/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/IMJSONModel.h>

@class IMAdsConfigWebviewModeModel;

@interface IMAdsConfig_WebviewMode : IMJSONModel {

	IMAdsConfigWebviewModeModel* _base;
	IMAdsConfigWebviewModeModel* _interstitial;
	IMAdsConfigWebviewModeModel* _native;
	IMAdsConfigWebviewModeModel* _banner;
	IMAdsConfigWebviewModeModel* _pingStore;

}

@property (nonatomic,retain) IMAdsConfigWebviewModeModel * base;                      //@synthesize base=_base - In the implementation block
@property (nonatomic,retain) IMAdsConfigWebviewModeModel * interstitial;              //@synthesize interstitial=_interstitial - In the implementation block
@property (nonatomic,retain) IMAdsConfigWebviewModeModel * native;                    //@synthesize native=_native - In the implementation block
@property (nonatomic,retain) IMAdsConfigWebviewModeModel * banner;                    //@synthesize banner=_banner - In the implementation block
@property (nonatomic,retain) IMAdsConfigWebviewModeModel * pingStore;                 //@synthesize pingStore=_pingStore - In the implementation block
+(id)keyMapper;
-(void)setNative:(IMAdsConfigWebviewModeModel *)arg1 ;
-(IMAdsConfigWebviewModeModel *)pingStore;
-(void)setPingStore:(IMAdsConfigWebviewModeModel *)arg1 ;
-(id)init;
-(BOOL)validate:(id*)arg1 ;
-(void)setBase:(IMAdsConfigWebviewModeModel *)arg1 ;
-(IMAdsConfigWebviewModeModel *)base;
-(IMAdsConfigWebviewModeModel *)native;
-(IMAdsConfigWebviewModeModel *)banner;
-(IMAdsConfigWebviewModeModel *)interstitial;
-(void)setInterstitial:(IMAdsConfigWebviewModeModel *)arg1 ;
-(void)setBanner:(IMAdsConfigWebviewModeModel *)arg1 ;
@end

