/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMAssetActionDelegate <NSObject>
@optional
-(BOOL)imActionShouldScrollToTopForRoot:(id)arg1;
-(void)assetVisibleOnScreen:(id)arg1;
-(void)fireGenericEventUrl:(id)arg1 forAsset:(id)arg2;
-(void)asset:(id)arg1 firesTrackingEvent:(id)arg2;
-(void)imActionVideoCompletedQuartile:(long long)arg1 forVideoAssetId:(id)arg2;
-(void)imActionVideoSkipped;
-(double)imActionMinimumVisiblePercentage;
-(id)imActionGetVideoMetadataForAssetId:(id)arg1;
-(void)imActionAudioStateChanged:(BOOL)arg1;
-(BOOL)imActionShouldRequireCustomViewabilityTracker:(id)arg1;
-(id)imAssetActionRequireVideoPropertiesWithRoot:(id)arg1;
-(void)imActionMediaStartedPlaying:(id)arg1;
-(void)imActionTrackVideoViewabilityForAsset:(id)arg1;
-(void)imActionMediaFinishedPlaying:(id)arg1;
-(void)imActionRewardedActionComplete;
-(void)imActionShowVideoEndCardForAsset:(id)arg1;
-(BOOL)imActionIsCloseScheduled;
-(void)countdownTimerFireAction:(id)arg1;
-(id)imActionGetAssetWithID:(id)arg1;
-(void)asset:(id)arg1 builtNonObstuctiveViewForVideoAndWebViewability:(id)arg2;
-(void)skipActionAvailableforAsset:(id)arg1 withSkipDelayOffset:(id)arg2;
-(void)assetClicked:(id)arg1 withParams:(id)arg2;
-(void)imActionFoundSKStoreWithID:(id)arg1;
-(void)imActionFoundCompanionExtensionTrackers:(id)arg1;
-(BOOL)shouldAllowAutoRedirectionForUserClickedOnRenderView:(BOOL)arg1;
-(void)fireTelemetryEventForAutoRedirectionForCommand:(id)arg1;
-(BOOL)saveAdBlobFromWebView:(id)arg1;
-(id)fetchAdBlobForWebView;
-(void)fireShowEndCardFromWebView;
-(void)fireSkipActionFromWebView;
-(void)fireWebViewWillPresentScreen:(id)arg1;
-(void)fireWebViewDidPresentScreen:(id)arg1;
-(void)fireWebViewWillDismissScreen:(id)arg1;
-(void)fireCloseActionFromWebView;
-(void)fireWebViewDidDismissScreen:(id)arg1;
-(void)fireWebViewWillLeaveApplication;
-(void)fireWebViewDidInteractWithParams:(id)arg1;
-(id)imActionGetNotificationSender;

@required
-(id)fetchAdUnitType;

@end

