/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/IMCoreAd.h>
#import <MessagesExtension/ASBannerAdManagerDelegate.h>

@protocol IMBannerCoreAdDelegate;
@class IMBannerAdManager, NSString;

@interface IMBannerCoreAd : IMCoreAd <ASBannerAdManagerDelegate> {

	long long _transitionAnimation;
	id<IMBannerCoreAdDelegate> _delegate;
	IMBannerAdManager* _manager;
	CGSize _adSize;

}

@property (assign,nonatomic,__weak) id<IMBannerCoreAdDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) IMBannerAdManager * manager;                             //@synthesize manager=_manager - In the implementation block
@property (assign,nonatomic) long long transitionAnimation;                           //@synthesize transitionAnimation=_transitionAnimation - In the implementation block
@property (assign,nonatomic) CGSize adSize;                                           //@synthesize adSize=_adSize - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setAdSize:(CGSize)arg1 ;
-(CGSize)adSize;
-(void)reportErrorToDelegate:(id)arg1 ;
-(void)preloadAd;
-(void)loadAd;
-(void)adManager:(id)arg1 didFailWithError:(id)arg2 ;
-(void)adManagerDidLoad:(id)arg1 ;
-(void)adManagerDidPreload:(id)arg1 ;
-(void)adManager:(id)arg1 didLoadWithTransaction:(id)arg2 ;
-(void)adManager:(id)arg1 didLoadWithVirtualCurrency:(id)arg2 ;
-(void)notifyOfPreload;
-(CGSize)requestedSizeForBannerAdManager:(id)arg1 ;
-(void)bannerAdManager:(id)arg1 willShowAd:(id)arg2 ;
-(void)adManagerDidFireAdImpression:(id)arg1 ;
-(void)bannerAdManagerWasRefreshed:(id)arg1 ;
-(void)adManager:(id)arg1 didShowWithTransaction:(id)arg2 ;
-(void)adManager:(id)arg1 hasInteractionWithParams:(id)arg2 ;
-(void)adManagerAdWasSkipped:(id)arg1 ;
-(void)adManagerMediaDidComplete:(id)arg1 ;
-(void)adManagerWillLeaveApplication:(id)arg1 ;
-(void)adManagerDidReturnToApplication:(id)arg1 ;
-(void)adManager:(id)arg1 didRewardWithVirtualCurrency:(id)arg2 ;
-(id)viewControllerForBannerAdManager:(id)arg1 ;
-(id)viewForBannerAdManager:(id)arg1 ;
-(void)adManagerWillPresent:(id)arg1 ;
-(void)adManagerDidPresent:(id)arg1 ;
-(void)adManagerWillDismiss:(id)arg1 ;
-(void)adManagerDidDismiss:(id)arg1 ;
-(void)enableRefresh:(BOOL)arg1 ;
-(void)triggerRefresh;
-(long long)adStateForAdManager:(id)arg1 ;
-(void)defineOnWindow:(BOOL)arg1 ;
-(id)initWithAdSettings:(id)arg1 forFrame:(CGRect)arg2 andDelegate:(id)arg3 ;
-(void)setTransitionAnimation:(long long)arg1 ;
-(void)appGoingToBackground;
-(void)appComingToForeground;
-(void)scheduleBannerRefresh;
-(void)updateSettigsObject;
-(id)createManager;
-(void)dealloc;
-(id<IMBannerCoreAdDelegate>)delegate;
-(void)setDelegate:(id<IMBannerCoreAdDelegate>)arg1 ;
-(IMBannerAdManager *)manager;
-(void)setManager:(IMBannerAdManager *)arg1 ;
-(long long)transitionAnimation;
@end

