/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableArray, NSString;

@interface IMCompanionTrackingEvents : NSObject <NSSecureCoding> {

	NSMutableArray* _companionTrackers;
	NSString* _companionTrackerID;

}

@property (nonatomic,retain) NSMutableArray * companionTrackers;              //@synthesize companionTrackers=_companionTrackers - In the implementation block
@property (nonatomic,retain) NSString * companionTrackerID;                   //@synthesize companionTrackerID=_companionTrackerID - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSString *)companionTrackerID;
-(NSMutableArray *)companionTrackers;
-(void)setCompanionTrackerID:(NSString *)arg1 ;
-(void)setCompanionTrackers:(NSMutableArray *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
@end

