/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/IMMoatNativeViewability.h>

@interface IMMoatNativeVideoViewability : IMMoatNativeViewability {

	id _moatCustomTracker;

}

@property (nonatomic,retain) id moatCustomTracker;              //@synthesize moatCustomTracker=_moatCustomTracker - In the implementation block
-(void)sendAdEventForEventType:(unsigned long long)arg1 forPlayHead:(double)arg2 withVolume:(float)arg3 ;
-(id)initWithMoatParameters:(id)arg1 ;
-(void)switchViewabilityTo:(id)arg1 ;
-(void)attachViewabilityToVideoAssets:(id)arg1 ;
-(id)moatCustomTracker;
-(void)setMoatCustomTracker:(id)arg1 ;
-(void)dealloc;
@end

