/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/IMConfig.h>
#import <MessagesExtension/IMConfig.h>

@protocol IMComponentConfig;
@class IMRootConfig_SDKInfoModel, NSNumber, IMGDPRConfig, NSArray, NSString;

@interface IMRootConfig : IMConfig <IMConfig> {

	long long _maxRetries;
	long long _waitTime;
	long long _retryInterval;
	IMRootConfig_SDKInfoModel* _latestSdkInfo;
	NSNumber* _monetizationDisabled;
	IMGDPRConfig* _gdpr;
	NSArray*<IMComponentConfig> _components;

}

@property (nonatomic,retain) NSArray*<IMComponentConfig> components;                 //@synthesize components=_components - In the implementation block
@property (assign,nonatomic) long long maxRetries;                                   //@synthesize maxRetries=_maxRetries - In the implementation block
@property (assign,nonatomic) long long waitTime;                                     //@synthesize waitTime=_waitTime - In the implementation block
@property (assign,nonatomic) long long retryInterval;                                //@synthesize retryInterval=_retryInterval - In the implementation block
@property (nonatomic,retain) IMRootConfig_SDKInfoModel * latestSdkInfo;              //@synthesize latestSdkInfo=_latestSdkInfo - In the implementation block
@property (nonatomic,retain) NSNumber * monetizationDisabled;                        //@synthesize monetizationDisabled=_monetizationDisabled - In the implementation block
@property (nonatomic,retain) IMGDPRConfig * gdpr;                                    //@synthesize gdpr=_gdpr - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)keyMapper;
-(BOOL)updatefromDictionary:(id)arg1 ;
-(IMGDPRConfig *)gdpr;
-(void)setWaitTime:(long long)arg1 ;
-(id)getDefaultPreinitComponentConfig;
-(void)setLatestSdkInfo:(IMRootConfig_SDKInfoModel *)arg1 ;
-(void)setMonetizationDisabled:(NSNumber *)arg1 ;
-(void)setGdpr:(IMGDPRConfig *)arg1 ;
-(long long)waitTime;
-(IMRootConfig_SDKInfoModel *)latestSdkInfo;
-(NSNumber *)monetizationDisabled;
-(void)updateFromObject:(id)arg1 ;
-(id)urlForProductType:(id)arg1 ;
-(long long)expiryForProductType:(id)arg1 ;
-(id)init;
-(BOOL)isValid;
-(NSArray*<IMComponentConfig>)components;
-(BOOL)validate:(id*)arg1 ;
-(void)setComponents:(NSArray*<IMComponentConfig>)arg1 ;
-(void)setMaxRetries:(long long)arg1 ;
-(long long)maxRetries;
-(id)getType;
-(long long)retryInterval;
-(void)setRetryInterval:(long long)arg1 ;
@end

