/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/IMHealthReportingDelegate.h>

@protocol OS_dispatch_queue;
@class IMTelemetryDAO, NSMutableDictionary, IMHealthReportingManager, NSObject, NSNumber, NSString;

@interface IMTelemetryComponent : NSObject <IMHealthReportingDelegate> {

	IMTelemetryDAO* _dao;
	NSMutableDictionary* _eventCounts;
	unsigned long long _startTime;
	unsigned long long _identifier;
	IMHealthReportingManager* _dispatchEventManager;
	NSObject*<OS_dispatch_queue> _dBQueue;
	NSNumber* _randomNumber;

}

@property (nonatomic,retain) IMTelemetryDAO * dao;                                         //@synthesize dao=_dao - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * eventCounts;                            //@synthesize eventCounts=_eventCounts - In the implementation block
@property (assign,nonatomic) unsigned long long startTime;                                 //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) unsigned long long identifier;                                //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) IMHealthReportingManager * dispatchEventManager;              //@synthesize dispatchEventManager=_dispatchEventManager - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dBQueue;                         //@synthesize dBQueue=_dBQueue - In the implementation block
@property (nonatomic,retain) NSNumber * randomNumber;                                      //@synthesize randomNumber=_randomNumber - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)sendTelemetryEvent:(unsigned long long)arg1 withPayload:(id)arg2 ;
+(id)sharedComponent;
+(id)convertObjectToDictionary:(id)arg1 ;
-(void)setDao:(IMTelemetryDAO *)arg1 ;
-(IMTelemetryDAO *)dao;
-(NSObject*<OS_dispatch_queue>)dBQueue;
-(id)provideNetworkRequestObject:(id)arg1 forAdType:(id)arg2 ;
-(void)setDBQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)startDispatchManager;
-(IMHealthReportingManager *)dispatchEventManager;
-(BOOL)isTelemetryAssetReportingEnabledForEvent:(id)arg1 ;
-(void)addEventToDb:(id)arg1 ;
-(id)getNetworkTypeConfig:(id)arg1 ;
-(void)setDispatchEventManager:(IMHealthReportingManager *)arg1 ;
-(id)getPollingManager:(id)arg1 ;
-(void)setRandomNumber:(NSNumber *)arg1 ;
-(id)init;
-(unsigned long long)identifier;
-(void)stop;
-(void)start;
-(void)setIdentifier:(unsigned long long)arg1 ;
-(unsigned long long)startTime;
-(void)setStartTime:(unsigned long long)arg1 ;
-(void)processEvent:(id)arg1 ;
-(void)submitEvent:(id)arg1 ;
-(NSNumber *)randomNumber;
-(void)setEventCounts:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)eventCounts;
@end

