/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IMViewabilityConfig : NSObject {

	long long _interval;
	long long _pollingInterval;
	double _percentage;
	long long _timeout;
	long long _maxViewsAllowed;

}

@property (assign,nonatomic) long long interval;                     //@synthesize interval=_interval - In the implementation block
@property (assign,nonatomic) long long pollingInterval;              //@synthesize pollingInterval=_pollingInterval - In the implementation block
@property (assign,nonatomic) double percentage;                      //@synthesize percentage=_percentage - In the implementation block
@property (assign,nonatomic) long long timeout;                      //@synthesize timeout=_timeout - In the implementation block
@property (assign,nonatomic) long long maxViewsAllowed;              //@synthesize maxViewsAllowed=_maxViewsAllowed - In the implementation block
-(void)setMaxViewsAllowed:(long long)arg1 ;
-(long long)maxViewsAllowed;
-(id)init;
-(long long)interval;
-(void)setInterval:(long long)arg1 ;
-(long long)timeout;
-(void)setTimeout:(long long)arg1 ;
-(double)percentage;
-(BOOL)isEqualTo:(id)arg1 ;
-(long long)pollingInterval;
-(void)setPercentage:(double)arg1 ;
-(void)setPollingInterval:(long long)arg1 ;
@end

