/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/IMBaseProcessor.h>
#import <MessagesExtension/IMSafariViewControllerDelegate.h>

@class NSString;

@interface IMViewProcessor : IMBaseProcessor <IMSafariViewControllerDelegate>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)imSafariViewControllerWillDismissScreen:(id)arg1 ;
-(void)imSafariViewControllerDidDismissScreen:(id)arg1 ;
-(void)expand:(id)arg1 withScheme:(id)arg2 ;
-(void)setCloseEndCardTracker:(id)arg1 ;
-(void)openFallback:(id)arg1 withScheme:(id)arg2 ;
-(void)openExternal:(id)arg1 withScheme:(id)arg2 ;
-(BOOL)openEmbedded:(id)arg1 withScheme:(id)arg2 ;
-(void)resizeWithScheme:(id)arg1 ;
-(void)setExpandProperties:(id)arg1 withScheme:(id)arg2 ;
-(void)setResizeProperties:(id)arg1 withScheme:(id)arg2 ;
-(void)setOrientationProperties:(id)arg1 withScheme:(id)arg2 ;
-(void)closeWithScheme:(id)arg1 ;
-(void)useCustomClose:(id)arg1 ;
-(void)disableCloseRegion:(id)arg1 ;
-(void)readySuccessCallbackToRenderView;
-(void)readyFailedCallBackToRenderView;
-(void)skipwithScheme:(id)arg1 ;
-(void)hideStatusBar;
@end

