/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface IMWebToNativeCall : NSObject {

	NSString* _scheme;
	NSString* _command;
	NSDictionary* _params;

}

@property (readonly) NSString * scheme;                  //@synthesize scheme=_scheme - In the implementation block
@property (readonly) NSString * command;                 //@synthesize command=_command - In the implementation block
@property (readonly) NSDictionary * params;              //@synthesize params=_params - In the implementation block
-(id)initWithScheme:(id)arg1 command:(id)arg2 params:(id)arg3 ;
-(id)description;
-(NSString *)scheme;
-(NSDictionary *)params;
-(NSString *)command;
@end

