/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MPNativeCustomEvent.h>
#import <MessagesExtension/IMNativeDelegate.h>

@class IMNative, InMobiNativeAdAdapter, NSString;

@interface InMobiNativeCustomEvent : MPNativeCustomEvent <IMNativeDelegate> {

	IMNative* _nativeAd;
	InMobiNativeAdAdapter* _adAdapter;

}

@property (nonatomic,retain) IMNative * nativeAd;                            //@synthesize nativeAd=_nativeAd - In the implementation block
@property (nonatomic,retain) InMobiNativeAdAdapter * adAdapter;              //@synthesize adAdapter=_adAdapter - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)native:(id)arg1 didFailToLoadWithError:(id)arg2 ;
-(void)nativeDidFinishLoading:(id)arg1 ;
-(void)nativeWillPresentScreen:(id)arg1 ;
-(void)nativeDidPresentScreen:(id)arg1 ;
-(void)nativeWillDismissScreen:(id)arg1 ;
-(void)nativeDidDismissScreen:(id)arg1 ;
-(void)userWillLeaveApplicationFromNative:(id)arg1 ;
-(void)native:(id)arg1 didInteractWithParams:(id)arg2 ;
-(void)nativeAdImpressed:(id)arg1 ;
-(void)nativeDidFinishPlayingMedia:(id)arg1 ;
-(void)userDidSkipPlayingMediaFromNative:(id)arg1 ;
-(void)native:(id)arg1 adAudioStateChanged:(BOOL)arg2 ;
-(void)setNativeAd:(IMNative *)arg1 ;
-(IMNative *)nativeAd;
-(void)native:(id)arg1 rewardActionCompletedWithRewards:(id)arg2 ;
-(void)requestAdWithCustomEventInfo:(id)arg1 adMarkup:(id)arg2 ;
-(InMobiNativeAdAdapter *)adAdapter;
-(void)setAdAdapter:(InMobiNativeAdAdapter *)arg1 ;
@end

