/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MOPUBExperimentProvider : NSObject {

	BOOL _isDisplayAgentOverriddenByClient;
	long long _displayAgentType;

}

@property (assign,nonatomic) BOOL isDisplayAgentOverriddenByClient;              //@synthesize isDisplayAgentOverriddenByClient=_isDisplayAgentOverriddenByClient - In the implementation block
@property (assign,nonatomic) long long displayAgentType;                         //@synthesize displayAgentType=_displayAgentType - In the implementation block
+(id)sharedInstance;
-(void)setDisplayAgentFromAdServer:(long long)arg1 ;
-(long long)displayAgentType;
-(void)setDisplayAgentType:(long long)arg1 ;
-(BOOL)isDisplayAgentOverriddenByClient;
-(void)setIsDisplayAgentOverriddenByClient:(BOOL)arg1 ;
-(id)init;
@end

