/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, MOPUBExperimentProvider, NSString;

@interface MoPub : NSObject {

	BOOL _forceWKWebView;
	BOOL _isSdkInitialized;
	NSArray* _globalMediationSettings;
	MOPUBExperimentProvider* _experimentProvider;

}

@property (nonatomic,readonly) BOOL canCollectPersonalInfo; 
@property (nonatomic,readonly) long long currentConsentStatus; 
@property (nonatomic,readonly) long long isGDPRApplicable; 
@property (assign,nonatomic) BOOL allowLegitimateInterest; 
@property (nonatomic,readonly) BOOL isConsentDialogReady; 
@property (nonatomic,readonly) BOOL shouldShowConsentDialog; 
@property (nonatomic,copy,readonly) NSString * currentConsentIabVendorListFormat; 
@property (nonatomic,copy,readonly) NSString * currentConsentPrivacyPolicyVersion; 
@property (nonatomic,copy,readonly) NSString * currentConsentVendorListVersion; 
@property (nonatomic,copy,readonly) NSString * previouslyConsentedIabVendorListFormat; 
@property (nonatomic,copy,readonly) NSString * previouslyConsentedPrivacyPolicyVersion; 
@property (nonatomic,copy,readonly) NSString * previouslyConsentedVendorListVersion; 
@property (nonatomic,retain) NSArray * globalMediationSettings;                                      //@synthesize globalMediationSettings=_globalMediationSettings - In the implementation block
@property (assign,nonatomic) BOOL isSdkInitialized;                                                  //@synthesize isSdkInitialized=_isSdkInitialized - In the implementation block
@property (nonatomic,retain) MOPUBExperimentProvider * experimentProvider;                           //@synthesize experimentProvider=_experimentProvider - In the implementation block
@property (assign,nonatomic) BOOL locationUpdatesEnabled; 
@property (assign,nonatomic) BOOL frequencyCappingIdUsageEnabled; 
@property (assign,nonatomic) BOOL forceWKWebView;                                                    //@synthesize forceWKWebView=_forceWKWebView - In the implementation block
@property (assign,nonatomic) unsigned long long logLevel; 
+(void)sendImpressionDelegateAndNotificationFromAd:(id)arg1 adUnitID:(id)arg2 impressionData:(id)arg3 ;
+(void)sendImpressionNotificationFromAd:(id)arg1 adUnitID:(id)arg2 impressionData:(id)arg3 ;
+(id)sharedInstance;
+(void)openURL:(id)arg1 ;
+(void)openURL:(id)arg1 options:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)canCollectPersonalInfo;
-(BOOL)isSdkInitialized;
-(void)setExperimentProvider:(MOPUBExperimentProvider *)arg1 ;
-(MOPUBExperimentProvider *)experimentProvider;
-(void)disableViewability:(long long)arg1 ;
-(BOOL)frequencyCappingIdUsageEnabled;
-(void)setFrequencyCappingIdUsageEnabled:(BOOL)arg1 ;
-(long long)isGDPRApplicable;
-(void)showConsentDialogFromViewController:(id)arg1 didShow:(/*^block*/id)arg2 didDismiss:(/*^block*/id)arg3 ;
-(void)grantConsent;
-(void)revokeConsent;
-(void)loadConsentDialogWithCompletion:(/*^block*/id)arg1 ;
-(BOOL)allowLegitimateInterest;
-(void)setAllowLegitimateInterest:(BOOL)arg1 ;
-(NSArray *)globalMediationSettings;
-(void)setGlobalMediationSettings:(NSArray *)arg1 ;
-(id)globalMediationSettingsForClass:(Class)arg1 ;
-(long long)currentConsentStatus;
-(void)initializeSdkWithConfiguration:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)commonInitWithExperimentProvider:(id)arg1 ;
-(void)handlePersonalData;
-(void)setSdkWithConfiguration:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)setIsSdkInitialized:(BOOL)arg1 ;
-(void)setEngineInformation:(id)arg1 ;
-(void)setClickthroughDisplayAgentType:(long long)arg1 ;
-(BOOL)forceWKWebView;
-(void)setForceWKWebView:(BOOL)arg1 ;
-(id)adapterConfigurationNamed:(id)arg1 ;
-(id)availableAdapterClassNames;
-(void)clearCachedNetworks;
-(BOOL)shouldShowConsentDialog;
-(void)forceGDPRApplicable;
-(NSString *)currentConsentIabVendorListFormat;
-(NSString *)currentConsentPrivacyPolicyVersion;
-(NSString *)currentConsentVendorListVersion;
-(NSString *)previouslyConsentedIabVendorListFormat;
-(NSString *)previouslyConsentedPrivacyPolicyVersion;
-(NSString *)previouslyConsentedVendorListVersion;
-(void)showConsentDialogFromViewController:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)isConsentDialogReady;
-(id)currentConsentPrivacyPolicyUrl;
-(id)currentConsentPrivacyPolicyUrlWithISOLanguageCode:(id)arg1 ;
-(id)currentConsentVendorListUrl;
-(id)currentConsentVendorListUrlWithISOLanguageCode:(id)arg1 ;
-(id)init;
-(id)bundleIdentifier;
-(id)version;
-(unsigned long long)logLevel;
-(void)setLogLevel:(unsigned long long)arg1 ;
-(void)setLocationUpdatesEnabled:(BOOL)arg1 ;
-(BOOL)locationUpdatesEnabled;
@end

