/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MPBaseNativeAdRenderer.h>
#import <MessagesExtension/MPNativeAdRenderer.h>
#import <MessagesExtension/MOPUBPlayerViewControllerDelegate.h>
#import <MessagesExtension/MOPUBFullscreenPlayerViewControllerDelegate.h>
#import <MessagesExtension/MPNativeAdRendererImageHandlerDelegate.h>

@protocol MPNativeAdAdapter;
@class MOPUBNativeVideoAdAdapter, MPNativeAdRendererImageHandler, MOPUBPlayerViewController, MPTimer, MPVideoConfig, MPVASTTracking, MOPUBNativeVideoAdConfigValues, NSString;

@interface MOPUBNativeVideoAdRenderer : MPBaseNativeAdRenderer <MPNativeAdRenderer, MOPUBPlayerViewControllerDelegate, MOPUBFullscreenPlayerViewControllerDelegate, MPNativeAdRendererImageHandlerDelegate> {

	BOOL _adViewInViewHierarchy;
	BOOL _trackingImpressionFired;
	/*^block*/id _viewSizeHandler;
	MOPUBNativeVideoAdAdapter*<MPNativeAdAdapter> _adapter;
	MPNativeAdRendererImageHandler* _rendererImageHandler;
	MOPUBPlayerViewController* _videoController;
	MPTimer* _autoPlayTimer;
	MPVideoConfig* _videoConfig;
	MPVASTTracking* _vastTracking;
	MOPUBNativeVideoAdConfigValues* _nativeVideoAdConfig;

}

@property (nonatomic,retain) MOPUBNativeVideoAdAdapter*<MPNativeAdAdapter> adapter;              //@synthesize adapter=_adapter - In the implementation block
@property (assign,nonatomic) BOOL adViewInViewHierarchy;                                         //@synthesize adViewInViewHierarchy=_adViewInViewHierarchy - In the implementation block
@property (nonatomic,retain) MPNativeAdRendererImageHandler * rendererImageHandler;              //@synthesize rendererImageHandler=_rendererImageHandler - In the implementation block
@property (assign,nonatomic,__weak) MOPUBPlayerViewController * videoController;                 //@synthesize videoController=_videoController - In the implementation block
@property (nonatomic,retain) MPTimer * autoPlayTimer;                                            //@synthesize autoPlayTimer=_autoPlayTimer - In the implementation block
@property (nonatomic,retain) MPVideoConfig * videoConfig;                                        //@synthesize videoConfig=_videoConfig - In the implementation block
@property (nonatomic,retain) MPVASTTracking * vastTracking;                                      //@synthesize vastTracking=_vastTracking - In the implementation block
@property (nonatomic,retain) MOPUBNativeVideoAdConfigValues * nativeVideoAdConfig;               //@synthesize nativeVideoAdConfig=_nativeVideoAdConfig - In the implementation block
@property (assign,nonatomic) BOOL trackingImpressionFired;                                       //@synthesize trackingImpressionFired=_trackingImpressionFired - In the implementation block
@property (nonatomic,readonly) id viewSizeHandler;                                               //@synthesize viewSizeHandler=_viewSizeHandler - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)rendererConfigurationWithRendererSettings:(id)arg1 ;
-(id)viewSizeHandler;
-(void)setVideoConfig:(MPVideoConfig *)arg1 ;
-(void)setVastTracking:(MPVASTTracking *)arg1 ;
-(MPVASTTracking *)vastTracking;
-(MPVideoConfig *)videoConfig;
-(BOOL)nativeAdViewInViewHierarchy;
-(void)ctaTapped:(id)arg1 ;
-(void)playerDidProgressToTime:(double)arg1 ;
-(void)fullscreenPlayerWillLeaveApplication:(id)arg1 ;
-(void)willEnterFullscreen:(id)arg1 ;
-(MOPUBNativeVideoAdConfigValues *)nativeVideoAdConfig;
-(id)initWithRendererSettings:(id)arg1 ;
-(void)onPrivacyIconTapped;
-(BOOL)hasIconView;
-(BOOL)shouldLoadMediaView;
-(void)setAdViewInViewHierarchy:(BOOL)arg1 ;
-(MPNativeAdRendererImageHandler *)rendererImageHandler;
-(BOOL)adViewInViewHierarchy;
-(id)retrieveViewWithAdapter:(id)arg1 error:(id*)arg2 ;
-(void)adViewWillMoveToSuperview:(id)arg1 ;
-(void)nativeAdTapped;
-(void)setRendererImageHandler:(MPNativeAdRendererImageHandler *)arg1 ;
-(void)initAdView;
-(void)setupVideoView;
-(void)enterFullscreen:(id)arg1 ;
-(BOOL)trackingImpressionFired;
-(void)setTrackingImpressionFired:(BOOL)arg1 ;
-(void)setNativeVideoAdConfig:(MOPUBNativeVideoAdConfigValues *)arg1 ;
-(MPTimer *)autoPlayTimer;
-(void)setAutoPlayTimer:(MPTimer *)arg1 ;
-(void)dealloc;
-(MOPUBNativeVideoAdAdapter*<MPNativeAdAdapter>)adapter;
-(void)setAdapter:(MOPUBNativeVideoAdAdapter*<MPNativeAdAdapter>)arg1 ;
-(MOPUBPlayerViewController *)videoController;
-(void)setVideoController:(MOPUBPlayerViewController *)arg1 ;
-(void)tick:(id)arg1 ;
@end

