/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ShareSheet/UIActivityItemProvider.h>

@class NSString;

@interface MPActivityItemProviderWithSubject : UIActivityItemProvider {

	NSString* _subject;
	NSString* _body;

}

@property (nonatomic,readonly) NSString * subject;              //@synthesize subject=_subject - In the implementation block
@property (nonatomic,readonly) NSString * body;                 //@synthesize body=_body - In the implementation block
-(id)initWithSubject:(id)arg1 body:(id)arg2 ;
-(id)item;
-(NSString *)subject;
-(id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2 ;
-(NSString *)body;
@end

