/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MPAdServerCommunicatorDelegate.h>
#import <MessagesExtension/MPBannerAdapterDelegate.h>

@protocol MPBannerAdManagerDelegate;
@class MPAdServerCommunicator, MPBaseBannerAdapter, UIView, MPAdConfiguration, MPAdTargeting, NSMutableArray, MPTimer, NSURL, MPStopwatch, NSString;

@interface MPBannerAdManager : NSObject <MPAdServerCommunicatorDelegate, MPBannerAdapterDelegate> {

	BOOL _adActionInProgress;
	BOOL _automaticallyRefreshesContents;
	BOOL _hasRequestedAtLeastOneAd;
	id<MPBannerAdManagerDelegate> _delegate;
	MPAdServerCommunicator* _communicator;
	MPBaseBannerAdapter* _onscreenAdapter;
	MPBaseBannerAdapter* _requestingAdapter;
	UIView* _requestingAdapterAdContentView;
	MPAdConfiguration* _requestingConfiguration;
	MPAdTargeting* _targeting;
	NSMutableArray* _remainingConfigurations;
	MPTimer* _refreshTimer;
	NSURL* _mostRecentlyLoadedURL;
	long long _currentOrientation;
	MPStopwatch* _loadStopwatch;

}

@property (nonatomic,retain) MPAdServerCommunicator * communicator;                      //@synthesize communicator=_communicator - In the implementation block
@property (nonatomic,retain) MPBaseBannerAdapter * onscreenAdapter;                      //@synthesize onscreenAdapter=_onscreenAdapter - In the implementation block
@property (nonatomic,retain) MPBaseBannerAdapter * requestingAdapter;                    //@synthesize requestingAdapter=_requestingAdapter - In the implementation block
@property (nonatomic,retain) UIView * requestingAdapterAdContentView;                    //@synthesize requestingAdapterAdContentView=_requestingAdapterAdContentView - In the implementation block
@property (nonatomic,retain) MPAdConfiguration * requestingConfiguration;                //@synthesize requestingConfiguration=_requestingConfiguration - In the implementation block
@property (nonatomic,retain) MPAdTargeting * targeting;                                  //@synthesize targeting=_targeting - In the implementation block
@property (nonatomic,retain) NSMutableArray * remainingConfigurations;                   //@synthesize remainingConfigurations=_remainingConfigurations - In the implementation block
@property (nonatomic,retain) MPTimer * refreshTimer;                                     //@synthesize refreshTimer=_refreshTimer - In the implementation block
@property (nonatomic,retain) NSURL * mostRecentlyLoadedURL;                              //@synthesize mostRecentlyLoadedURL=_mostRecentlyLoadedURL - In the implementation block
@property (assign,nonatomic) BOOL adActionInProgress;                                    //@synthesize adActionInProgress=_adActionInProgress - In the implementation block
@property (assign,nonatomic) BOOL automaticallyRefreshesContents;                        //@synthesize automaticallyRefreshesContents=_automaticallyRefreshesContents - In the implementation block
@property (assign,nonatomic) BOOL hasRequestedAtLeastOneAd;                              //@synthesize hasRequestedAtLeastOneAd=_hasRequestedAtLeastOneAd - In the implementation block
@property (assign,nonatomic) long long currentOrientation;                               //@synthesize currentOrientation=_currentOrientation - In the implementation block
@property (nonatomic,retain) MPStopwatch * loadStopwatch;                                //@synthesize loadStopwatch=_loadStopwatch - In the implementation block
@property (assign,nonatomic,__weak) id<MPBannerAdManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) BOOL isMraidAd; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)refreshTimerDidFire;
-(id)viewControllerForPresentingModalView;
-(id)adUnitId;
-(void)adapter:(id)arg1 didFailToLoadAdWithError:(id)arg2 ;
-(BOOL)isMraidAd;
-(void)loadAdWithTargeting:(id)arg1 ;
-(void)forceRefreshAd;
-(void)stopAutomaticallyRefreshingContents;
-(void)startAutomaticallyRefreshingContents;
-(int)allowedNativeAdsOrientation;
-(id)bannerDelegate;
-(void)communicatorDidFailWithError:(id)arg1 ;
-(BOOL)isFullscreenAd;
-(void)communicatorDidReceiveAdConfigurations:(id)arg1 ;
-(MPAdTargeting *)targeting;
-(void)setTargeting:(MPAdTargeting *)arg1 ;
-(void)setAutomaticallyRefreshesContents:(BOOL)arg1 ;
-(MPBaseBannerAdapter *)onscreenAdapter;
-(MPBaseBannerAdapter *)requestingAdapter;
-(BOOL)hasRequestedAtLeastOneAd;
-(void)setHasRequestedAtLeastOneAd:(BOOL)arg1 ;
-(void)loadAdWithURL:(id)arg1 ;
-(BOOL)automaticallyRefreshesContents;
-(void)pauseRefreshTimer;
-(void)scheduleRefreshTimer;
-(void)setRequestingConfiguration:(MPAdConfiguration *)arg1 ;
-(void)setRequestingAdapter:(MPBaseBannerAdapter *)arg1 ;
-(void)setRequestingAdapterAdContentView:(UIView *)arg1 ;
-(void)setMostRecentlyLoadedURL:(NSURL *)arg1 ;
-(MPAdConfiguration *)requestingConfiguration;
-(void)didFailToLoadAdapterWithError:(id)arg1 ;
-(MPStopwatch *)loadStopwatch;
-(void)setRemainingConfigurations:(NSMutableArray *)arg1 ;
-(NSMutableArray *)remainingConfigurations;
-(void)fetchAdWithConfiguration:(id)arg1 ;
-(UIView *)requestingAdapterAdContentView;
-(BOOL)adActionInProgress;
-(BOOL)requestingAdapterIsReadyToBePresented;
-(void)setOnscreenAdapter:(MPBaseBannerAdapter *)arg1 ;
-(void)presentRequestingAdapter;
-(NSURL *)mostRecentlyLoadedURL;
-(void)setAdActionInProgress:(BOOL)arg1 ;
-(void)resumeRefreshTimer;
-(void)adapter:(id)arg1 didFinishLoadingAd:(id)arg2 ;
-(void)userActionWillBeginForAdapter:(id)arg1 ;
-(void)userActionDidFinishForAdapter:(id)arg1 ;
-(void)userWillLeaveApplicationFromAdapter:(id)arg1 ;
-(void)adapterDidTrackImpressionForAd:(id)arg1 ;
-(void)adWillExpandForAdapter:(id)arg1 ;
-(void)adDidCollapseForAdapter:(id)arg1 ;
-(void)setLoadStopwatch:(MPStopwatch *)arg1 ;
-(void)dealloc;
-(id<MPBannerAdManagerDelegate>)delegate;
-(void)setDelegate:(id<MPBannerAdManagerDelegate>)arg1 ;
-(id)location;
-(id)initWithDelegate:(id)arg1 ;
-(void)rotateToOrientation:(long long)arg1 ;
-(long long)currentOrientation;
-(BOOL)loading;
-(void)applicationWillEnterForeground;
-(void)applicationDidEnterBackground;
-(id)banner;
-(void)setCurrentOrientation:(long long)arg1 ;
-(MPTimer *)refreshTimer;
-(MPAdServerCommunicator *)communicator;
-(void)setRefreshTimer:(MPTimer *)arg1 ;
-(void)setCommunicator:(MPAdServerCommunicator *)arg1 ;
@end

