/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/MPBaseBannerAdapter.h>
#import <MessagesExtension/MPAdImpressionTimerDelegate.h>
#import <MessagesExtension/MPPrivateBannerCustomEventDelegate.h>

@class MPBannerCustomEvent, MPAdConfiguration, MPAdImpressionTimer, UIView, NSString;

@interface MPBannerCustomEventAdapter : MPBaseBannerAdapter <MPAdImpressionTimerDelegate, MPPrivateBannerCustomEventDelegate> {

	BOOL _hasTrackedImpression;
	BOOL _hasTrackedClick;
	MPBannerCustomEvent* _bannerCustomEvent;
	MPAdConfiguration* _configuration;
	MPAdImpressionTimer* _impressionTimer;
	UIView* _adView;

}

@property (nonatomic,retain) MPBannerCustomEvent * bannerCustomEvent;              //@synthesize bannerCustomEvent=_bannerCustomEvent - In the implementation block
@property (nonatomic,retain) MPAdConfiguration * configuration;                    //@synthesize configuration=_configuration - In the implementation block
@property (assign,nonatomic) BOOL hasTrackedImpression;                            //@synthesize hasTrackedImpression=_hasTrackedImpression - In the implementation block
@property (assign,nonatomic) BOOL hasTrackedClick;                                 //@synthesize hasTrackedClick=_hasTrackedClick - In the implementation block
@property (nonatomic,retain) MPAdImpressionTimer * impressionTimer;                //@synthesize impressionTimer=_impressionTimer - In the implementation block
@property (nonatomic,retain) UIView * adView;                                      //@synthesize adView=_adView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)trackImpression;
-(void)trackClick;
-(id)viewControllerForPresentingModalView;
-(id)adUnitId;
-(void)getAdWithConfiguration:(id)arg1 targeting:(id)arg2 containerSize:(CGSize)arg3 ;
-(void)didDisplayAd;
-(id)bannerDelegate;
-(void)setImpressionTimer:(MPAdImpressionTimer *)arg1 ;
-(MPAdImpressionTimer *)impressionTimer;
-(void)adViewWillLogImpression:(id)arg1 ;
-(void)bannerCustomEvent:(id)arg1 didFailToLoadAdWithError:(id)arg2 ;
-(void)bannerCustomEvent:(id)arg1 didLoadAd:(id)arg2 ;
-(void)bannerCustomEventWillLeaveApplication:(id)arg1 ;
-(void)bannerCustomEventWillBeginAction:(id)arg1 ;
-(void)bannerCustomEventDidFinishAction:(id)arg1 ;
-(id)initWithConfiguration:(id)arg1 delegate:(id)arg2 ;
-(MPBannerCustomEvent *)bannerCustomEvent;
-(void)setBannerCustomEvent:(MPBannerCustomEvent *)arg1 ;
-(void)startViewableTrackingTimer;
-(BOOL)hasTrackedClick;
-(void)setHasTrackedClick:(BOOL)arg1 ;
-(void)bannerCustomEventWillExpandAd:(id)arg1 ;
-(void)bannerCustomEventDidCollapseAd:(id)arg1 ;
-(BOOL)hasTrackedImpression;
-(void)setHasTrackedImpression:(BOOL)arg1 ;
-(id)location;
-(void)setConfiguration:(MPAdConfiguration *)arg1 ;
-(MPAdConfiguration *)configuration;
-(void)rotateToOrientation:(long long)arg1 ;
-(void)unregisterDelegate;
-(void)setAdView:(UIView *)arg1 ;
-(UIView *)adView;
@end

