/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MPInterstitialAdManagerDelegate.h>
#import <MessagesExtension/MPMoPubAd.h>

@protocol MPInterstitialAdControllerDelegate;
@class NSString, CLLocation, NSDictionary, MPInterstitialAdManager;

@interface MPInterstitialAdController : NSObject <MPInterstitialAdManagerDelegate, MPMoPubAd> {

	id<MPInterstitialAdControllerDelegate> _delegate;
	NSString* _adUnitId;
	NSString* _keywords;
	NSString* _userDataKeywords;
	CLLocation* _location;
	NSDictionary* _localExtras;
	MPInterstitialAdManager* _manager;

}

@property (nonatomic,retain) MPInterstitialAdManager * manager;                                   //@synthesize manager=_manager - In the implementation block
@property (assign,nonatomic,__weak) id<MPInterstitialAdControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * adUnitId;                                                   //@synthesize adUnitId=_adUnitId - In the implementation block
@property (nonatomic,copy) NSString * keywords;                                                   //@synthesize keywords=_keywords - In the implementation block
@property (nonatomic,copy) NSString * userDataKeywords;                                           //@synthesize userDataKeywords=_userDataKeywords - In the implementation block
@property (nonatomic,copy) CLLocation * location;                                                 //@synthesize location=_location - In the implementation block
@property (nonatomic,copy) NSDictionary * localExtras;                                            //@synthesize localExtras=_localExtras - In the implementation block
@property (nonatomic,readonly) BOOL ready; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInterstitials;
+(id)interstitialAdControllerForAdUnitId:(id)arg1 ;
+(id)sharedInterstitialAdControllers;
+(void)removeSharedInterstitialAdController:(id)arg1 ;
-(void)loadAd;
-(NSDictionary *)localExtras;
-(void)setLocalExtras:(NSDictionary *)arg1 ;
-(NSString *)adUnitId;
-(void)setAdUnitId:(NSString *)arg1 ;
-(id)initWithAdUnitId:(id)arg1 ;
-(NSString *)userDataKeywords;
-(void)setUserDataKeywords:(NSString *)arg1 ;
-(id)interstitialAdController;
-(id)interstitialDelegate;
-(void)managerDidLoadInterstitial:(id)arg1 ;
-(void)manager:(id)arg1 didFailToLoadInterstitialWithError:(id)arg2 ;
-(void)managerWillPresentInterstitial:(id)arg1 ;
-(void)managerDidPresentInterstitial:(id)arg1 ;
-(void)managerWillDismissInterstitial:(id)arg1 ;
-(void)managerDidDismissInterstitial:(id)arg1 ;
-(void)managerDidExpireInterstitial:(id)arg1 ;
-(void)interstitialAdManager:(id)arg1 didReceiveImpressionEventWithImpressionData:(id)arg2 ;
-(void)managerDidReceiveTapEventFromInterstitial:(id)arg1 ;
-(void)dealloc;
-(id<MPInterstitialAdControllerDelegate>)delegate;
-(void)setDelegate:(id<MPInterstitialAdControllerDelegate>)arg1 ;
-(NSString *)keywords;
-(void)setKeywords:(NSString *)arg1 ;
-(MPInterstitialAdManager *)manager;
-(CLLocation *)location;
-(BOOL)ready;
-(void)setManager:(MPInterstitialAdManager *)arg1 ;
-(void)setLocation:(CLLocation *)arg1 ;
-(void)showFromViewController:(id)arg1 ;
@end

