/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/MPBannerCustomEvent.h>
#import <MessagesExtension/MRControllerDelegate.h>

@protocol MPPrivateBannerCustomEventDelegate;
@class MRController, NSString;

@interface MPMRAIDBannerCustomEvent : MPBannerCustomEvent <MRControllerDelegate> {

	id<MPPrivateBannerCustomEventDelegate> delegate;
	MRController* _mraidController;

}

@property (nonatomic,retain) MRController * mraidController;                                      //@synthesize mraidController=_mraidController - In the implementation block
@property (assign,nonatomic,__weak) id<MPPrivateBannerCustomEventDelegate> delegate; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)viewControllerForPresentingModalView;
-(id)adUnitId;
-(MRController *)mraidController;
-(void)setMraidController:(MRController *)arg1 ;
-(void)appShouldSuspendForAd:(id)arg1 ;
-(void)appShouldResumeFromAd:(id)arg1 ;
-(void)adDidLoad:(id)arg1 ;
-(void)adDidFailToLoad:(id)arg1 ;
-(void)adDidReceiveClickthrough:(id)arg1 ;
-(void)adWillExpand:(id)arg1 ;
-(void)adDidCollapse:(id)arg1 ;
-(void)startViewabilityTracker;
-(void)requestAdWithSize:(CGSize)arg1 customEventInfo:(id)arg2 adMarkup:(id)arg3 ;
-(void)trackImpressionsIncludedInMarkup;
-(id<MPPrivateBannerCustomEventDelegate>)delegate;
-(void)setDelegate:(id<MPPrivateBannerCustomEventDelegate>)arg1 ;
-(void)closeButtonPressed;
@end

