/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MPRewardedVideoConnectionDelegate;
@class NSURLSessionTask, NSURL;

@interface MPRewardedVideoConnection : NSObject {

	NSURLSessionTask* _task;
	NSURL* _url;
	unsigned long long _retryCount;
	double _accumulatedRetryInterval;
	id<MPRewardedVideoConnectionDelegate> _delegate;

}

@property (nonatomic,retain) NSURLSessionTask * task;                                            //@synthesize task=_task - In the implementation block
@property (nonatomic,retain) NSURL * url;                                                        //@synthesize url=_url - In the implementation block
@property (assign,nonatomic) unsigned long long retryCount;                                      //@synthesize retryCount=_retryCount - In the implementation block
@property (assign,nonatomic) double accumulatedRetryInterval;                                    //@synthesize accumulatedRetryInterval=_accumulatedRetryInterval - In the implementation block
@property (assign,nonatomic,__weak) id<MPRewardedVideoConnectionDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)retryRewardedVideoCompletionRequest;
-(double)backoffTime:(unsigned long long)arg1 ;
-(double)accumulatedRetryInterval;
-(void)setAccumulatedRetryInterval:(double)arg1 ;
-(void)sendRewardedVideoCompletionRequest;
-(id)initWithUrl:(id)arg1 delegate:(id)arg2 ;
-(id<MPRewardedVideoConnectionDelegate>)delegate;
-(void)setDelegate:(id<MPRewardedVideoConnectionDelegate>)arg1 ;
-(NSURL *)url;
-(void)setUrl:(NSURL *)arg1 ;
-(NSURLSessionTask *)task;
-(void)setTask:(NSURLSessionTask *)arg1 ;
-(unsigned long long)retryCount;
-(void)setRetryCount:(unsigned long long)arg1 ;
@end

