/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessagesExtension/MessagesExtension-Structs.h>
@interface MPUBMoatViewableState : NSObject {

	BOOL _isAttached;
	BOOL _isFocused;
	BOOL _isHidden;
	float _opacity;
	float _coveredPercent;
	CGRect _screenRect;
	CGRect _viewRect;
	CGRect _visibleRect;

}

@property (assign) BOOL isAttached;                   //@synthesize isAttached=_isAttached - In the implementation block
@property (assign) BOOL isFocused;                    //@synthesize isFocused=_isFocused - In the implementation block
@property (assign) BOOL isHidden;                     //@synthesize isHidden=_isHidden - In the implementation block
@property (assign) float opacity;                     //@synthesize opacity=_opacity - In the implementation block
@property (assign) float coveredPercent;              //@synthesize coveredPercent=_coveredPercent - In the implementation block
@property (assign) CGRect screenRect;                 //@synthesize screenRect=_screenRect - In the implementation block
@property (assign) CGRect viewRect;                   //@synthesize viewRect=_viewRect - In the implementation block
@property (assign) CGRect visibleRect;                //@synthesize visibleRect=_visibleRect - In the implementation block
+(id)getRectAsJsonDict:(CGRect)arg1 ;
-(id)toJSON;
-(CGRect)screenRect;
-(float)coveredPercent;
-(float)getVisiblePercent;
-(void)setScreenRect:(CGRect)arg1 ;
-(void)setViewRect:(CGRect)arg1 ;
-(void)setIsAttached:(BOOL)arg1 ;
-(void)setCoveredPercent:(float)arg1 ;
-(BOOL)isHidden;
-(float)opacity;
-(void)setOpacity:(float)arg1 ;
-(void)setIsHidden:(BOOL)arg1 ;
-(CGRect)visibleRect;
-(BOOL)isFocused;
-(BOOL)isAttached;
-(void)setVisibleRect:(CGRect)arg1 ;
-(id)toDict;
-(CGRect)viewRect;
-(void)setIsFocused:(BOOL)arg1 ;
@end

