/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURL, NSURLSessionTask;

@interface MPURLResolver : NSObject {

	NSURL* _originalURL;
	NSURL* _currentURL;
	NSURLSessionTask* _task;
	/*^block*/id _completion;

}

@property (nonatomic,retain) NSURL * originalURL;                  //@synthesize originalURL=_originalURL - In the implementation block
@property (nonatomic,retain) NSURL * currentURL;                   //@synthesize currentURL=_currentURL - In the implementation block
@property (nonatomic,retain) NSURLSessionTask * task;              //@synthesize task=_task - In the implementation block
@property (nonatomic,copy) id completion;                          //@synthesize completion=_completion - In the implementation block
+(id)resolverWithURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)actionInfoFromURL:(id)arg1 error:(id*)arg2 ;
-(void)safeInvokeAndNilCompletionBlock:(id)arg1 error:(id)arg2 ;
-(BOOL)shouldOpenWithInAppWebBrowser;
-(id)httpTaskWithRequest:(id)arg1 ;
-(unsigned long long)stringEncodingFromContentType:(id)arg1 ;
-(id)appStoreProductParametersForURL:(id)arg1 ;
-(BOOL)URLHasDeeplinkPlusScheme:(id)arg1 ;
-(id)safariURLForURL:(id)arg1 ;
-(BOOL)URLShouldOpenInApplication:(id)arg1 ;
-(BOOL)URLIsHTTPOrHTTPS:(id)arg1 ;
-(BOOL)URLPointsToAMap:(id)arg1 ;
-(BOOL)URLIsAppleScheme:(id)arg1 ;
-(void)cancel;
-(void)start;
-(NSURL *)originalURL;
-(void)setCompletion:(id)arg1 ;
-(id)completion;
-(NSURLSessionTask *)task;
-(void)setTask:(NSURLSessionTask *)arg1 ;
-(void)setOriginalURL:(NSURL *)arg1 ;
-(id)initWithURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSURL *)currentURL;
-(void)setCurrentURL:(NSURL *)arg1 ;
@end

