/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MPVASTModel.h>

@class NSArray, NSString;

@interface MPVASTResponse : MPVASTModel {

	NSArray* _ads;
	NSArray* _errorURLs;
	NSString* _version;

}

@property (nonatomic,retain) NSArray * ads;                    //@synthesize ads=_ads - In the implementation block
@property (nonatomic,retain) NSArray * errorURLs;              //@synthesize errorURLs=_errorURLs - In the implementation block
@property (nonatomic,copy) NSString * version;                 //@synthesize version=_version - In the implementation block
+(id)modelMap;
-(void)setAds:(NSArray *)arg1 ;
-(NSArray *)errorURLs;
-(void)setErrorURLs:(NSArray *)arg1 ;
-(NSString *)version;
-(void)setVersion:(NSString *)arg1 ;
-(NSArray *)ads;
@end

