/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface MPViewabilityTracker : NSObject {

	NSDictionary* _trackers;

}

@property (nonatomic,retain) NSDictionary * trackers;              //@synthesize trackers=_trackers - In the implementation block
+(void)disableViewability:(long long)arg1 ;
+(long long)enabledViewabilityVendors;
+(void)initialize;
-(void)registerFriendlyObstructionView:(id)arg1 ;
-(void)setTrackers:(NSDictionary *)arg1 ;
-(id)initWithWebView:(id)arg1 isVideo:(BOOL)arg2 startTrackingImmediately:(BOOL)arg3 ;
-(id)initWithNativeVideoView:(id)arg1 startTrackingImmediately:(BOOL)arg2 ;
-(void)trackNativeVideoEvent:(id)arg1 eventInfo:(id)arg2 ;
-(void)onDisableViewabilityTrackingForNotification:(id)arg1 ;
-(id)initializeTrackerWithClassName:(id)arg1 forViewabilityOption:(long long)arg2 withAdView:(id)arg3 isVideo:(BOOL)arg4 startTrackingImmediately:(BOOL)arg5 ;
-(id)initializeTrackerWithClassName:(id)arg1 forViewabilityOption:(long long)arg2 withNativeVideoView:(id)arg3 startTrackingImmediately:(BOOL)arg4 ;
-(void)stopTracking:(long long)arg1 ;
-(void)dealloc;
-(void)stopTracking;
-(void)startTracking;
-(NSDictionary *)trackers;
@end

