/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MPViewabilityAdapterForWebView.h>

@class MPUBMoatWebTracker, UIView, NSString;

@interface MPViewabilityAdapterMoat : NSObject <MPViewabilityAdapterForWebView> {

	BOOL _isTracking;
	BOOL _isVideo;
	MPUBMoatWebTracker* _moatWebTracker;
	UIView* _webView;

}

@property (assign,nonatomic) BOOL isTracking;                                  //@synthesize isTracking=_isTracking - In the implementation block
@property (nonatomic,retain) MPUBMoatWebTracker * moatWebTracker;              //@synthesize moatWebTracker=_moatWebTracker - In the implementation block
@property (nonatomic,retain) UIView * webView;                                 //@synthesize webView=_webView - In the implementation block
@property (assign,nonatomic) BOOL isVideo;                                     //@synthesize isVideo=_isVideo - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)registerFriendlyObstructionView:(id)arg1 ;
-(MPUBMoatWebTracker *)moatWebTracker;
-(id)initWithWebView:(id)arg1 isVideo:(BOOL)arg2 startTrackingImmediately:(BOOL)arg3 ;
-(void)setMoatWebTracker:(MPUBMoatWebTracker *)arg1 ;
-(UIView *)webView;
-(BOOL)isTracking;
-(BOOL)isVideo;
-(void)setWebView:(UIView *)arg1 ;
-(void)setIsTracking:(BOOL)arg1 ;
-(void)setIsVideo:(BOOL)arg1 ;
-(void)stopTracking;
-(void)startTracking;
@end

