/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/MPWebViewDelegate.h>
#import <MessagesExtension/MRNativeCommandHandlerDelegate.h>

@protocol MRBridgeDelegate;
@class MPWebView, MRNativeCommandHandler, NSString;

@interface MRBridge : NSObject <MPWebViewDelegate, MRNativeCommandHandlerDelegate> {

	BOOL _shouldHandleRequests;
	id<MRBridgeDelegate> _delegate;
	MPWebView* _webView;
	MRNativeCommandHandler* _nativeCommandHandler;

}

@property (nonatomic,retain) MPWebView * webView;                                        //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) MRNativeCommandHandler * nativeCommandHandler;              //@synthesize nativeCommandHandler=_nativeCommandHandler - In the implementation block
@property (assign,nonatomic) BOOL shouldHandleRequests;                                  //@synthesize shouldHandleRequests=_shouldHandleRequests - In the implementation block
@property (assign,nonatomic,__weak) id<MRBridgeDelegate> delegate;                       //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)executeJavascript:(id)arg1 ;
-(void)fireSizeChangeEvent:(CGSize)arg1 ;
-(void)fireReadyEvent;
-(id)viewControllerForPresentingModalView;
-(void)setShouldHandleRequests:(BOOL)arg1 ;
-(BOOL)shouldHandleRequests;
-(BOOL)userInteractedWithWebView;
-(void)nativeCommandCompleted:(id)arg1 ;
-(void)nativeCommandFailed:(id)arg1 withMessage:(id)arg2 ;
-(BOOL)handlingWebviewRequests;
-(unsigned long long)adViewPlacementType;
-(void)handleMRAIDUseCustomClose:(BOOL)arg1 ;
-(void)handleMRAIDSetOrientationPropertiesWithForceOrientationMask:(unsigned long long)arg1 ;
-(void)handleMRAIDOpenCallForURL:(id)arg1 ;
-(void)handleMRAIDExpandWithParameters:(id)arg1 ;
-(void)handleMRAIDResizeWithParameters:(id)arg1 ;
-(void)handleMRAIDClose;
-(void)nativeCommandWillPresentModalView;
-(void)nativeCommandDidDismissModalView;
-(MRNativeCommandHandler *)nativeCommandHandler;
-(void)executeJavascript:(id)arg1 withVarArgs:(char*)arg2 ;
-(void)fireNativeCommandCompleteEvent:(id)arg1 ;
-(void)fireErrorEventForAction:(id)arg1 withMessage:(id)arg2 ;
-(void)loadHTMLUrl:(id)arg1 ;
-(void)fireChangeEventForProperty:(id)arg1 ;
-(void)fireChangeEventsForProperties:(id)arg1 ;
-(void)fireSetScreenSize:(CGSize)arg1 ;
-(void)fireSetPlacementType:(id)arg1 ;
-(void)fireSetCurrentPositionWithPositionRect:(CGRect)arg1 ;
-(void)fireSetDefaultPositionWithPositionRect:(CGRect)arg1 ;
-(void)fireSetMaxSize:(CGSize)arg1 ;
-(void)setNativeCommandHandler:(MRNativeCommandHandler *)arg1 ;
-(void)dealloc;
-(id<MRBridgeDelegate>)delegate;
-(void)setDelegate:(id<MRBridgeDelegate>)arg1 ;
-(MPWebView *)webView;
-(void)loadHTMLString:(id)arg1 baseURL:(id)arg2 ;
-(void)setWebView:(MPWebView *)arg1 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 ;
-(void)webViewDidStartLoad:(id)arg1 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(id)initWithWebView:(id)arg1 delegate:(id)arg2 ;
@end

