/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OMIDInmobiTreeWalkerTimeLogger;
@class NSTimer, NSDate, OMIDInmobiProcessorFactory, OMIDInmobiAdViewCache, OMIDInmobiStatePublisher;

@interface OMIDInmobiTreeWalker : NSObject {

	NSTimer* _timer;
	unsigned long long _count;
	NSDate* _date1;
	NSDate* _date2;
	id<OMIDInmobiTreeWalkerTimeLogger> _timeLogger;
	OMIDInmobiProcessorFactory* _processorFactory;
	OMIDInmobiAdViewCache* _adViewCache;
	OMIDInmobiStatePublisher* _statePublisher;

}

@property (nonatomic,readonly) OMIDInmobiProcessorFactory * processorFactory;                   //@synthesize processorFactory=_processorFactory - In the implementation block
@property (nonatomic,readonly) OMIDInmobiAdViewCache * adViewCache;                             //@synthesize adViewCache=_adViewCache - In the implementation block
@property (nonatomic,readonly) OMIDInmobiStatePublisher * statePublisher;                       //@synthesize statePublisher=_statePublisher - In the implementation block
@property (assign,nonatomic,__weak) id<OMIDInmobiTreeWalkerTimeLogger> timeLogger;              //@synthesize timeLogger=_timeLogger - In the implementation block
+(id)getInstance;
-(OMIDInmobiStatePublisher *)statePublisher;
-(void)updateTreeState;
-(void)onTick:(id)arg1 ;
-(id<OMIDInmobiTreeWalkerTimeLogger>)timeLogger;
-(void)beforeWalk;
-(void)doWalk;
-(void)afterWalk;
-(void)handleNotVisibleAdView:(id)arg1 view:(id)arg2 viewState:(id)arg3 ;
-(void)walkChildrenForView:(id)arg1 processor:(id)arg2 state:(id)arg3 type:(unsigned long long)arg4 ;
-(BOOL)handleAdView:(id)arg1 withState:(id)arg2 ;
-(void)checkFriendlyObstruction:(id)arg1 withState:(id)arg2 ;
-(void)walkView:(id)arg1 processor:(id)arg2 parentState:(id)arg3 ;
-(void)setTimeLogger:(id<OMIDInmobiTreeWalkerTimeLogger>)arg1 ;
-(OMIDInmobiProcessorFactory *)processorFactory;
-(OMIDInmobiAdViewCache *)adViewCache;
-(id)init;
-(void)pause;
-(void)stop;
-(void)start;
@end

