/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/OMIDInmobiCommandPublisher.h>
#import <MessagesExtension/OMIDInmobiSessionEventsPublisher.h>
#import <MessagesExtension/OMIDInmobiAdEventsPublisher.h>
#import <MessagesExtension/OMIDInmobiVideoEventsPublisher.h>

@protocol OMIDInmobiJSExecutor;
@class NSString;

@interface OMIDInmobiBridge : NSObject <OMIDInmobiCommandPublisher, OMIDInmobiSessionEventsPublisher, OMIDInmobiAdEventsPublisher, OMIDInmobiVideoEventsPublisher> {

	id<OMIDInmobiJSExecutor> _jsExecutor;

}

@property (nonatomic,readonly) id<OMIDInmobiJSExecutor> jsExecutor;              //@synthesize jsExecutor=_jsExecutor - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithJSExecutor:(id)arg1 ;
-(void)publishInitWithConfiguration:(id)arg1 ;
-(void)publishStartEventWithAdSessionId:(id)arg1 JSONContext:(id)arg2 verificationParameters:(id)arg3 ;
-(void)publishFinishEvent;
-(id<OMIDInmobiJSExecutor>)jsExecutor;
-(void)publishErrorWithType:(unsigned long long)arg1 errorMessage:(id)arg2 ;
-(void)internal_publishCommand:(id)arg1 ;
-(id)getStringOwner:(unsigned long long)arg1 ;
-(void)publishCommand:(id)arg1 ;
-(void)publishEventWithName:(id)arg1 parameters:(id)arg2 commandName:(id)arg3 ;
-(void)publishImpressionEvent;
-(void)publishVideoEventWithName:(id)arg1 parameters:(id)arg2 ;
@end

