/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURL, NSString;

@interface OMIDAdcolonyVerificationScriptResource : NSObject {

	NSURL* _URL;
	NSString* _vendorKey;
	NSString* _parameters;

}

@property (nonatomic,readonly) NSURL * URL;                        //@synthesize URL=_URL - In the implementation block
@property (nonatomic,readonly) NSString * vendorKey;               //@synthesize vendorKey=_vendorKey - In the implementation block
@property (nonatomic,readonly) NSString * parameters;              //@synthesize parameters=_parameters - In the implementation block
-(id)initWithURL:(id)arg1 vendorKey:(id)arg2 parameters:(id)arg3 ;
-(NSString *)vendorKey;
-(id)initWithURL:(id)arg1 ;
-(NSURL *)URL;
-(NSString *)parameters;
@end

