/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class OMIDInmobiAdSession;

@interface OMIDInmobiVideoEvents : NSObject {

	OMIDInmobiAdSession* _adSession;
	double _playerVolume;
	BOOL _observerIsRegistered;

}
-(double)deviceVolume;
-(id)initWithAdSession:(id)arg1 error:(id*)arg2 ;
-(void)playerStateChangeTo:(unsigned long long)arg1 ;
-(void)loadedWithVastProperties:(id)arg1 ;
-(void)startWithDuration:(double)arg1 videoPlayerVolume:(double)arg2 ;
-(void)firstQuartile;
-(void)thirdQuartile;
-(void)volumeChangeTo:(double)arg1 ;
-(void)adUserInteractionWithType:(unsigned long long)arg1 ;
-(void)publishEventWithName:(id)arg1 parameters:(id)arg2 requireStart:(BOOL)arg3 ;
-(void)publishEventWithName:(id)arg1 parameters:(id)arg2 ;
-(void)startListeningForDeviceVolumeChanges;
-(void)stopListeningForDeviceVolumeChanges;
-(id)stringFromPlayerState:(unsigned long long)arg1 ;
-(id)stringFromInteractionType:(unsigned long long)arg1 ;
-(void)bufferStart;
-(void)bufferFinish;
-(void)dealloc;
-(void)pause;
-(void)resume;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)complete;
-(void)midpoint;
-(void)skipped;
@end

