/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSMutableSet, OMIDAdcolonyAdSessionRegistry, NSDictionary, NSSet;

@interface OMIDAdcolonyAdViewCache : NSObject {

	NSMutableDictionary* _visibleAdViews;
	NSMutableDictionary* _friendlyObstructionInfo;
	NSMutableDictionary* _notVisibleAdViews;
	NSMutableDictionary* _notVisibleReasons;
	BOOL _isAdViewProcessed;
	NSMutableSet* _rootViews;
	NSMutableSet* _visibleSessionIds;
	NSMutableSet* _notVisibleSessionIds;
	OMIDAdcolonyAdSessionRegistry* _adSessionRegistry;

}

@property (nonatomic,readonly) OMIDAdcolonyAdSessionRegistry * adSessionRegistry;              //@synthesize adSessionRegistry=_adSessionRegistry - In the implementation block
@property (nonatomic,readonly) NSDictionary * visibleAdViews; 
@property (nonatomic,readonly) NSDictionary * friendlyObstructionInfo; 
@property (nonatomic,readonly) NSSet * rootViews; 
@property (nonatomic,readonly) NSSet * visibleSessionIds; 
@property (nonatomic,readonly) NSSet * notVisibleSessionIds; 
-(id)initWithAdSessionRegistry:(id)arg1 ;
-(NSSet *)notVisibleSessionIds;
-(id)notVisibleAdView:(id)arg1 ;
-(NSSet *)visibleSessionIds;
-(unsigned long long)typeForView:(id)arg1 ;
-(id)sessionIdForView:(id)arg1 ;
-(void)onAdViewProcessed;
-(unsigned long long)getViewHiddenReason:(id)arg1 ;
-(unsigned long long)buildRootViewsFromAdView:(id)arg1 ;
-(void)prepareFriendlyObstructionsForAdSession:(id)arg1 ;
-(void)addFriendlyObstruction:(id)arg1 forAdSession:(id)arg2 ;
-(NSDictionary *)visibleAdViews;
-(NSSet *)rootViews;
-(OMIDAdcolonyAdSessionRegistry *)adSessionRegistry;
-(id)obstructionInfoForView:(id)arg1 ;
-(NSDictionary *)friendlyObstructionInfo;
-(void)cleanup;
-(void)prepare;
@end

