/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ProtobufMessage.h>

@class NSString;

@interface OneScoreValue : NSObject <ProtobufMessage> {

	int cachedSize;
	int cachedSizeId;
	int score;
	float percentile;
	int topRank;
	NSString* userId;

}

@property (retain) NSString * userId; 
@property (assign) int score; 
@property (assign) float percentile; 
@property (assign) int topRank; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)oneScoreValueWithUserId:(id)arg1 score:(int)arg2 percentile:(float)arg3 topRank:(int)arg4 ;
-(void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2 ;
-(void)deserializeFromReader:(id)arg1 ;
-(int)sizeWithCacheId:(int)arg1 ;
-(id)initWithUserId:(id)arg1 score:(int)arg2 percentile:(float)arg3 topRank:(int)arg4 ;
-(int)topRank;
-(void)setTopRank:(int)arg1 ;
-(id)init;
-(void)dealloc;
-(int)score;
-(void)setScore:(int)arg1 ;
-(NSString *)userId;
-(void)setUserId:(NSString *)arg1 ;
-(float)percentile;
-(void)setPercentile:(float)arg1 ;
@end

