/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class PlayerIOChannel, NSString, NSArray;

@interface PIOAchievements : NSObject {

	PlayerIOChannel* _channel;
	NSString* _currentVersion;
	NSArray* _myAchievements;
	/*^block*/id _onComplete;

}

@property (retain,readonly) NSArray * myAchievements;              //@synthesize myAchievements=_myAchievements - In the implementation block
@property (copy) id onComplete;                                    //@synthesize onComplete=_onComplete - In the implementation block
+(id)newPIOAchievement:(id)arg1 ;
-(NSArray *)myAchievements;
-(void)refreshed:(id)arg1 ;
-(void)refreshWithSuccessBlock:(/*^block*/id)arg1 errorBlock:(/*^block*/id)arg2 ;
-(void)loadWithuserIds:(id)arg1 successBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(id)doneWithAchievement:(id)arg1 completedNow:(BOOL)arg2 ;
-(void)progressAddWithAchievementId:(id)arg1 progressDelta:(int)arg2 successBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(void)progressSetWithAchievementId:(id)arg1 progress:(int)arg2 successBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(void)progressMaxWithAchievementId:(id)arg1 progress:(int)arg2 successBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(void)progressCompleteWithAchievementId:(id)arg1 successBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(id)getWithAchievementId:(id)arg1 ;
-(void)refreshWithSuccessBlock:(/*^block*/id)arg1 ;
-(id)loadWithUserIds:(id)arg1 ;
-(void)loadWithuserIds:(id)arg1 successBlock:(/*^block*/id)arg2 ;
-(id)progressAddWithAchievementId:(id)arg1 progressDelta:(int)arg2 ;
-(void)progressAddWithAchievementId:(id)arg1 progressDelta:(int)arg2 successBlock:(/*^block*/id)arg3 ;
-(id)progressSetWithAchievementId:(id)arg1 progress:(int)arg2 ;
-(void)progressSetWithAchievementId:(id)arg1 progress:(int)arg2 successBlock:(/*^block*/id)arg3 ;
-(id)progressMaxWithAchievementId:(id)arg1 progress:(int)arg2 ;
-(void)progressMaxWithAchievementId:(id)arg1 progress:(int)arg2 successBlock:(/*^block*/id)arg3 ;
-(id)progressCompleteWithAchievementId:(id)arg1 ;
-(void)progressCompleteWithAchievementId:(id)arg1 successBlock:(/*^block*/id)arg2 ;
-(void)dealloc;
-(void)refresh;
-(id)load:(id)arg1 ;
-(void)setOnComplete:(id)arg1 ;
-(id)onComplete;
-(id)initWithChannel:(id)arg1 ;
@end

