/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSURLConnection, NSMutableData, NSString, NSFileHandle;

@interface PIOFileDownloader : NSObject {

	NSDate* start;
	long long expectedContentLength;
	NSURLConnection* connection;
	NSMutableData* receivedData;
	NSString* filePath;
	NSFileHandle* fileHandle;
	/*^block*/id progressBlock;
	/*^block*/id successBlockData;
	/*^block*/id successBlockFile;
	/*^block*/id errorBlock;

}
-(id)initWithUrl:(id)arg1 filePath:(id)arg2 timeout:(double)arg3 progressBlock:(/*^block*/id)arg4 successBlockData:(/*^block*/id)arg5 successBlockFile:(/*^block*/id)arg6 errorBlock:(/*^block*/id)arg7 ;
-(void)dealloc;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
@end

