/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSMutableDictionary;

@interface PIOGameFS : NSObject {

	NSString* gameId;
	NSMutableDictionary* maps;

}
-(id)initWithGameId:(id)arg1 redirectMap:(id)arg2 ;
-(id)getUrlWithPath:(id)arg1 useSecureHttp:(BOOL)arg2 ;
-(id)getUrlWithPath:(id)arg1 ;
-(void)downloadPath:(id)arg1 useSecureHttp:(BOOL)arg2 timeout:(double)arg3 progressBlock:(/*^block*/id)arg4 successBlock:(/*^block*/id)arg5 errorBlock:(/*^block*/id)arg6 ;
-(void)downloadPath:(id)arg1 toFile:(id)arg2 useSecureHttp:(BOOL)arg3 timeout:(double)arg4 progressBlock:(/*^block*/id)arg5 successBlock:(/*^block*/id)arg6 errorBlock:(/*^block*/id)arg7 ;
-(id)init;
-(void)dealloc;
@end

