/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class PlayerIOChannel, PlayerInsightState;

@interface PIOPlayerInsight : NSObject {

	PlayerIOChannel* _channel;
	PlayerInsightState* _state;
	int _playersOnline;

}

@property (readonly) int playersOnline;              //@synthesize playersOnline=_playersOnline - In the implementation block
-(void)setSegmentsWithSegments:(id)arg1 successBlock:(/*^block*/id)arg2 errorBlock:(/*^block*/id)arg3 ;
-(void)trackInvitedByWithInvitingUserId:(id)arg1 invitationChannel:(id)arg2 successBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(void)sessionKeepAliveWithSuccessBlock:(/*^block*/id)arg1 errorBlock:(/*^block*/id)arg2 ;
-(void)sessionStopWithSuccessBlock:(/*^block*/id)arg1 errorBlock:(/*^block*/id)arg2 ;
-(void)trackEventWithEventType:(id)arg1 value:(int)arg2 successBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(void)trackExternalPaymentWithCurrency:(id)arg1 amount:(int)arg2 successBlock:(/*^block*/id)arg3 errorBlock:(/*^block*/id)arg4 ;
-(id)getSegmentWithSegmentGroup:(id)arg1 ;
-(void)setSegmentsWithSegments:(id)arg1 ;
-(void)setSegmentsWithSegments:(id)arg1 successBlock:(/*^block*/id)arg2 ;
-(void)trackInvitedByWithInvitingUserId:(id)arg1 invitationChannel:(id)arg2 ;
-(void)trackInvitedByWithInvitingUserId:(id)arg1 invitationChannel:(id)arg2 successBlock:(/*^block*/id)arg3 ;
-(void)sessionKeepAlive;
-(void)sessionKeepAliveWithSuccessBlock:(/*^block*/id)arg1 ;
-(void)sessionStopWithSuccessBlock:(/*^block*/id)arg1 ;
-(void)trackEventWithEventType:(id)arg1 value:(int)arg2 ;
-(void)trackEventWithEventType:(id)arg1 value:(int)arg2 successBlock:(/*^block*/id)arg3 ;
-(void)trackExternalPaymentWithCurrency:(id)arg1 amount:(int)arg2 ;
-(void)trackExternalPaymentWithCurrency:(id)arg1 amount:(int)arg2 successBlock:(/*^block*/id)arg3 ;
-(void)refreshWithSuccessBlock:(/*^block*/id)arg1 errorBlock:(/*^block*/id)arg2 ;
-(void)refreshWithSuccessBlock:(/*^block*/id)arg1 ;
-(int)playersOnline;
-(id)initWithChannel:(id)arg1 state:(id)arg2 ;
-(void)dealloc;
-(void)refresh;
-(void)sessionStop;
@end

