/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class CodedInputStream;

@interface ProtobufReader : NSObject {

	CodedInputStream* input;
	int recursionDepth;
	int recursionLimit;

}
-(BOOL)readHeader:(int*)arg1 fieldNumber:(int*)arg2 ;
-(id)readMessage:(id)arg1 ;
-(void)skip:(int)arg1 wireType:(int)arg2 ;
-(id)init;
-(void)dealloc;
-(double)readDouble;
-(float)readFloat;
-(int)readInt32;
-(long long)readInt64;
-(int)readFixed32;
-(long long)readFixed64;
-(id)readString;
-(id)initWithInputStream:(id)arg1 ;
-(unsigned long long)readUInt64;
-(BOOL)readBool;
-(id)readBytes;
-(unsigned)readUInt32;
-(int)readSFixed32;
-(long long)readSFixed64;
-(int)readSInt32;
-(long long)readSInt64;
@end

