/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PSWebSocketDriverDelegate;
@class NSURLRequest, NSString, NSMutableArray, PSWebSocketInflater, PSWebSocketDeflater;

@interface PSWebSocketDriver : NSObject {

	NSURLRequest* _request;
	long long _state;
	BOOL _failed;
	NSString* _handshakeSecKey;
	NSMutableArray* _frames;
	BOOL _pmdEnabled;
	long long _pmdClientWindowBits;
	BOOL _pmdClientNoContextTakeover;
	long long _pmdServerWindowBits;
	BOOL _pmdServerNoContextTakeover;
	PSWebSocketInflater* _inflater;
	PSWebSocketDeflater* _deflater;
	unsigned _utf8DecoderState;
	unsigned _utf8DecoderCodePoint;
	long long _mode;
	id<PSWebSocketDriverDelegate> _delegate;
	NSString* _protocol;

}

@property (nonatomic,readonly) long long mode;                                           //@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic,__weak) id<PSWebSocketDriverDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSString * protocol;                                        //@synthesize protocol=_protocol - In the implementation block
+(BOOL)isWebSocketRequest:(id)arg1 ;
+(id)clientDriverWithRequest:(id)arg1 ;
+(id)serverDriverWithRequest:(id)arg1 ;
+(id)errorWithCode:(long long)arg1 reason:(id)arg2 ;
-(id)initWithMode:(long long)arg1 request:(id)arg2 ;
-(void)sendBinary:(id)arg1 ;
-(void)sendPing:(id)arg1 ;
-(void)sendCloseCode:(long long)arg1 reason:(id)arg2 ;
-(unsigned long long)execute:(void*)arg1 maxLength:(unsigned long long)arg2 ;
-(void)sendPong:(id)arg1 ;
-(void)writeHandshakeRequest;
-(void)writeHandshakeResponse;
-(long long)readBytes:(void*)arg1 maxLength:(unsigned long long)arg2 error:(id*)arg3 ;
-(void)failWithErrorCode:(long long)arg1 reason:(id)arg2 ;
-(void)writeMessageWithOpCode:(unsigned char)arg1 data:(id)arg2 ;
-(id)base64EncodedData:(id)arg1 ;
-(id)pmdExtensionsHeaderComponents;
-(BOOL)pmdConfigureWithExtensionsHeaderComponents:(id)arg1 ;
-(id)acceptHeaderForKey:(id)arg1 ;
-(BOOL)processFramesAndDelegate:(id*)arg1 ;
-(id<PSWebSocketDriverDelegate>)delegate;
-(void)setDelegate:(id<PSWebSocketDriverDelegate>)arg1 ;
-(void)failWithError:(id)arg1 ;
-(NSString *)protocol;
-(void)start;
-(long long)mode;
-(void)setProtocol:(NSString *)arg1 ;
-(void)sendText:(id)arg1 ;
@end

