/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableData;

@interface PSWebSocketBuffer : NSObject {

	NSMutableData* _data;
	long long _offset;
	unsigned long long _compactionLength;

}

@property (assign,nonatomic) long long offset;                                 //@synthesize offset=_offset - In the implementation block
@property (assign,nonatomic) unsigned long long compactionLength;              //@synthesize compactionLength=_compactionLength - In the implementation block
-(unsigned long long)bytesAvailable;
-(unsigned long long)compactionLength;
-(void)setCompactionLength:(unsigned long long)arg1 ;
-(void)appendBytes:(const void*)arg1 length:(unsigned long long)arg2 ;
-(id)init;
-(const void*)bytes;
-(void*)mutableBytes;
-(BOOL)hasBytesAvailable;
-(id)data;
-(void)compact;
-(void)appendData:(id)arg1 ;
-(void)reset;
-(void)setOffset:(long long)arg1 ;
-(long long)offset;
@end

