/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MessagesExtension/MessagesExtension-Structs.h>
@class NSMutableData;

@interface PSWebSocketInflater : NSObject {

	long long _windowBits;
	unsigned char _chunkBuffer[16384];
	z_stream_s* _stream;
	BOOL _ready;
	NSMutableData* _buffer;

}
-(BOOL)begin:(id)arg1 error:(id*)arg2 ;
-(BOOL)appendBytes:(const void*)arg1 length:(unsigned long long)arg2 error:(id*)arg3 ;
-(id)initWithWindowBits:(long long)arg1 ;
-(BOOL)ensureReady:(id*)arg1 ;
-(void)dealloc;
-(void)reset;
-(BOOL)end:(id*)arg1 ;
@end

