/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/GameSettings.h>
#import <UIKit/UITextFieldDelegate.h>

@class SettingsOptionPartition, UILabel, NSString, UITextField;

@interface QuestionsSettings : GameSettings <UITextFieldDelegate> {

	SettingsOptionPartition* part1;
	UILabel* tip;
	UILabel* tip2;
	NSString* mode;
	UITextField* myTextField;

}

@property (retain) NSString * mode; 
@property (retain) UITextField * myTextField; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)Sel;
-(UITextField *)myTextField;
-(void)setMyTextField:(UITextField *)arg1 ;
-(id)init;
-(void)setMode:(NSString *)arg1 ;
-(NSString *)mode;
-(void)update;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(void)blink;
-(void)resize;
@end

