/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <MessagesExtension/GameScene.h>

@class NSString, RenjuStone, SKSpriteNode, ActionButton, TipNode, NSMutableArray, Sprite, SKNode, YouNode, NSDate, SKShapeNode, SKLabelNode;

@interface RenjuScene : GameScene {

	NSString* player_id1;
	NSString* player_id2;
	RenjuStone* piece;
	RenjuStone* piece2;
	SKSpriteNode* board;
	ActionButton* actionButton;
	TipNode* tip;
	NSMutableArray* win_stones;
	NSMutableArray* win_highlights;
	SKSpriteNode* highlight;
	Sprite* highlight2;
	NSMutableArray* pieces;
	NSMutableArray* dangers;
	NSMutableArray* map;
	SKNode* selected;
	float gap;
	float tile;
	BOOL sent;
	YouNode* you;
	float top;
	float bottom;
	float bottom2;
	float pressure;
	int time;
	NSMutableArray* replay;
	int player;
	int received;
	int state;
	BOOL mine;
	float left;
	float right;
	SKSpriteNode* basket1;
	SKSpriteNode* basket2;
	int win_state;
	NSMutableArray* particles;
	NSDate* last_swoosh;
	SKShapeNode* _spinnyNode;
	SKLabelNode* _label;

}
-(id)initWithMain:(id)arg1 msg:(id)arg2 ;
-(void)createSceneContents;
-(void)receiveMessage:(id)arg1 ;
-(id)generatePreview;
-(void)savePlaceBack:(id)arg1 what:(id)arg2 ;
-(void)placeBack:(id)arg1 ;
-(void)touchDownAtPoint:(CGPoint)arg1 ;
-(void)touchMovedToPoint:(CGPoint)arg1 ;
-(void)touchUpAtPoint:(CGPoint)arg1 ;
-(id)getPreview;
-(int)checkWin;
-(void)swoosh;
-(void)sendComplete;
-(id)newPiece;
-(void)showDanger;
-(void)replayMove;
-(void)Dust:(CGPoint)arg1 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)didMoveToView:(id)arg1 ;
-(void)update:(double)arg1 ;
-(void)sendMessage;
-(void)didChangeSize:(CGSize)arg1 ;
-(void)resize;
@end

