/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/MessagesExtension-Structs.h>
#import <SpriteKit/SKNode.h>

@class SKLabelNode, NSString, SKSpriteNode;

@interface TipNode : SKNode {

	SKLabelNode* tip;
	SKLabelNode* tip2;
	NSString* dots;
	float max_width;
	SKSpriteNode* border;
	NSString* string;
	CGSize offset;

}

@property (retain) NSString * string; 
@property (retain) SKSpriteNode * border; 
@property (assign) CGSize offset; 
@property (assign) float max_width; 
-(void)setBorder:(BOOL)arg1 color:(id)arg2 ;
-(void)setArrow;
-(void)setTip:(id)arg1 color:(id)arg2 size:(float)arg3 ;
-(void)stopBlinking;
-(void)setTip:(id)arg1 save:(BOOL)arg2 ;
-(void)startBlinking;
-(float)max_width;
-(void)setMax_width:(float)arg1 ;
-(id)init;
-(NSString *)string;
-(void)setString:(NSString *)arg1 ;
-(void)setOffset:(CGSize)arg1 ;
-(void)setColor:(id)arg1 ;
-(CGSize)offset;
-(void)setTip:(id)arg1 ;
-(void)setBorder:(SKSpriteNode *)arg1 ;
-(SKSpriteNode *)border;
-(void)dot;
@end

