/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ProtobufMessage.h>

@class NSString, NSData, NSMutableArray;

@interface ValueObject : NSObject <ProtobufMessage> {

	int cachedSize;
	int cachedSizeId;
	BOOL _bool;
	int valueType;
	int _int;
	unsigned uInt;
	float _float;
	NSString* string;
	long long _long;
	double _double;
	NSData* byteArray;
	long long dateTime;
	NSMutableArray* arrayProperties;
	NSMutableArray* objectProperties;

}

@property (assign) int valueType; 
@property (retain) NSString * string; 
@property (assign) int _int;                                        //@synthesize int=_int - In the implementation block
@property (assign) unsigned uInt; 
@property (assign) long long _long;                                 //@synthesize long=_long - In the implementation block
@property (assign) BOOL _bool;                                      //@synthesize bool=_bool - In the implementation block
@property (assign) float _float;                                    //@synthesize float=_float - In the implementation block
@property (assign) double _double;                                  //@synthesize double=_double - In the implementation block
@property (retain) NSData * byteArray; 
@property (assign) long long dateTime; 
@property (retain) NSMutableArray * arrayProperties; 
@property (retain) NSMutableArray * objectProperties; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)valueObjectWithValueType:(int)arg1 string:(id)arg2 int:(int)arg3 uInt:(unsigned)arg4 long:(long long)arg5 _Bool:(BOOL)arg6 float:(float)arg7 double:(double)arg8 byteArray:(id)arg9 dateTime:(long long)arg10 arrayProperties:(id)arg11 objectProperties:(id)arg12 ;
-(void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2 ;
-(void)deserializeFromReader:(id)arg1 ;
-(int)sizeWithCacheId:(int)arg1 ;
-(id)initWithValueType:(int)arg1 string:(id)arg2 int:(int)arg3 uInt:(unsigned)arg4 long:(long long)arg5 _Bool:(BOOL)arg6 float:(float)arg7 double:(double)arg8 byteArray:(id)arg9 dateTime:(long long)arg10 arrayProperties:(id)arg11 objectProperties:(id)arg12 ;
-(int)_int;
-(void)set_int:(int)arg1 ;
-(unsigned)uInt;
-(void)setUInt:(unsigned)arg1 ;
-(long long)_long;
-(void)set_long:(long long)arg1 ;
-(BOOL)_bool;
-(void)set_bool:(BOOL)arg1 ;
-(void)set_float:(float)arg1 ;
-(double)_double;
-(void)set_double:(double)arg1 ;
-(NSData *)byteArray;
-(void)setByteArray:(NSData *)arg1 ;
-(NSMutableArray *)arrayProperties;
-(void)setArrayProperties:(NSMutableArray *)arg1 ;
-(NSMutableArray *)objectProperties;
-(void)setObjectProperties:(NSMutableArray *)arg1 ;
-(id)init;
-(NSString *)string;
-(void)dealloc;
-(void)setString:(NSString *)arg1 ;
-(int)valueType;
-(void)setValueType:(int)arg1 ;
-(long long)dateTime;
-(void)setDateTime:(long long)arg1 ;
-(float)_float;
@end

