/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 18, 2020 at 5:59:19 AM Central Daylight Time
* Operating System: Version 13.3 (Build 17C54)
* Image Source: /private/var/containers/Bundle/Application/97E911F0-28BD-48AC-8574-5B9D68F985F0/Game Pack.app/PlugIns/MessagesExtension.appex/MessagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MessagesExtension/ProtobufMessage.h>

@class NSString, NSMutableArray;

@interface WriteErrorArgs : NSObject <ProtobufMessage> {

	int cachedSize;
	int cachedSizeId;
	NSString* source;
	NSString* error;
	NSString* details;
	NSString* stacktrace;
	NSMutableArray* extraData;

}

@property (retain) NSString * source; 
@property (retain) NSString * error; 
@property (retain) NSString * details; 
@property (retain) NSString * stacktrace; 
@property (retain) NSMutableArray * extraData; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)writeErrorArgsWithSource:(id)arg1 error:(id)arg2 details:(id)arg3 stacktrace:(id)arg4 extraData:(id)arg5 ;
-(void)serializeToWriter:(id)arg1 sizeCacheId:(int)arg2 ;
-(void)deserializeFromReader:(id)arg1 ;
-(int)sizeWithCacheId:(int)arg1 ;
-(id)initWithSource:(id)arg1 error:(id)arg2 details:(id)arg3 stacktrace:(id)arg4 extraData:(id)arg5 ;
-(void)setStacktrace:(NSString *)arg1 ;
-(id)init;
-(void)dealloc;
-(void)setSource:(NSString *)arg1 ;
-(NSString *)source;
-(NSString *)error;
-(void)setError:(NSString *)arg1 ;
-(NSString *)details;
-(void)setDetails:(NSString *)arg1 ;
-(void)setExtraData:(NSMutableArray *)arg1 ;
-(NSMutableArray *)extraData;
-(NSString *)stacktrace;
@end

